### ISSUE TITLE
Audio stuttering while streaming

### ISSUE THREAD

**Issue by mattiasdrp** [streamlink/streamlink-twitch-gui#1000]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.4.1

### Streamlink version

6.1.0

### Operating system, environment and configuration details

Windows 10 21H2

### Description

Video is smooth but audio is continuously stuttering. I tried changing hls-live-edge and stream-segment-threads but nothing changed. I tried watching the stream with a low quality but same problem. You can hear how it sounds in this clip:

https://github.com/streamlink/streamlink-twitch-gui/assets/5543639/8606f769-e3e4-419e-9e75-f0dd9aa80a74

**Comment by bastimeyer** [comment]
Neither a **Streamlink Twitch GUI** issue, nor a **Streamlink** issue.

This is a rendering issue of your player while consuming Streamlink's output after a stream discontinuity, where decoding- and presentation-timestamps are messed up. Stream discontinuities are explicitly unsupported by Streamlink. I don't know about VLC, but MPV handles this well in most cases, and when not, you can simply clear its buffer by pressing enter (re-reading Streamlink's output).

**Comment by mattiasdrp** [comment]
Thanks for you answer and sorry for the noise, I'll try with MPV

**Comment by bastimeyer** [comment]
All good...
btw: stream discontinuities = transitions when ads get embedded into the stream by Twitch
