### ISSUE TITLE
Window `restore` event doesn't trigger when unmaximizing

### ISSUE THREAD

**Issue by cadbusca** [streamlink/streamlink-twitch-gui#1009]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.5.1

### Operating system, environment and configuration details

Manjaro Linux / KDE / X11

### Description

Clicking on the '-' and '+' buttons sometimes works as expected, but, most of the time it doesn't (has no effect).

The issue is not consistent and start happening after clicking a few times on those buttons or interacting with the UI. 
Right after opening Streamlink Twitch GUI It usually works fine, then you open a stream and after a while decide to use those buttons and the issue starts to happen.
Double-clicking the app's header bar fix the issue for a while, but not permanently.

This issue does not happen on v2.4.1

**Comment by bastimeyer** [comment]
No reason to open another issue for this. I am aware and have already explained it in #1008.
There will be a downgrade to NW.js 0.80 which will resolve the issue.

**Comment by cadbusca** [comment]
Thanks

**Comment by bastimeyer** [comment]
The issue currently can't be fixed. Please see the linked NW.js versions meta thread above...

For now, I've disabled storing the maximized window state, so that the app doesn't launch maximized. If you want to unmaximize the window, double-click the window drag area or use your system's window manager. The maximize button depends on the internal window state, which is broken due to an NW.js issue.

**Comment by bastimeyer** [comment]
Resolved by 381a9a5cb507ed689b2127ad6afb67127582eef8 / ab45651abefddd9d39d515f184648214ba810c1b
See #1015
