### ISSUE TITLE
Custom protocol handler support (e.g. `streamlink://`)

### ISSUE THREAD

**Issue by Victor239** [streamlink/streamlink-twitch-gui#1013]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

There was a feature request about this a [few years ago](https://github.com/streamlink/streamlink-twitch-gui/issues/613), I was wondering if this feature would be considered again now. My usecase is that I'd like to automatically redirect Twitch links in my browser to open in Streamlink Twitch GUI, and having this feature would enable the redirecting to be handled [using LibRedirect](https://github.com/libredirect/browser_extension/issues/924).

**Comment by bastimeyer** [comment]
Same reasoning
https://github.com/streamlink/streamlink-twitch-gui/issues/613#issuecomment-454630188

**Comment by Victor239** [comment]
This looks like a [NodeJS package](https://www.npmjs.com/package/protocol-registry) that supports it and is cross-platform.

**Comment by Victor239** [comment]
@bastimeyer is this package suitable?

**Comment by Victor239** [comment]
It has multiple benefits if you read the LibRedirect repo, this would be one of dozens of open-source frontends that people use to interact with proprietary web services. 

I'm new to using this particular app so I haven't seen it mentioned anywhere that this app is in maintenance mode. If that's the case you should put a notice in the README + a pinned issue like most projects do.

**Comment by bastimeyer** [comment]
> It has multiple benefits if you read the LibRedirect repo, this would be one of dozens of open-source frontends that people use to interact with proprietary web services.

This has nothing to do with **Streamlink Twitch GUI** though. You are looking for a way to launch streams using **Streamlink** via your web browser, which this application here is not meant for.
