### ISSUE TITLE
Can auto-update check be suppressed on first launch?

### ISSUE THREAD

**Issue by metaad** [streamlink/streamlink-twitch-gui#1016]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Can you please suggest or provide setting that is stored in file/registry to suppress auto-update check when shortcut of old version is launched for the first time. Looking for the setting which will disable the pop-up.

![image](https://github.com/streamlink/streamlink-twitch-gui/assets/106653425/80d72cce-569c-4dce-8909-8ba9d0b56ea1)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--no-version-check
