### ISSUE TITLE
AppImage: cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by ITIRadio** [streamlink/streamlink-twitch-gui#1020]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.5.2-i686

### Streamlink version

5.2.1-1

### Operating system, environment and configuration details

Debian GNU/Linux 12 (bookworm) aarch64 

### Description

I installed Streamlink using the command line, as per instructions, and not into a special path. I downloaded the Streamlink Twitch GUI AppImage, set to all users may execute permissions. Then, upon typing in the command:

$ ./streamlink-twitch-gui-v2.5.2-i686.AppImage
bash: ./streamlink-twitch-gui-v2.5.2-i686.AppImage: cannot execute binary file: Exec format error

I have no idea how to proceed...is this really that broken with Debian?

Basic System Info from neofetch:

OS: Debian GNU/Linux 12 (bookworm) aarch64 
Host: Raspberry Pi 4 Model B Rev 1.5 
ernel: 6.6.31+rpt-rpi-v8 
Uptime: 1 hour, 7 mins 
Packages: 1594 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: LXDE-pi-wayfire 
WM: wayfire 
Theme: PiXflat [GTK3] 
Icons: PiXflat [GTK3] 
Terminal: lxterminal 
Terminal Font: Monospace 18 
CPU: (4) @ 1.800GHz 
Memory: 2188MiB / 7810MiB

**Comment by bastimeyer** [comment]
> Debian GNU/Linux 12 (bookworm) aarch64

Only x86_64 and i686 are supported, as you can clearly see in the AppImage's filename, for example: `streamlink-twitch-gui-v2.5.2-x86_64.AppImage`
