### ISSUE TITLE
Allow following channels through the app

### ISSUE THREAD

**Issue by billbeans** [streamlink/streamlink-twitch-gui#1026]
### Checklist

- [x] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [x] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

The "Follow" button on channel pages is misleading. It simply opens up the default browser to the channel page. I'm not sure if this is even possible through the Twitch API, but either way it's annoying and not accurate. I clear cookies on every browser exit, so to follow a channel I found through the GUI I have to sign in again.

**Comment by bastimeyer** [comment]
> The "Follow" button on channel pages is misleading.

Oh really?
#813
