### ISSUE TITLE
Add last watched list

### ISSUE THREAD

**Issue by killerpommes** [streamlink/streamlink-twitch-gui#162]
Hi, 
Often i browse through the gamelist and watch a streamer.
After i watched "him" for a while i close the stream. Of course i forget what user i watched and did not follow.

It would  be cool to have a last watched streamer list.
Of course only if it is not a too big problem.

Greetings

**Comment by bastimeyer** [comment]
Yeah, I already had something like this planned when I started working on the app (see the old screenshots). I ended up removing it from the menu, because there were some issues with the data adapter and the way how the data was stored.
