### ISSUE TITLE
"Check for update" button in settings

### ISSUE THREAD

**Issue by sjasct** [streamlink/streamlink-twitch-gui#190]
A "check for application update" would be great for those who know that there is an update but have ignored it before.

**Comment by bastimeyer** [comment]
When clicking the ignore button, the popup will reappear after 7 days, so there actually is no real need for adding this feature, *unless* there was a critical bugfix update, etc.
But yeah, I can of course add something like that when I'm done implementing the download mechanism for the (Windows) installer. See #145
