### ISSUE TITLE
feature request: store a local list of channels to hide

### ISSUE THREAD

**Issue by untoreh** [streamlink/streamlink-twitch-gui#199]
How do you feel about a list stored locally of channels that automatically get hidden from browsing ?

**Comment by bastimeyer** [comment]
See https://github.com/bastimeyer/livestreamer-twitch-gui/issues/193#issuecomment-170468772 ...
The same issue also applies to channel lists.

This means that I don't want to implement anything that removes or filters list items, **unless** this can be achieved by using Twitch's user block list. The Twitch API does support [blocking users](https://github.com/justintv/Twitch-API/blob/master/v3_resources/blocks.md), but I think blocks don't apply to channel/stream lists, right? Does anybody know? The required OAuth scopes for adding and removing blocks [are already included](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/v0.11.2/package.json#L67-L68).

**Comment by natostanco** [comment]
I indeed looked up that issue before posting this, I didn't get from that that you don't want to add options not included in the twitch api

**Comment by bastimeyer** [comment]
This can't be implemented due to missing support of the Twitch API. I should have closed this thread a long time ago.
Related:
#193
#219
