### ISSUE TITLE
OS X user other than installing user can't open app

### ISSUE THREAD

**Issue by NilsEnevoldsen** [streamlink/streamlink-twitch-gui#210]
Replication:
1. Install app as user Alice
2. Try to run app as user Bob
3. Receive error about PowerPC applications not being supported

The issue appears to be permissions on the executable files:
- `/Applications/Livestreamer Twitch GUI.app/Contents/MacOS/nwjs`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Framework.framework/nwjs Framework`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper.app/Contents/MacOS/nwjs Helper`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper EH.app/Contents/MacOS/nwjs Helper EH`
- `/Applications/Livestreamer Twitch GUI.app/Contents/Frameworks/nwjs Helper NP.app/Contents/MacOS/nwjs Helper NP`

Running `sudo chmod [file] a+rx` on these files fixes the issue.

**Comment by bastimeyer** [comment]
`700` are the default file permissions of all executables in the .app folder.

These are set by the [NW.js archive](http://dl.nwjs.io/v0.12.3/nwjs-v0.12.3-osx-x64.zip) which is being downloaded by [`nw-builder`](https://github.com/nwjs/nw-builder). The builder doesn't change any file permissions. That was the reason why the *first* OSX builds of the current release were corrupted (#200)...

I don't want to manipulate the OSX build procedure here...
Please report this issue over there at the [`nw-builder`](https://github.com/nwjs/nw-builder) repo or maybe even the [`NW.js`](https://github.com/nwjs/nw.js) repo.

Thanks!

**Comment by bastimeyer** [comment]
I decided to include a fix for this issue here, since the nw-builder maintainers seem to be inactive again and are not interested in a fix.

The new NW.js builds on Linux also have invalid file permissions set (only user permissions). The solution for this mess is simply running `chmod -R g=u,o=u,g-w,o-w /path/to/app`, which copies user permissions to group and other and removes write flags on those.
