### ISSUE TITLE
Error in the 'Hosted Streams' page

### ISSUE THREAD

**Issue by MrLint** [streamlink/streamlink-twitch-gui#307]
## When trying to see the hosted streams I am now getting this error info

Error
There was an error while trying to display this page.

Name
TypeError
Message

**Comment by MrLint** [comment]
![2016-09-13 19_55_07-livestreamer twitch gui](https://cloud.githubusercontent.com/assets/18565454/18495455/0de14b0e-79ec-11e6-82eb-b404defaa400.png)

**Comment by bastimeyer** [comment]
I don't know what is causing this, but it doesn't seem to be an API change, although we are using the private Twitch API in the hosted streams menu. I'm not getting this kind of error and haven't seen this before.

Somehow the API response is causing EmberData to throw this error, and I'd like to know if it is differing from the one expected by the [StreamsHosted](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/6016bbfbfef3882d53ca86d6d0e926817cdd4e6b/src/app/models/twitch/StreamsHosted.js) model and [StreamsHostedSerializer](https://github.com/bastimeyer/livestreamer-twitch-gui/blob/6016bbfbfef3882d53ca86d6d0e926817cdd4e6b/src/app/models/twitch/StreamsHostedSerializer.js). Maybe the target property is missing causing the belongsTo model-relationship to break.

Is this error still happening? Can you tell me which channels you are following that are hosting other channels right now? Please check the Twitch website for this. Or even better, can you tell me the exact payload that is causing EmberData to return this error? Please open the application with the `--remote-debugging-port=8888` parameter, open `http://localhost:8888` in your web browser, click the `Livestreamer Twitch GUI` link, click on the `Network` tab and browse to the hosted streams menu in the GUI. You will see the `hosting` request being made to the Twitch servers. I'd like to know the data of the request's response tab, a JSON string. It will include your Twitch name, though. If you don't want this, just remove this part. Thanks!

*It looks like this and I need all of the data:*
![screenshot from 2016-09-14 05-06-07](https://cloud.githubusercontent.com/assets/467294/18498732/102abd12-7a39-11e6-806d-f4cc4ef8717c.png)

**Comment by MrLint** [comment]
Hi thanks for the response. I fired up LS at work and the hosted section is not giving the same behavior here. I'm going to make sure my local AV suite isn't some how getting involved. But i'll try and get the info you were looking for regardless.

**Comment by MrLint** [comment]
Sabastian,

So today this behavior has returned to normal. Perhaps twitched just wigged out for a while? If it would be helpful to collect further info I'd be glad to

**Comment by bastimeyer** [comment]
It must have been an issue with the Twitch API, but what worries me is that it caused EmberData to throw an error, which is not supposed to happen. If you see it happen again, just try to get and post the JSON string that's causing this. Thanks!

The Twitch API has been very unstable for the last few days. Maybe this is because of their recent API change (#310), coupled with an infrastructure change, who knows. This change btw broke Livestreamer and required me to push `v0.15.0` an hour ago.

**Comment by bastimeyer** [comment]
Let's close this thread. If this happens again, please feel free to reopen.
