### ISSUE TITLE
Add other services

### ISSUE THREAD

**Issue by vidje** [streamlink/streamlink-twitch-gui#309]
Is it possible for you to extend the gui beyond twitch and add other services, most notably crunchy roll?

**Comment by bastimeyer** [comment]
I already gave an answer about outher streaming services here: #192 
Crunchyroll is this anime site, right? Even if I would find the time and motivation to implement other services supported by livestreamer, gaming unrelated ones or those which I don't have any interest in would not be included here. The project's licence allows anyone to fork it, though. If there are other maintainers who are active and are willing to work on this here I would have nothing against it. A rebrand of the project would be required, though.

On a side note, livestreamer is not being actively maintained anymore, so adding more streaming services is even more risky. See #289
