### ISSUE TITLE
Error with exit code 3221225781

### ISSUE THREAD

**Issue by azrulnene** [streamlink/streamlink-twitch-gui#347]
### Description
When trying to watch live stream this error pops up
![capture](https://cloud.githubusercontent.com/assets/24377081/20870202/21a106d4-babf-11e6-94c7-352d1c075219.JPG)

Need help resolve this issue.

Thanks

**Comment by bastimeyer** [comment]
- Which OS are you using?
- How did you install Streamlink?
- Are you using custom settings in the Twitch GUI?
- Does this also happen when using the Streamlink CLI?

**Comment by azrulnene** [comment]
- Which OS are you using?
   Windows 7 ultimate 64bit

   - How did you install Streamlink?
   https://github.com/streamlink/streamlink/releases/tag/0.1.0
   I install this version of streamlink

   - Are you using custom settings in the Twitch GUI?
   Nope no custom setting only using default settings
   https://github.com/streamlink/streamlink-twitch-gui/releases
   using streamlink twitch GUI v1.0.0

   - Does this also happen when using the Streamlink CLI?
   Whats streamlink CLI, i dont understand this one.

   I used to use livestreamer before it ask me to update to streamlink. i
   had no problem using livestreamer, but when i change to streamlink twitch
   Gui, the error pops.

**Comment by bastimeyer** [comment]
> Whats streamlink CLI, i dont understand this one.

CLI = Command line interface
Does Streamlink work without the GUI when running it from the Windows cmd shell?

A custom python installation on your system could interfere with Streamlink if you're using default settings. Please make sure that the correct python executable and streamlink-script.py are being selected.

**Comment by azrulnene** [comment]
I cant find the streamline-script.py

On Dec 5, 2016 4:37 PM, "Sebastian Meyer" <notifications@github.com> wrote:

Whats streamlink CLI, i dont understand this one.

CLI = Command line interface
Does Streamlink work without the GUI when running it from the Windows cmd
shell?

A custom python installation on your system could interfere with Streamlink
if you're using default settings. Please make sure that the correct python
executable and streamlink-script.py are being selected.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/streamlink/streamlink-twitch-gui/issues/347#issuecomment-264795405>,
or mute the thread

**Comment by bastimeyer** [comment]
> streamline-script.py

The **streamlink-script.py** file is located in the `%PROGRAMFILES(X86)%\Streamlink\bin` folder (eg. `C:\Program Files (x86)\Streamlink\bin`) when using the Streamlink installer.

**Comment by azrulnene** [comment]
![capture1](https://cloud.githubusercontent.com/assets/24377081/20881620/262e011c-bb18-11e6-9d27-f4884c894090.JPG)

Still cant watch the stream. Still same error

**Comment by bastimeyer** [comment]
Can you please run streamlink via the "terminal", as I've already asked you, and then see if this is the cause for this?

`streamlink twitch.tv/CHANNEL best`

**Comment by azrulnene** [comment]
Can you please run streamlink via the "terminal" ? I'm not following you. I dont understand.

**Comment by bastimeyer** [comment]
It seems like you don't know what **Streamlink** and **Streamlink Twitch GUI** are. I don't know how I can help you then.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation

The issue you're having is not related to Streamlink Twitch GUI, but instead caused by a misconfiguration of your system, causing Streamlink to fail. If you don't know how to use Streamlink, please [read the documentation](https://streamlink.github.io/cli.html) first, otherwise I'm not able to help.

**Comment by azrulnene** [comment]
![capture](https://cloud.githubusercontent.com/assets/24377081/20882445/efcefe4c-bb1b-11e6-9904-3027c6c3ad24.JPG)

is this the terminal you were talking about?

**Comment by azrulnene** [comment]
Like i said, last time i use livestreamer, i saw this video on youtube https://www.youtube.com/watch?v=k0D0HkYzHp4 from here it was a success. then when i update to streamlink, the error pops, thats my problem that i dont know why. i follow this video guide on how to use livestreamer, but streamlink its new and no video to follow and understand how to use.

**Comment by bastimeyer** [comment]
streamlink/streamlink#246

Please download and install the Visual C++ Redistributable package and then install Streamlink again
https://www.microsoft.com/en-us/download/details.aspx?id=48145

**Comment by Vangelis66** [comment]
@azrulnene asked: 

> is this the terminal you were talking about? 

The _terminal_ equivalent on Windows is called 
the **Windows command prompt window** (or console)

On Win7, 
Start Button => All Programs => Accessories => Command Prompt

If you need to run with admin rights, 
Start Button => Start Search =>type **cmd** => in the results, 
right click **cmd.exe** and then choose **Run as administrator**

When you were aked to **run streamlink via the "terminal"**, 
you should have typed/pasted in the command prompt 
`streamlink twitch.tv/CHANNEL best` and hit `ENTER`
(CHANNEL the twitch channel you'd like to stream)

It appears you don't know how to run CLI apps, 
that's alright, many Windows users only know GUI apps, 
but Google (or the like) is your friend when you have 
knowledge gaps...

Hope I've helped :wink:

**Comment by bastimeyer** [comment]
@azrulnene Did you manage to solve this issue by installing the Visual C++ Redistributable package and reinstalling Streamlink?

**Comment by donalld** [comment]
Hi! I'm having same issue! when I try to launch streamlink com command prompt appears this error:

C:\Program Files (x86)\Streamlink\bin>streamlink twitch.tv/ecs_br high

failed to create process.

**Comment by bastimeyer** [comment]
Please read the comments above or the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation#streamlink

The Windows installer of the current Streamlink release doesn't install the necessary runtime libraries on Windows versions prior to 10. Either install these by yourself, or use one of the recent [nightly builds](https://streamlink.github.io/install.html#windows-binaries) of Streamlink, or wait for the `0.2.0` release.

**Comment by donalld** [comment]
Worked fine with last nightly build!

Thank you
