### ISSUE TITLE
Can't Maximize

### ISSUE THREAD

**Issue by fafa1510** [streamlink/streamlink-twitch-gui#350]
### Description
When stream is launched the maximize button doesn't work

### Expected / Actual behavior

Maximization 

### Reproduction steps

1. Open Streamlink Twitch GUI
2. Launch a stream
3. Streamlink Twitch GUI
4. Click on '+'
5. Nothing append

### Environment details (operating system, etc.)

- Win10 Pro up to date
- VLC 2.2.4
- Streamlink Twitch GUI - Stable version 
- streamlink 0.1.0

**Comment by bastimeyer** [comment]
> When stream is launched

Do you mean while having the stream launch popup / dialog box opened?

That's a design choice and none of the elements of the titlebar are clickable. The popup has to be closed first, either by pressing the continue button (the purple button with the arrow) or by closing the stream.

There's an option in the stream settings menu for automatically closing the popup on a successful stream launch.

**Comment by fafa1510** [comment]
No, it's happen after close the popup / dialog box.

The issue persist if I close all stream

I just remark now the issue is happend when I change the displayed page

So the maximize button work only when I launch the GUI and stop work when I do anything.

The workaround i've found is quit the GUI and relaunch it

Record of issue here: http://sendvid.com/a13m2rsu

**Comment by bastimeyer** [comment]
Yep, that's a bug.
The maximize button does only work once. There must have gone something wrong during the transition to the new NW.js.

The window can still be maximized by using other methods (hotkeys, etc), depending on the operating system, desktop environment / window manager and configuration.

**Comment by bastimeyer** [comment]
Thanks for reporting the issue!
