### ISSUE TITLE
Set default window (or tab?)

### ISSUE THREAD

**Issue by NuMs1** [streamlink/streamlink-twitch-gui#353]
Heya, small QoL issue.

In the old twitch GUI on application load it would default to the My > Live Streams tab, the new version however will default to the Browse > Featured tab.

I don't know if it was a setting on the old one that didn't make it to the new one or if i'm just missing it, if not, please consider adding an option allowing users to set which tab to default to when opened, similar to how steam allows you to [pick which window](http://puu.sh/sGKau/d04a050312.png) to display when opened.

Keep up the awesome work! :)

**Comment by 404NetworkError** [comment]
You missed a setting just like I did.

To fix it, go to the tab which you would like set as your default.  In the top right, there is a three dot menu.  Open that menu and select the blue home button.  This will set your homepage.

**Comment by bastimeyer** [comment]
> similar to how steam allows you to pick which window to display when opened

A similar option doesn't make sense, because this doesn't support setting `/games/:game` routes as homepage.

Thanks @404NetworkError for answering

**Comment by NilsEnevoldsen** [comment]
Let me add to those who expected a setting like the one @NuMs1 described, and came here to report a feature request, only to discover @404NetworkError's answer.

@bastimeyer, is the issue you discuss the only problem with adding such an option? If so, perhaps we could brainstorm a UI that worked.

Off the top of my head (I'm not proposing this as the perfect solution) there could be a "start tab" menu in settings to select any of the default tabs, together with a text notice, "To set any other tab as your start tab, click the 🏠 icon on that tab".

**Comment by bastimeyer** [comment]
This would all be redundant and even more confusing. The UI element you're describing is only half-complete with missing dynamic routes. Providing an UI element where you can set dynamic routes is error prone when it doesn't have a visual feedback for the user. Adding visual feedback where the input is being used as a Twitch API query is a bunch of work if done correctly.

I think this is all unnecessary. A reference text describing menu specific settings could be added, though.

**Comment by NilsEnevoldsen** [comment]
> A reference text describing menu specific settings could be added, though.

This is exactly the kind of brainstorming I had in mind. Yes, this is a better solution. If such a reference text appeared in settings, I would have found it easily. I support this idea.

**Comment by bastimeyer** [comment]
> I support this idea.

It's already been added, forgot to reference this thread in the commit msg
7c086fe80c09d461e95b49c07a1bfff981f163eb
