### ISSUE TITLE
Single instance mode Error on macOS

### ISSUE THREAD

**Issue by 404NetworkError** [streamlink/streamlink-twitch-gui#354]
### Description

I receive an `error: Failed to start player: /Applications/VLC.app/Contents/MacOS/VLC (Process exited prematurely)` when using the Single instance mode option (which is on by default).

### Environment details (operating system, etc.)

OS X 10.11.6
VLC 2.2.4-g2fc51dd (release 2.2.4 build)
Streamlink Twitch GUI v1.0.0

### Comments, logs, screenshots, etc.

I believe the problem stems from this version of VLC not having `--no-one-instance` as an option.  As a suggestion, you may want to either uncheck it by default or remove the option entirely for the Mac version.  I can confirm that the problem persists if VLC or streamlink is run from the CLI with this option.  The error is `vlc: unknown option or missing mandatory argument '--no-one-instatnce'`.

**Comment by bastimeyer** [comment]
> I believe the problem stems from this version of VLC not having --no-one-instance as an option.

Yep, I was unaware of this and didn't test it on MacOS. I will extend the preset system by platform dependent player parameters and will then remove this parameter from MacOS.

Thanks for reporting
