### ISSUE TITLE
Player window title Error on macOS

### ISSUE THREAD

**Issue by 404NetworkError** [streamlink/streamlink-twitch-gui#355]
### Description

I receive this error from VLC when using the Set custom title option:
![streamlink-twitch-gui_vlc_error](https://cloud.githubusercontent.com/assets/10837458/20953423/243d335a-bbf9-11e6-8139-220d98577f63.png)

### Environment details (operating system, etc.)

OS X 10.11.6
VLC 2.2.4-g2fc51dd (release 2.2.4 build)
Streamlink Twitch GUI v1.0.0

### Comments, logs, screenshots, etc.

I was able to stop this from happening by passing `--verbose=0` to VLC through the Custom parameters.    I have not tried passing other options to VLC.  The problem does not happen when executing VLC or streamlink from the CLI.

**Comment by bastimeyer** [comment]
The `--meta-title` parameter needs to be changed to `--input-title-format`. For some reason, VLC on MacOS doesn't support it. The other param should work on all platforms, but works differently. It sets the title of the input file instead the title of the VLC window.

Thanks for reporting
