### ISSUE TITLE
Dragging and dropping an icon into a text field breaks the app

### ISSUE THREAD

**Issue by pwestrich** [streamlink/streamlink-twitch-gui#359]
----

### Description

I dragged the VLC binary to the text field for the media player's location.and it looked like it's tried to open it as an index webpage; I can navigate it as much as I want. The app is however soft locked as you cannot return to normal function.
...

### Expected / Actual behavior

(optimal) Placed the location of the item into the text box.
(okay) Do nothing.
...

### Reproduction steps

1. Drag any icon on to the window.

### Environment details (operating system, etc.)

macOS 10.12.1, Streamlink GUI 1.0.0
...

### Comments, logs, screenshots, etc.
<img width="717" alt="oops" src="https://cloud.githubusercontent.com/assets/7771375/21024988/51ca03d0-bd4c-11e6-9acd-769ad1ea83bb.png">

...

**Comment by bastimeyer** [comment]
Thanks for reporting
