### ISSUE TITLE
Streamlink Misconfiguration

### ISSUE THREAD

**Issue by amberkun** [streamlink/streamlink-twitch-gui#368]
![streamlink error](https://cloud.githubusercontent.com/assets/11237708/21170102/1c63cf72-c1fd-11e6-88c0-ba759389706e.jpg)

**"Error: Streamlink Misconfiguration"
Could not find Python executable**

i was using livestreamer v0.15.2 before updating and it was working fine

Im using windows 7 32bit
installed it with "streamlink-twitch-gui-v1.0.0-win32.zip"
settings are default i think. i never changed anything

thanks

**Comment by bastimeyer** [comment]
> Please check your settings and/or (re)install Streamlink

You should do exactly this. This is not a bug...

> i was using livestreamer v0.15.2

No, you were using **Livestreamer Twitch GUI** and **Livestreamer**. These are two different programs.

**Streamlink Twitch GUI** now uses **Streamlink** by default, as the name already suggests and as you can read in the changelog:
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CHANGELOG.md#v100-2016-12-04

If you've installed Streamlink by using the Windows installer and the GUI is unable to find it, then the registration of Streamlink's install dir in the system's `PATH` environment variable has failed (you can try the latest Streamlink nightly release in this case) and you've installed it to a custom dir.
https://github.com/streamlink/streamlink-twitch-gui/wiki

I have already given an answer to the same question a couple of days ago
https://github.com/streamlink/streamlink-twitch-gui/issues/363#issuecomment-266213948
Please search for already closed issues next time. Thanks.

**Comment by amberkun** [comment]
oh sorry
its fixed now thanks

**Comment by bastimeyer** [comment]
No worries...
Btw, I have updated the wiki today, so if there's anything unclear, just ask.
And there's a new release: `1.0.1`
