### ISSUE TITLE
Error: Streamlink Misconfiguration

### ISSUE THREAD

**Issue by TrollOutOfControl** [streamlink/streamlink-twitch-gui#370]
So i have [this problem](http://s1.bild.me/bilder/240416/6470691sdf.PNG)
also these are my [settings](http://s1.bild.me/bilder/240416/1137507ssd.PNG)
i haven't touched anything, i've downloaded the original, master and this win10 64 installation, i've reinstalled it several times, and i can't find those files. I've also installed python 3.5 
can somebody help me?

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui#description
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
