### ISSUE TITLE
Option to disable hw acceleration & gpu process

### ISSUE THREAD

**Issue by ahmedtds** [streamlink/streamlink-twitch-gui#372]
Hi

I noticed that after version 1.0 this app started to use gpu. I want to disable that, can you please add an option to be able to disable it?

I mostly use this app in a very old laptop because watching twitch via browser is practically impossible and this app does a great job. But after 1.0 it actually started to affect performance when I watch 2-3 streams because also streamlink twitch gui uses gpu.

Versions before 1.0 doesn't have this issue because they don't touch gpu.

**Comment by bastimeyer** [comment]
You can use all available Chromium parameters when starting NW.js applications... Also the ones for disabling GPU acceleration. See here or google for the needed parameters:
http://docs.nwjs.io/en/latest/References/Command%20Line%20Options/

> this app started to use gpu

Previous releases (which used Chromium 41 and below) were already making use of GPU acceleration

**Comment by ahmedtds** [comment]
Thank you for that link I will try it.

> Previous releases (which used Chromium 41 and below) were already making use of GPU acceleration

I don't think it was enabled in previous releases. I just downloaded 0.16 version and Process Explorer shows that none of the livestreamer-twitch-gui processes touches gpu.

This is all of the 0.16 processes: http://i.imgur.com/DBLeoKm.png
This is a process of 1.0 and 1.0.1: http://i.imgur.com/StEjy7k.png

**Comment by bastimeyer** [comment]
Chromium automatically decides if GPU accelerated compositing and rasterization is being used. This depends on your system and configuration. As you can see, there are only parameters for disabling all this. This can't be *enabled*.
