### ISSUE TITLE
Error: Couldn't launch the stream (python error)

### ISSUE THREAD

**Issue by appleiiguy** [streamlink/streamlink-twitch-gui#378]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

When attempting to open a stream i get the following error:
Error: Couldn't launch the stream
Traceback (most recent call last):
File "/usr/local/bin/streamlink", line 5, in <module>
from pkg_resources import load_entry_point
File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/pkg_resources/__init__.py", line 3095, in <module>

...

### Expected / Actual behavior

Open the stream in VLC

### Reproduction steps

1. Launch Streamlink Twitch GUI
2. Launch Stream
3. ...

### Environment details (operating system, etc.)
MacOS Sierra 12.2
streamlink 0.2.0

### Comments, logs, screenshots, etc.

...screenshot_92

**Comment by bastimeyer** [comment]
> Streamlink is working correctly on my system without using the Twitch GUI.
> I tried solving my issue by reading the project's wiki first.
> When attempting to open a stream i get the following error:

Are you sure that Streamlink is working correctly? You are getting a python error message...

If you are using multiple python versions on the same machine, you need to specify the one that streamlink requires in the GUI's settings menu:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#selecting-a-streaming-provider

**Comment by appleiiguy** [comment]
Yes streamlink from command line is working correctly.

$ which python
/Library/Frameworks/Python.framework/Versions/2.7/bin/python

$ streamlink twitch.tv/EJ_SA source
[cli][info] Found matching plugin twitch for URL twitch.tv/EJ_SA
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC

**Comment by bastimeyer** [comment]
> /usr/local/bin/streamlink

How did you install streamlink?
The python script should be located here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/src/config/streamprovider.json#L53 

The one that's found in `$PATH` doesn't seem to be compatible with the python version which is being resolved by looking into `$PATH`.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/src/app/services/StreamingService.js#L299

Which shebang is it using?
`cat $(which streamlink) | head -n 1`

Anyway, you need to select the correct streamlink script file.

**Comment by appleiiguy** [comment]
I used easy_install -U streamlink to install.

$ cat $(which streamlink) | head -n 1
#!/usr/local/opt/python/bin/python2.7

**Comment by bastimeyer** [comment]
Well, there you have it... Either set the python path in the GUI settings to this path or install streamlink via pip (which will install it to the expected dir) and then set the correct streamlink script path.

I didn't know that easy_install was doing this... I'm not sure if adding this path to the list will fix this, though.

**Comment by appleiiguy** [comment]
now its says connecting but the vlc window immediately opens then closes

**Comment by bastimeyer** [comment]
Which version of the Twitch GUI are you using? You didn't include this in your post...

There was a bugfix regarding the VLC player preset in `1.0.1`:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/CHANGELOG.md#v101-2016-12-14

You can always try running streamlink from the shell, btw:
`/path/to/python /path/to/streamlink -p /path/to/player STREAM best`

**Comment by appleiiguy** [comment]
using version 1.0.1
streamlink from cli works fine without any paths.
entering "streamlink twitch.tv/EJ_SA source" in terminal works just fine

**Comment by bastimeyer** [comment]
> streamlink from cli works fine without any paths.

Because it's using a different python executable (set in the shebang)...
The GUI is using the `which python` one.

As I've already told you and as the wiki says, streamlink needs to be compatible with the python executable you're using.

The command I've posted above is the explicit way of starting streamlink, which is exactly what the GUI does (except the reduced parameter list).

**Comment by bastimeyer** [comment]
85906723c3a9762ca21c39e032760c59a73dcca3 has added support for parsing of the pythonscript shebang, which should select the correct python executable if none has been set in the settings menu.
