### ISSUE TITLE
Small color change for dark theme

### ISSUE THREAD

**Issue by ivan200** [streamlink/streamlink-twitch-gui#379]
I use dark theme of the application, and every time I look in the left menu, its so hard to see this purple text on dark background.

And this is from [twitch brand assets](https://www.twitch.tv/p/brand-assets):

> Do use black as the default on light backgrounds, and **white on dark backgrounds**.

Please, can you change it for example like this?:
![twitext](https://cloud.githubusercontent.com/assets/15914922/21336267/4e4afc64-c675-11e6-82ec-8f9071628cc5.png)

**Comment by bastimeyer** [comment]
Sorry for the late answer, I clicked the notification away on my phone and forgot about it. 😸 

Regarding your question:
We'll see what can be done with a different theming system based on css variables. Stylesheets can then be dynamically customized during runtime, which means that everyone can customize stuff the way they want. I'm not sure when I'll be able to implement this, though. I really would like implementing css modules first, but a proper implementation is being blocked by EmberJS (routable components to be precise) and a new EmberJS module resolver based on the new EmberJS project folder structure (this is not an Ember-CLI project).

You can always build the application on your own and add new themes or customize the already included ones:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/src/styles/themes/dark.less#L104-L106

**Comment by bastimeyer** [comment]
Closing this thread for #397 (there's a more detailed answer).
I'm not going to change the dark theme now...
