### ISSUE TITLE
Mouse forward and back buttons

### ISSUE THREAD

**Issue by Baum-r** [streamlink/streamlink-twitch-gui#382]
### Checklist

- [x] This is a bug report. (maybe?)
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

The Forward and Back buttons on the mouse do nothing in the app

### Expected / Actual behavior

**Expected** - Back button to return the the previous page and the Forward button going to the next page if you've one back one

**Actual behavior** - The buttons do nothing

### Environment details (operating system, etc.)

Win10

### Comments, logs, screenshots, etc.

I did notice that Alt+Arrow keys work

**Comment by bastimeyer** [comment]
Not possible, see
https://github.com/streamlink/streamlink-twitch-gui/issues/242#issuecomment-214509528
https://github.com/streamlink/streamlink-twitch-gui/issues/180#issuecomment-167425713
https://github.com/streamlink/streamlink-twitch-gui/issues/85#issuecomment-98985832

> I did notice that Alt+Arrow keys work

https://github.com/streamlink/streamlink-twitch-gui/blob/v1.0.1/src/app/components/ApplicationComponent.js#L79-L85
