### ISSUE TITLE
Export/import configuration

### ISSUE THREAD

**Issue by kitce** [streamlink/streamlink-twitch-gui#387]
I am switching from Livestreamer Twitch GUI (LTGUI) to Streamlink Twitch GUI (STGUI)

Is there a way I could export the configuration from LTGUI and import to STGUI?

**Comment by bastimeyer** [comment]
See the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Data-migration

**Comment by kitce** [comment]
That was quick! Thanks for the guideline.
