### ISSUE TITLE
Invalid Streamlink Version Despite Correct Version Being Installed

### ISSUE THREAD

**Issue by mam8cc** [streamlink/streamlink-twitch-gui#388]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
After moving over from Livestreamer GUI, I've not been able to get the GUI to work with Streamlink.  I have 0.2.0 of Streamlink installed and have paths set to my python install as well as the livestreamer binary.  
...

### Expected / Actual behavior
Expect that I can launch a stream via the GUI.

Recieve an error:

Error: Invalid Streamlink version
Your version v0.1.0 doesn't match the min. requirements (v0.2.0).

### Reproduction steps

1. Launch Streamlink GUI and configure paths to python and streamlink
2. Open stream
3. See error

### Environment details (operating system, etc.)
Installed the GUI from the releases: https://github.com/streamlink/streamlink-twitch-gui/releases/download/v1.1.1/streamlink-twitch-gui-v1.1.1-macOS.tar.gz
macOS Sierra 10.12.2
python 3.4.4
streamlink 0.2.0

```
# mikemcclannahan @ beetlestation in ~ [11:22:01]
$ which python3
/usr/local/bin/python3

# mikemcclannahan @ beetlestation in ~ [11:22:05]
$ python3 --version
Python 3.4.4

# mikemcclannahan @ beetlestation in ~ [11:22:08]
$ which streamlink
/usr/local/bin/streamlink

# mikemcclannahan @ beetlestation in ~ [11:22:15] C:2
$ streamlink --version
streamlink 0.2.0

```

### Comments, logs, screenshots, etc.
![screen shot 2017-01-03 at 10 51 00 am](https://cloud.githubusercontent.com/assets/1774337/21616330/a4f942aa-d1a6-11e6-89c2-a6159e5d6b0a.png)
![screen shot 2017-01-03 at 10 51 29 am](https://cloud.githubusercontent.com/assets/1774337/21616335/a899422a-d1a6-11e6-8db0-0fdc7110e783.png)
![screen shot 2017-01-03 at 11 21 38 am](https://cloud.githubusercontent.com/assets/1774337/21616372/d493e57e-d1a6-11e6-8749-e06274ffebb8.png)

**Comment by Robby-** [comment]
After updating to version 1.1.1 this problem is now occurring for me as well. With version 1.0.1 this issue didn't occur. Probably related to this: streamlink/streamlink#346.

**Comment by bastimeyer** [comment]
@mam8cc 
What's the output of running
```bash
/usr/local/bin/python3 /usr/local/bin/streamlink --version
```
and
```
cat /usr/local/bin/streamlink | head -n 1
```

Please also try removing the explicit python path from the settings as it shouldn't be necessary anymore since `v1.1.x`.


@Robby- 
This was an issue related to the Windows installer of 0.2.0. I knew that this would affect some users, but I needed to publish a new release because of a critical bug of the installer of the Twitch GUI and I didn't want to revert the commit of the streamlink dependency increment. Re-downloading the Streamlink installer fixes the issue, as you've already figured out 😃

**Comment by mam8cc** [comment]
@bastimeyer If I remove the explicit path setting and attempt to launch a stream I get:

```
Traceback (most recent call last):
File "/usr/local/bin/streamlink", line 7, in <module>
from streamlink_cli.main import main
ImportError: No module named streamlink_cli.main
```

And the requested output:
```
# mikemcclannahan @ beetlestation in ~ [21:16:57]
$ /usr/local/bin/python3 /usr/local/bin/streamlink --version
streamlink 0.1.0

# mikemcclannahan @ beetlestation in ~ [21:17:01]
$ cat /usr/local/bin/streamlink | head -n 1
#!/usr/local/opt/python3/bin/python3.5
```

**Comment by bastimeyer** [comment]
You are mixing different python versions (and different streamlink versions).

The first command is the one the GUI invokes when setting the explicit python path you have posted. As you can see, it prints out `0.1.0`. The third screenshot you uploaded shows that calling "streamlink" works fine. When not setting an explicit python path, the GUI uses the python executable set in the streamlink-script's shebang (`/usr/local/opt/python3/bin/python3.5`), which is the same as calling `streamlink` from the shell. I don't know your whole setup, but I'm surprised that this throws a python error when clearing the python path in the GUI.

Maybe you should clear all existing streamlink installations and start off fresh. I don't have a better answer right now 😞

**Comment by mam8cc** [comment]
I've uninstalled streamlink from every python distro I have installed.  I've grepped for it across the system and cannot find it.  However this is clearly a local issue.  Thanks for looking.

**Comment by mam8cc** [comment]
@bastimeyer If others encounter this issue, the only thing I've had success with is installing streamlink inside a virtualenv and pointing the GUI to it.

However, now I am seeing the below issue:

```
Found matching plugin twitch for URL twitch.tv/summit1g
Attempting to authenticate using OAuth token
Successfully logged in as [twich user name]
Available streams: audio, mobile (worst), low, medium, high, source (best)
Starting player: /Applications/VLC.app/Contents/MacOS/VLC
error: Failed to start player: /Applications/VLC.app/Contents/MacOS/VLC (Process exited prematurely)
```

As I've shown above I can start livestreamer for the command line.  I can open a new issue if you'd prefer.

**Comment by bastimeyer** [comment]
Can you please add the [`--verbose-player`](https://streamlink.github.io/cli.html#cmdoption-verbose-player) custom streamlink parameter in the GUI, so you can see the VLC output? Maybe also [`--loglevel DEBUG`](https://streamlink.github.io/cli.html#cmdoption-l)

**Comment by mam8cc** [comment]
```
vlc: unknown option or missing mandatory argument `--qt-minimal-view'
Try `vlc --help' for more information.
error: Failed to start player: /Applications/VLC.app/Contents/MacOS/VLC (Process exited prematurely)
```

**Comment by bastimeyer** [comment]
> unknown option or missing mandatory argument `--qt-minimal-view'

https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/config/players.json#L57-L66
Looks like VLC doesn't support this on MacOS.

**Comment by bastimeyer** [comment]
Closing this now, since the original issue has been a client issue and the other one was fixed.

Please deselect the "Minimal player layout" option in the settings menu to be able to launch streams on MacOS with VLC.

**Comment by mam8cc** [comment]
@bastimeyer I can open a new issue if you'd like but after deselecting the "Minimal player layout" option as you recommended above, I now see the below error when launching a stream.

```
Error:  Couldn't Launch Stream
[0000000100218468] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
[000000010030e038] http access error: failed to read answer
[000000010030e038] access_mms access error: cannot connect to 127.0.0.1:50614
[0000000105301278] filesystem access error: cannot open file /Applications/Streamlink Twitch GUI.app/Contents/Resources/app.nw/http://127.0.0.1:50614/ (No such file or directory)
2017-01-07 20:55:55.103 VLC[17222:43282244] Can't find app with identifier com.spotify.client
[000000010030dc38] core input error: open of `file:///Applications/Streamlink%20Twitch%20GUI.app/Contents/Resources/app.nw/http%3A//127.0.0.1%3A50614/' failed
[00000001002666a8] core playlist: end of playlist, exiting
```

**Comment by bastimeyer** [comment]
> file:///Applications/Streamlink%20Twitch%20GUI.app/Contents/Resources/app.nw/http%3A//127.0.0.1%3A50614/

This looks like a VLC bug. Why is it treating a http URL as a local file name?

What happens when you run this?
```bash
streamlink -p /path/to/vlc --player-passthrough http STREAM best
```

Btw, switching to rtmp fixes this, as reported in the linked thread above.

**Comment by mam8cc** [comment]
Here is the output you requested.  Everything works fine and the stream starts.

```
$ streamlink -p /Applications/VLC.app/Contents/MacOS/VLC --player-passthrough http https://www.twitch.tv/pinballjoe BEST
[cli][info] Found matching plugin twitch for URL https://www.twitch.tv/pinballjoe
[cli][info] Available streams: audio, mobile (worst), low, medium, high, source (best)
[cli][info] Opening stream: source (hls)
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
```

Switching to `rtmp` did in fact launch a stream.  You can consider this resolved.
