### ISSUE TITLE
Adding misc streams to GUI

### ISSUE THREAD

**Issue by Glasse** [streamlink/streamlink-twitch-gui#389]
**This is a feature request**

I saw the answer for the Hitbox.tv question and I think this may be a bit different so i figured i'd ask.

I was wondering if it would be possible to add "shortcuts" to specific streams on other website to the GUI.

As an example, I could add a stream from openrec.tv (which I have a .bat for on my desktop) to the twitch GUI. It could show up in the "live streams" section when live.

I don't even care if it doesn't show the game they are playing, their viewers or whatever, just an indicator that they are live. This is a GUI for twitch so I don't expect full functionality for every website ever, but a "live" indicator for whatever website is supported by streamlink would be great.

Even without a live indicator, I have so many different files for different streams on other websites :(

Thank you for your amazing work btw, I've been using the UI since the very beginning. Love it.

**Comment by bastimeyer** [comment]
Sorry, but this is a Streamlink GUI for Twitch.tv. What you are requesting doesn't fit here. There are other simpler Livestreamer/Streamlink GUI projects that are not platform specific.
Being able to see whether streams/channels are online on other platforms means either having an API of this platform and access to it, or running streamlink for each URL and then seeing if a stream resource could be found, which is of course much slower and also costs much more resources.
The second method can easily be written in a simple bash script...
