### ISSUE TITLE
Unable to download NWjs during compliation on Solus

### ISSUE THREAD

**Issue by joebonrichie** [streamlink/streamlink-twitch-gui#392]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
During grunt release NWjs fails to download during runtest task, I've tried grunt build and other combinations to see if that fixes it. I've also tried manually downloading the correct nwjs-sdk and un-tarring it in /build/cache/0.19.0-sdk but that does not work.

```
$ grunt release
Running "release" task

Running "jshint:tasks" (jshint) task
>> 25 files lint free.

Running "jshint:app" (jshint) task
>> 269 files lint free.

Running "jshint:test" (jshint) task
>> 33 files lint free.

Running "clean:tmp_test" (clean) task
>> 15 paths cleaned.

Running "webpack:test" (webpack) task
Version: webpack 1.13.3     
Time: 7039ms
                 Asset       Size  Chunks             Chunk Names
               main.js     192 kB       0  [emitted]  main
      img/icon-256.png    4.11 kB          [emitted]  
    img/icon-16@2x.png    1.15 kB          [emitted]  
    img/icon-16@3x.png    1.51 kB          [emitted]  
   img/icon-osx-18.png  313 bytes          [emitted]  
img/icon-osx-18@2x.png  406 bytes          [emitted]  
img/icon-osx-18@3x.png  478 bytes          [emitted]  
       img/icon-16.png  723 bytes          [emitted]  
       vendor.bower.js    3.59 MB       1  [emitted]  vendor.bower
         vendor.npm.js    2.03 kB       2  [emitted]  vendor.npm
          templates.js    38.6 kB       3  [emitted]  templates
            vendor.css    7.46 kB       1  [emitted]  vendor.bower
          package.json  298 bytes          [emitted]  
            index.html  434 bytes          [emitted]  

Running "runtest" task
Using v0.19.0 (sdk)
Create cache folder in /home/ninya/streamlink-twitch-gui/build/cache/0.19.0-sdk
Downloading: http://dl.nwjs.io/v0.19.0/nwjs-sdk-v0.19.0-linux-x64.tar.gz
undefined
Fatal error: Unable to download NWjs.
```

### Expected / Actual behavior
NWjs downloads, app compiles without issue

### Reproduction steps

1. npm install -g bower grunt-cli
2. npm install
3. grunt release

### Environment details (operating system, etc.)
```
npm version
{ 'streamlink-twitch-gui': '1.1.1',
  npm: '3.10.10',
  ares: '1.10.1-DEV',
  http_parser: '2.7.0',
  icu: '57.1',
  modules: '48',
  node: '6.9.3',
  openssl: '1.0.2j',
  uv: '1.9.1',
  v8: '5.1.281.89',
  zlib: '1.2.8' }
$ lsb_release -a
LSB Version:	1.4
Distributor ID:	Solus
Description:	Solus
Release:	2017.01.01.0
Codename:	shannon
$ uname -romi
4.8.15 x86_64 unknown GNU/Linux
```

### Comments, logs, screenshots, etc.
I'm trying to package this application for Solus

**Comment by bastimeyer** [comment]
This is an issue of the nw-builder. This has been reported a couple of days ago, but the project seems to be inactive once again. It's a disaster tbh.

I have created a PR on the nw-builder repo a couple of months ago that forces https downloads, but this hasn't been merged yet. The NW.js devs are now redirecting unencrypted http requests, which causes this issue.

I have pushed a fix to master here (e5f98d3c4ffbad8cc75bf8ddfed67affd1b1aa5b) that uses my patched nw-builder version. Should be working again now...


> I'm trying to package this application for Solus

Cool. Is this a package in one of the official repos or how does packaging on Solus work? Could you give me a link please?

**Comment by joebonrichie** [comment]
Ah great thanks that fixed it, grunt release now completes without error.

streamlink-twitch-gui has been accepted for package inclusion on the dev tracker in solus
https://dev.solus-project.com/T1410
Since I use stg a lot i'm packaging it myself and will provide a patch on the tracker

The packages have to be build from source from a stable release

As for building on solus you create a package.yml which is very similar to a PKGBUILD, you build the pkg with solbuild build which creates a chroot enviroment to build the pkg in. You end up with an .eopkg that you can install using eopkg install pkg.eopkg
More info here: https://wiki.solus-project.com/Packaging

Here's the package.yml so far if you're interested
```
name       : streamlink-twitch-gui
version    : 1.1.1
release    : 1
source     :
    #- https://github.com/streamlink/streamlink-twitch-gui/archive/v1.1.1.tar.gz : aa60214371056a31a7bb35bc590ae33c39e72006986abb19771092e3ac861f01
    - https://github.com/streamlink/streamlink-twitch-gui/archive/master.zip : 4e1873dcc9da099efaf32b17544a5d7d72de32c6abc47274abc2db0ad36ab2a8
license    : MIT
component  : network.web
summary    : A multi platform Twitch.tv browser for Streamlink
description: |
    A multi platform Twitch.tv browser for Streamlink
networking : yes
builddeps  :
    - nodejs-devel
    - git
build      : |
    # Since grunt-cli and bower will not be installed globally (-g) export them to path
    export PATH=$workdir/node_modules/.bin:$PATH
    npm install grunt-cli bower
    npm install
    # Normally bower install gets triggered by npm install but we need to pass --allow-root to it
    bower install --allow-root
    grunt release
install    : |
    # cp -R $workdir/build/releases $installroot/opt/
    # add-menu-item.sh
    # disable update checking
    %make_install
```

Thanks for your help!

**Comment by bastimeyer** [comment]
> Here's the package.yml so far if you're interested

I don't think that using the archives provided by github can be used here. The repo needs to be cloned, because during the build process the custom webpack "metadata" loader is executing [`git describe --tags`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.1.1/src/web_loaders/metadata-loader.js#L63).
Also, the hash of the archive of the master branch will change as soon as a new commit gets pushed to that branch, which will break the package build.

For the remaining stuff in the install section, see the AUR package if you like:
https://aur.archlinux.org/cgit/aur.git/tree/?h=streamlink-twitch-gui

**Comment by joebonrichie** [comment]
You're right, if I compile from an archive the compile fails at webpack:prod

```
ERROR in ./src/web_modules/metadata.js
Module build failed: Error: null
  at ChildProcess.onExit (/home/ninya/streamlink-twitch-gui-e5f98d3c4ffbad8cc75bf8ddfed67affd1b1aa5b/src/web_loaders/metadata-loader.js:39:14)
  at emitTwo (events.js:106:13)
  at ChildProcess.emit (events.js:191:7)
  at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)

 @ ./src/app/controllers/AboutController.js 11:16-35
Warning: Task "webpack:prod" failed. Use --force to continue.
```

I don't think any packages are built using git clone in Solus atm, or even if its possible with the current package manager. There is a third party repo but that's reserved for proprietary software mostly.

**Comment by bastimeyer** [comment]
Just a quick question: Why don't you simply use the archives with the prebuilt application from the github releases, just like the main AUR package?

I mean I can change the webpack loader so that it can also be built when not using the git repo, but I don't know if I want to. Please don't think that I'm greedy here, but custom builds also don't include donation metadata. And I don't think that it's a good idea to use unfinished work from the master branch (which is the dev branch) in an official package.

**Comment by bastimeyer** [comment]
Closing this, since the original issue has been solved pretty much immediately.
If there are other issues regarding the packaging of the application for Solus, please open another one.
