### ISSUE TITLE
Error: Coudn't launch the stream

### ISSUE THREAD

**Issue by Sesacis** [streamlink/streamlink-twitch-gui#394]
I get this error and i dont know how to fix it.
I'm making this issue because i didnt find any fix for it.
![issue](https://cloud.githubusercontent.com/assets/25112658/21950978/1c07a7a0-da09-11e6-8e4a-0a8e9ca2fca2.png)

**Comment by bastimeyer** [comment]
You should follow the installation instructions in the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
> Please note that the Visual C++ Redistributable package needs to be installed on systems using a Windows version prior to 10.

Btw, when using the issue search function and searching for this specific error message (or even googling it), you will find this thread: #347
