### ISSUE TITLE
streamlink opens 4 proccess in parallel ?

### ISSUE THREAD

**Issue by ooak** [streamlink/streamlink-twitch-gui#398]
when using streamlink it opens 4 different processes. is it normal ?

I attached a picture:
![default](https://cloud.githubusercontent.com/assets/24572584/22183362/0c598176-e0c5-11e6-8a0e-702dd3d882fa.jpg)

**Comment by bastimeyer** [comment]
As you can read in the description of the readme file, __Streamlink *Twitch GUI*__ is a NW.js application.
NW.js is a combination of Node.js and Chromium. Chromium uses a multi process rendering architecture (AFAIK, Firefox has finally done the same in one of the latest releases).

https://nwjs.io/
https://www.chromium.org/developers/design-documents/multi-process-architecture

**Comment by ooak** [comment]
ok thank you.
