### ISSUE TITLE
[Request] Basic support for keybindings

### ISSUE THREAD

**Issue by Hund** [streamlink/streamlink-twitch-gui#399]
Since livestreamer-curses has been dead for the longest time now and finally starting to fall apart, I had to replace it with something else. So, here I am. I really like this program, it's probably as good as a GUI can get. The only problems is that I prefer CLIs/TUIs.

Anyway, would it be possible to implement some kind of basic support for keybindings? Perhaps something like that resembles the Vi-style, like `f` for hints, `/` to search et cetera? Or at least something, so you don't have to use the mouse for the most basic things like open a stream and perhaps switching between featured streams, games et cetera.

Dunno if it's crazy talk or not, but at least I would appreciate it. :)

**Comment by bastimeyer** [comment]
I'm okay with adding basic hotkeys, eg. for focusing the search bar, visiting routes of the main menu, or modal dialog hotkeys. Adding navigation hotkeys is something I don't want to implement, as this would require some more additional work (focusable/selectable list items), which can become quite complex, especially when different layouts are being implemented in the future.

If you want to use an application that has been built entirely with keyboard usage in mind, then you should look for something else or try to fix the one you were talking about.

**Comment by Hund** [comment]
Sounds good. :) 

I was only hoping for some basics keybinding for some basic things. I know it's program based around a GUI and they're built around the mouse.

livestreamer-curses works after I replaced the backend to streamlink. But I don't know how to code, so I have no idea how to make it to only show online channels. Right now it shows a channel as online, even though they're just hosting someone. :/
