### ISSUE TITLE
VLC Process Exits prematurely

### ISSUE THREAD

**Issue by CritKlepka** [streamlink/streamlink-twitch-gui#400]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description
When I attempt to launch any stream, I get the following error:

> error: Failed to start player: /Applications/VLC.app/Contents/MacOS/VLC (Process exited prematurely)

### Environment details (operating system, etc.)
macOS Sierra
streamlink installed (currently using a virtual environment method in order not to install as root, as that has been a problem for other users but it apparently is not mine)

<img width="959" alt="screen shot 2017-01-25 at 11 48 52 am" src="https://cloud.githubusercontent.com/assets/25349922/22300187/ab893b0c-e2f4-11e6-993f-10cac944a310.png">

**Comment by bastimeyer** [comment]
This seems to be the same issue has this one:
https://github.com/streamlink/streamlink-twitch-gui/issues/388#issuecomment-270699184

VLC on MacOS doesn't support the `--qt-minimal-view` parameter, which gets set by Streamlink Twitch GUI when the according checkbox is set in the player preset list. You need to disable it. This checkbox has already been removed for MacOS (see the linked thread), but no newer release has been published yet that contains that fix.

**Comment by CritKlepka** [comment]
Alright thanks. Went ahead and did that, no error, but SOMETHING flashes and it just goes back to the followed streams directory (what I currently have open). I see a glimpse of red so maybe another error but VLC is never launched. If it attempt to do it with VLC already open, same thing.

**Comment by bastimeyer** [comment]
Which VLC version are you using?
See below in the linked thread, you need to select the RTMP player-passthrough (requires advanced settings to be enabled).

**Comment by CritKlepka** [comment]
That fixed it for me. Appreciate it! 

One odd thing to note, if I opened VLC from applications, it was open as one icon on the dock. If I ran Streamlink from the terminal, it opened another VLC app (not another window, Command-Q'ing closed the second window and left the first open). Dunno if that helps lead to fixing the issuing in the future...

**Comment by bastimeyer** [comment]
Can you please tell mich version of VLC you're using? I'm not seeing this kind of VLC behavior in my MacOS VMs....

**Comment by CritKlepka** [comment]
Version 2.2.4 Weatherwax (Intel 64bit)

**Comment by CritKlepka** [comment]
If I stop the VLC playback with the stop button on VLC, then close the stream in Twitch GUI, that VLC stays open. And attempting to open the same stream does nothing, and a different stream starts a new instance of VLC. Not game breaking, just there.
