### ISSUE TITLE
The process exited with code 2

### ISSUE THREAD

**Issue by babyrim** [streamlink/streamlink-twitch-gui#403]
Hi~

I've been getting an error message when trying to open stream with the GUI I haven't been able to find anyone with a similar issue/error message.

http://puu.sh/tDpSs/23c908b1cd.jpg

Is there anything I forgot to change in the settings?
Any help would be appreciated! Thanks~

**Comment by bastimeyer** [comment]
You have to make sure that Streamlink itself if working correctly on your system. This is not a Streamlink Twitch GUI issue you're having...

The Windows installer of the Streamlink `0.3.0` release has a couple of issues. I think this is why you are seeing this error message. It has already been fixed here: streamlink/streamlink#483

Please try using the latest Streamlink nightly installer (see the website) or apply [these changes](https://github.com/streamlink/streamlink/pull/483/files) to your `streamlinkrc` config file.

**Comment by bastimeyer** [comment]
Closing this, since it's a streamlink related issue that has been resolved since a couple of days (streamlink `0.3.1` has been published).
