### ISSUE TITLE
"Error: Couldn't launch the stream"

### ISSUE THREAD

**Issue by JotaPe** [streamlink/streamlink-twitch-gui#405]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Try to launch a stream and get a "Error: Couldn't launch the stream"

### Expected / Actual behavior

Play the stream with all the settings

### Reproduction steps

1. Open Streamlink Twitch Gui
2. Click to play a stream
3. get a error

### Environment details (operating system, etc.)

Linux Mint Cinnamon 18.1 64Bits Kernel 4.4
GTX 970 with propietary drivers
I installed the Streamlink with PIP on sudo and cant install without sudo

### Comments, logs, screenshots, etc.

Log After Error
Traceback (most recent call last):
File "/usr/local/bin/streamlink", line 6, in <module>
from pkg_resources import load_entry_point
File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2927, in <module>

**Comment by bastimeyer** [comment]
> Streamlink is working correctly on my system without using the Twitch GUI.

> Traceback (most recent call last):
> File "/usr/local/bin/streamlink", line 6, in 
> from pkg_resources import load_entry_point
> File "/usr/lib/python2.7/dist-packages/pkg_resources/init.py", line 2927, in

Streamlink seems to be broken on your system. You have to fix it in order to launch stream from the GUI.
