### ISSUE TITLE
Can you watch vods?

### ISSUE THREAD

**Issue by DonattR** [streamlink/streamlink-twitch-gui#413]
Can you watch vods ? if yes how ! im new so i dont know anything! thanks.

**Comment by bytegeist** [comment]
Yeah, this is the only major feature I'm missing as well. On android there's a Twitch client called "Ace" that let's you open vods with your external media player that works very well, so there seems to be a way to grab those links to share.

**Comment by bastimeyer** [comment]
Please see https://github.com/streamlink/streamlink-twitch-gui/issues/81#issuecomment-265733864 and use the search function next time before opening new issues. Thanks.

**Comment by adrenochrome25** [comment]
other thread closed, i dont get why refusing comments about this restriction : i'm a new twitch user and i watch a lot of video/VOD(in fact record of streams for which email notifications comes much too late once broadcast is already finished) on it  : on my favortite streamers profile, tab videos)
i wanted a less cpu eating application and i found streamlink-twitch-gui, after fighting with the installation i discover that it is unable to list and display the twitch video i want to watch the most

**Comment by bastimeyer** [comment]
There is everything said in the other thread, so there is no reason further ask or even to beg. The Twitch GUI depends on a proper implementation of Streamlink, which doesn't exist yet, and watching VODs with a bad user experience is not going to be added here.

**Comment by mystixa** [comment]
Definitely should add VOD support.. even if its incomplete. Its a big part of the Twitch experience.
