### ISSUE TITLE
Stream queue. feature request

### ISSUE THREAD

**Issue by pascaldulieu** [streamlink/streamlink-twitch-gui#417]
It would be nice to be able to add another stream to the playlist (VLC for me) so when the first stream ends it try's to start the next stream and if it is offline it try's the next one if there is another on the list and keeps going until it runs out of streams.

It could be a thing built into the application as a new option on the side panel where we can queue up people and just hit play and it will start or in the right click menu so we can just click add to queue.

Thanks

**Comment by pokeguru87** [comment]
I wouldn't mind a mode where I could setup a ordered list of all my followed streams and it would start up the first stream on the list that is streaming when one ends, and maybe a mode to allow specific streams or just ones higher on the list to override the current one. For example, I pretty much always watch Bikeman over anyone else, even if I have to stop in the middle of the other persons stream.

**Comment by bastimeyer** [comment]
A queuing feature has already been requested in #241.

Implementing a queuing system was not possible until recently, but I'm still not a fan of automatism in this regard, as it can lead to some issues. It's also quite difficult creating a good queuing system that's able to deal with multiple streams that are being watched at the same time (multiple parellel queues). Right now, my focus is on other things that need to be done first, so a queuing system may not be added any time soon.

I'm going to close this thread. If you have any more comments, please use #241.
