### ISSUE TITLE
Auto open. feature request

### ISSUE THREAD

**Issue by pascaldulieu** [streamlink/streamlink-twitch-gui#418]
When a set streamer comes online it automatically opens the live stream when the come online, could this be added in the channel settings under chat so it automatically opens the stream and chat when they come online if the option is checked.

Thanks

**Comment by bastimeyer** [comment]
As I've already said in the other thread you've opened, I'm not a fan of automatism when it comes to launching streams, which basically means automatically starting other applications.

If you want to start Streamlink/Livestreamer as soon as one of your favorite channels starts broadcasting, you should either use a different application or write a little shell script. IIRC, there was a thread on the streamlink issue tracker a couple of months ago where somebody asked this same question.

**Comment by invalidhippo** [comment]
For anyone interested, I have written an application that offers such functionality.
