### ISSUE TITLE
Filters for games, channels, and content

### ISSUE THREAD

**Issue by matt2hews** [streamlink/streamlink-twitch-gui#421]
Games, channels, or content attribute could have a hide filter that works in the same fashion as the language filter.

**Comment by bastimeyer** [comment]
This can't be done without having a filter parameter available in Twitch's API.

#193 
#199 
#219 
#320 
#364 

https://github.com/streamlink/streamlink-twitch-gui/issues/151#issuecomment-183581175

https://github.com/streamlink/streamlink-twitch-gui/issues?utf8=%E2%9C%93&q=filter

**Comment by matt2hews** [comment]
Thanks for the feedback.
