### ISSUE TITLE
[Question] Should the default behavior close the media player after the stream has ended?

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink-twitch-gui#426]
Since there is an option to leave the media player window open once the stream has ended, I assume the default behavior should be to close it. 

However, I've never seen that happen.

**Comment by bastimeyer** [comment]
> However, I've never seen that happen.

See https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration#videolan-client

**Comment by sfkpmr** [comment]
Should I just add --play-and-exit to the config file?

Also, the link to the Streamlink config at the top is dead. Current link - https://streamlink.github.io/cli.html#configuration-file

**Comment by bastimeyer** [comment]
> Should I just add --play-and-exit to the config file?

No, this is a **VLC** parameter and not a Streamlink parameter.
The Twitch GUI already includes player presets that can be selected in the settings menu, so that those player parameters don't need to be set in Streamlink's `--player-args` parameter.

> the link to the Streamlink config at the top is dead

I know, the link anchors in the docs have had a change recently. streamlink/streamlink.github.io#1

**Comment by sfkpmr** [comment]
Oh!

How can I use it along with Streamlink, can I just add it to the target in the VLC.exe properties?

"C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --play-and-exit

**Comment by bastimeyer** [comment]
With Streamlink alone, you can either add player parameters to the value of the `--player` (`-p`) Streamlink parameter or use `--player-args` (`-a`), which is a bit more elegant, but also requires `{filename}` to be included somewhere in its value.
```sh
# This generates bad log outputs
streamlink -p "/path/to/vlc --play-and-exit" STREAM QUALITY
# This is the better way
streamlink -p "/path/to/vlc" -a "--play-and-exit {filename}" STREAM QUALITY
```

In the Twitch GUI, just select the VLC player preset in the player settings menu and make sure that the according checkbox is set for the `--play-and-exit` VLC param.

Btw, you can read all of this in the Streamlink docs and Twitch GUI wiki. I don't want to and don't have the time to explain this for every user separately.
