### ISSUE TITLE
Play host after streamer quits and hosts someone

### ISSUE THREAD

**Issue by rhazor** [streamlink/streamlink-twitch-gui#427]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first!*

*Feel free to use the following template. Be as detailed as possible.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

If you watch someone on VLC and he decides to stop stream and host someone, player should play the hosted stream?

### Expected / Actual behavior

Now it just quits VLC Player.

### Reproduction steps

1. Play your favorite stream
2. Wait till host
3. No host, quit player because stream ended

### Environment details (operating system, etc.)

Win10 x64, latest Streamlink Twich GUI, latest VLC, latest Livestreamer

### Comments, logs, screenshots, etc.

Nothing comes to mind.

**Comment by bastimeyer** [comment]
This basically falls into the same category as #241, so I'm closing your thread in favor of the already existing one.

Also:
I'm not too sure, but I think viewer redirections on the Twitch website (when a channel starts hosting another one) are tied to the chat system (IRC messages). IRC has not been implemented here yet, so this makes this feature a bit more difficult to implement. Although I have added hosting channels into the Twitch GUI last year, the part of the Twitch API is still private and there's no way of checking for a specific channel whether it is hosting another one.
