### ISSUE TITLE
Chocolatey-distributed version needs an update to 1.2.0

### ISSUE THREAD

**Issue by siziyman** [streamlink/streamlink-twitch-gui#428]
Chocolatey still has v1.1.1 as latest version. Would love to get actually latest version from there, hope you'll update that.
Thanks!

**Comment by bastimeyer** [comment]
I'm not the maintainer of the package...
See here: https://github.com/streamlink/streamlink-twitch-gui-chocolatey/issues/10

**Comment by bastimeyer** [comment]
I'll close this issue since 1.2.0 has been published to chocolatey.
https://chocolatey.org/packages/streamlink-twitch-gui/1.2.0
streamlink/streamlink-twitch-gui-chocolatey#11

The package still needs to be approved by a choco moderator, though.
