### ISSUE TITLE
Error: Invalid Streamlink Version

### ISSUE THREAD

**Issue by thorerikn** [streamlink/streamlink-twitch-gui#429]
### Checklist

- [x] This is a bug report.
- [ ] Streamlink is working correctly on my system without using the Twitch GUI.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I used the search function to find already opened/closed issues or pull requests.

### Description

I got "Error: Invalid Streamlink Version. Your version v.0.1.0 doesn't match the min. requirements (v.0.2.0)" after downloading the newest Streamlink Version.

### Environment details (operating system, etc.)

Mac OS X v10.12.3

### Comments, logs, screenshots, etc.

My apologies for not really knowing what to do, I'm not a professional. Any help would be appreciated.

**Comment by bastimeyer** [comment]
> after downloading the newest Streamlink Version
> 0.1.0

The newest Streamlink release is `0.4.0`. You did not install the latest one...
https://github.com/streamlink/streamlink/tags

How did you install Streamlink?
https://streamlink.github.io/install.html

There's also the wiki of the Streamlink Twitch GUI with install instructions for both applications:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation

**Comment by bastimeyer** [comment]
I'm going to close this thread since I didn't receive an answer.
If you think that the Twitch GUI is definitely responsible for this, feel free to reopen.
