### ISSUE TITLE
Medium quality = low quality

### ISSUE THREAD

**Issue by Arzack** [streamlink/streamlink-twitch-gui#435]
### Checklist

- [x] This is a bug report.
- [?] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

If I start streams at medium quality, it opens low quality instead. 
Maybe it has to do with the recent twitch qualities update.

### Environment details (operating system, etc.)

win 7 with mpc-hc (from cccp 64bit folder)

**Comment by bastimeyer** [comment]
Are you using the latest version (`v1.2.1`)?
See #434
