### ISSUE TITLE
Right clicking links and images with a link in channel details / Copy URL

### ISSUE THREAD

**Issue by Robby-** [streamlink/streamlink-twitch-gui#436]
It would be nice if in the channel details of a streamer when you right click a link or an image with a link, that there is an option to copy the URL, exactly like its already possible when right clicking a link in their stream title. Right now there is only `Open in browser`.

**Comment by bastimeyer** [comment]
Yeah, this seems to have been forgotten when it was implemented. The text links in the channel panels also don't have a copy link context menu item right now.
