### ISSUE TITLE
doesn't search anything that includes underscore

### ISSUE THREAD

**Issue by stlongear** [streamlink/streamlink-twitch-gui#437]
Looked up name, that included underscore: "_". 
Does not work with name alone or with full link.

Examples:
https://www.twitch.tv/mc_arkas
mc_arkas

The only way to find was with dropping left side of with underscore. While there was link with underscore, nothing seemed to work. Probably people know about this limitation, but I just checked my internet connection that had some problems earlier, because I thought that it was not working again...

**Comment by bastimeyer** [comment]
Yep, the regular expression for validating inputs is wrong here.
