### ISSUE TITLE
Middle clicking channel page causes NW.js popup

### ISSUE THREAD

**Issue by scowalt** [streamlink/streamlink-twitch-gui#447]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Reproduction steps

1. Open Streamlink Twitch GUI (signed in)
2. Under the "My" section, navigate to the "Channels" page
3. Middle click on any channel name

### Expected behavior

Any of the following:

- Open the channel page in the native browser
- Mirror left click behavior
- Do nothing

### Actual behavior

A NW.js popup window is opened navigated to `chrome-extension://invalid`

### Environment details (operating system, etc.)

Windows 10 Creator's Update, x64
Streamlink Twitch GUI v1.2.1

### Comments, logs, screenshots, etc.

Also happens when middle-clicking games on the same page. Probably just need to override the default behavior for the whole page?

Cheers!

**Comment by bastimeyer** [comment]
Thanks for reporting!
