### ISSUE TITLE
Error when tried to open "Games" on "Browser" section

### ISSUE THREAD

**Issue by moige** [streamlink/streamlink-twitch-gui#448]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I get this error (showm in command line) when I tried to view "Games" on "Browser" section:

`streamlink-twtich-gui 2> twitch.log` output:

```
[6130:6130:0515/121429.968608:ERROR:child_thread_impl.cc(762)] Request for unknown Channel-associated interface: ui::mojom::GpuMain
[6087:6087:0515/121432.030220:ERROR:browser_main_loop.cc(279)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[error][Application]
Error: Adapter operation failed
    at V.U (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:26:170540)
    at V (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:18:99933)
    at Ne.handleResponse (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/main.js:7:43339)
    at J (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:18:103179)
    at Ne.ue.error (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:18:106862)
    at Vr (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:26:480548)
    at Object.fireWith [as rejectWith] (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:26:481405)
    at Lr (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:26:521778)
    at XMLHttpRequest.<anonymous> (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/vendor.bower.js:26:526993)

```
#### NOTE 
+ _All_ others sections works fine and don't present errors logs.
+ Chrome, Chromium or derivative are not installed.

### Reproduction steps

1. Open `streamlink-twitch-gui` on command line
2. Open "Games" on "Browser" 
3. View error log in command line or in a file if you use `2> foo.log`

### Environment details (operating system, etc.)

`uname --all`:
`Linux ATENAS 4.9.27-1-MANJARO #1 SMP PREEMPT Mon May 8 08:48:50 UTC 2017 x86_64 GNU/Linux`

**Comment by bastimeyer** [comment]
Thanks for the detailed report!

> Error: Adapter operation failed

Is there a more specific error message shown in the application window? Unfortunately, this is a generic adapter error message which is getting logged here. An AdapterError can also be a simple HTTP error (4xx or 5xx), so I don't think there's a bug in the [GamesIndexRoute](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.2.1/src/app/routes/GamesIndexRoute.js#L17-L20). It's a normal route like the others and there's nothing special going on there.

> All others sections works fine and don't present errors logs.

This is the strange part, but I'd not be surprised if there's an ongoing issue in the Twitch API or on the specific API server to which your IP address was assigned to by the load balancing mechanism. This has happened to me a few times in the past years.

You could try to delete your application cache and config files located in `~/.{cache,config}/streamlink-twitch-gui`, but I don't think this will help. There's also the option for you to install the `streamlink-twitch-gui-git` AUR package, so you can try the latest development build.

**Comment by moige** [comment]
> Is there a more specific error message shown in the application window?

![Here I'm viewing the preview section](https://cloud.githubusercontent.com/assets/15069486/26069716/e8c3ae7c-396f-11e7-87d4-2db122916fe9.png)
^ Viewing the preview section (Sorry for the cutted window. I only have 1024x600 of resolution :P).
![Error in "Games" sections](https://cloud.githubusercontent.com/assets/15069486/26069791/3381f54a-3970-11e7-873b-9dab03dc0b3f.png)
^ Try to view the "Game" section where Error appear.

> You could try to delete your application cache and config files...

I tried to do that, but nothing happen.

> There's also the option for you to install the `streamlink-twitch-gui-git` AUR package, so you can try the latest development build.

I'm going to do that. I will give you the feedback.

Thanks for the response. 👍

**Comment by bastimeyer** [comment]
> 400 Malformed locale

What's your system's locale? This is automatically included in each HTTP request made by NW.js / Chromium and the error message (the response from the Twitch API) suggests that they don't accept the value set on your system. I don't know though why they are returning this error only on the top games API namespace and not everywhere else.

You can check your [system's locale](https://wiki.archlinux.org/index.php/Locale) by running `locale`.

Please try starting the application with `env LANG=en_US.UTF-8 streamlink-twitch-gui` and see if the error persists.

**Comment by moige** [comment]
> You can check your system's locale by running `locale`.

```
$ locale
LANG=es_VE.UTF-8
LC_CTYPE="es_VE.UTF-8"
LC_NUMERIC=es_VE.UTF-8
LC_TIME=es_VE.UTF-8
LC_COLLATE="es_VE.UTF-8"
LC_MONETARY=es_VE.UTF-8
LC_MESSAGES="es_VE.UTF-8"
LC_PAPER=es_VE.UTF-8
LC_NAME=es_VE.UTF-8
LC_ADDRESS=es_VE.UTF-8
LC_TELEPHONE=es_VE.UTF-8
LC_MEASUREMENT=es_VE.UTF-8
LC_IDENTIFICATION=es_VE.UTF-8
LC_ALL=
```
> Please try starting the application with env LANG=en_US.UTF-8 streamlink-twitch-gui and see if the error persists.

![Without error](https://cloud.githubusercontent.com/assets/15069486/26070863/1f2d32d6-3974-11e7-9ea9-9d065fc5baff.png)
^ All sections work without errors. But, why only the error appear in "Games" section?
I will try to use `streamlink-twitch-gui-git`. Thanks for the response. 👍

**Comment by bastimeyer** [comment]
> why only the error appear in "Games" section?

This is the mysterious logic of the Twitch API which no one will ever be able to understand. 🤔 
On other words, it's inconsistent AF and a PITA.

At least you were able to fix this issue. 👍
I'm closing the thread.

**Comment by Soufey** [comment]
I have the same problem but i use windows, i don't use the command line for anything, any ideas?

**Comment by bastimeyer** [comment]
@Soufey Are you sure you're talking about the same issue and not about #517 for example? It is always a bit difficult judging comments without any further details, especially if those are posted on issues which have been closed for almost a year.

**Comment by Soufey** [comment]
@bastimeyer sorry for the late response, i get this error when trying to browse the "Games" section in the GUI. im using the windows version
![cd386bae9879dc97cf0edc821136034f](https://user-images.githubusercontent.com/10188198/38911416-0f44dd8c-4284-11e8-9a8a-655f4e894e12.png)

**Comment by bastimeyer** [comment]
@Soufey 
What is your system's locale? As you can see in the other posts of this thread, the source of this issue is your system's locale, which is being used by NW.js/Chromium in all https requests and the Twitch API (kraken v5) is failing on the /games/top endpoint for no apparent reason. Try to set it to `en_US` and see if it works. I don't know how this can be done on Windows and if you're able to set this on a per-application level, so you have to look this up yourself.

**Comment by Soufey** [comment]
@bastimeyer 
Thank you! i changed user and system locale to english (us) and it solved it.

**Comment by bastimeyer** [comment]
Which one were you using before?

**Comment by Soufey** [comment]
@bastimeyer system locale was English (us) and user locale was spanish (mexico)
