### ISSUE TITLE
"Couldn't validate python script" (Streamlink portable)

### ISSUE THREAD

**Issue by tmarplatt** [streamlink/streamlink-twitch-gui#451]
I'm trying to launch streamlink-twitch-gui after updating it to 1.3.0 (Windows portable). But after clicking on a stream to launch the GUI shows this error message: "Couldn't validate python script". Stream doesn't launch at all.

I was on 1.2.1 (Windows portable) before and loading streams without problems. Streamlink is up to date and without issues. I tried with both 32 and 64 bit version of streamlink-twitch, getting the same error.

### Environment details (operating system, etc.)

I'm using Windows 7 64bit. 

I'll be glad to produce more feedback if necessary. You're doing a terrific work with this app. :)

**Comment by sadiablos** [comment]
Do you have python executables set in settings?

**Comment by bran** [comment]
Mine are set to:

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/streamlink

Respectively.

Get the same error about validate python script.

**Comment by bastimeyer** [comment]
@tmarplatt 
Streamlink portable is not offically supported. You're seeing this error, because the new implementation of the stream launch logic [is a bit more strict than before](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.0/src/app/services/StreamingService/provider/resolve.js#L85-L95) and [expects a valid streamlink python script](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.0/src/app/services/StreamingService/provider/find-pythonscript-interpreter.js#L26-L30). The reason for this are streamlink packages for other OSes like the MacOS homebrew package that should work without defining a custom config. The python script of the portable version on Windows is *malformed* and doesn't include a shebang, which the Twitch GUI expects. I'll see if I can make it so that the Twitch GUI ignores it if a custom exec has been set. This is a bit more logical to me and would solve the issues with the portable version.

**Comment by bastimeyer** [comment]
@bran 
How did you install Streamlink? Installing streamlink via homebrew, easy_install and python-pip should work without defining a custom config.

Could you please post the content of your custom streamlink python script path (`/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/streamlink`)?

**Comment by MrLint** [comment]
@bastimeyer 

I'm also using the portable on windows, with it ive managed to cobble together a fully portable streamlink 'suite' and i'd like to keep it that way.. 

Thanks for your efforts.

**Comment by tmarplatt** [comment]
@bastimeyer 
Indeed I forgot to include that I am using streamlink portable. I've also set streamlink-twitch-gui to use the python executable bundled with streamlink portable.

**Comment by bastimeyer** [comment]
Let me reopen this thread until a new release gets published, so we don't get any reposts.

In the meantime, you can *fix* this issue by adding a shebang to the stream link python script pointing to the pythonw.exe file.

Example:
```
#!"C:\absolute\path\to\pythonw.exe"
```

**Comment by jhanssen** [comment]
I'm getting this error as well on OS X, using python3 from homebrew and streamlink installed through pip. Python executable is `/usr/local/bin/python3` and Streamlink python script is `/usr/local/bin/streamlink`

**Comment by bastimeyer** [comment]
@jhanssen This thread is about the Streamlink portable version on Windows. Let me try to help you anyway...

On macOS you should make sure that you are using a clean environment. The streamlink-twitch-gui homebrew cask has streamlink set as a homebrew formula dependency. There is no need to install streamlink via pip. Even if you did use pip or easy_install, the Twitch GUI should be able to automatically resolve the correct files while not having set any custom paths in the settings menu.
You can find debug/error log files in `$TMPDIR/streamlink-twitch-gui/logs`. Maybe this will help you a bit further.

**Comment by jhanssen** [comment]
Sorry. I've opened #459 to track my OS X issue separately.

**Comment by bastimeyer** [comment]
`v1.3.1` has been released containing the fixes for this issue...
https://github.com/streamlink/streamlink-twitch-gui/releases/latest

**Comment by thejustsoul** [comment]
`v1.3.1` does not fix the error.
Previously I had no problems with the launch of streamlink. But when Upgrading to 1.3.1 (with the old version 1.2.XX) and updating streamlink to version 0.8.1 (as usual after unpacking the installer (without any changes) to the folder with the GUI and putting in the settings the path is:
`streamlink-0.8.1\Python\pythonw.exe`
`streamlink-0.8.1\bin\streamlink-script.py`
I get the error as the topic starter. How to fix it without changes scripts (edits) of something?

**Comment by bastimeyer** [comment]
@thejustsoul this is a configuration error on your side. Both Streamlink portable installation methods of `0.8.1` are working fine in the `v1.3.1` release and master version of the Twitch GUI.

Please follow the installation instructions from the wiki to fix your issue:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

> ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Streamlink\Python\python

Your pythonw.exe path seems to be cut off. You have to set the correct path here pointing to the `pythonw.exe` python executable.

`v1.2.1` was using a different resolving strategy and validating logic that wasn't working on all systems and needed to be fixed. A result of these changes is that you need to specify explicit paths as a Streamlink portable user.
de75211
050fbc1
3d435d1

**Comment by thejustsoul** [comment]
@bastimeyer Downloaded a fresh version, again. What am I doing wrong? I tried to specify the `full path`,`.\`, `./`, does not work. Need add to PATH path for `streamlink-0.8.1\Python\pythonw.exe` and `streamlink-0.8.1\bin\streamlink-script.py`?
![](https://i.imgur.com/kv7xFli.png)

**Comment by bastimeyer** [comment]
@thejustsoul 
I noticed there was an issue with resolving relative paths in some cases. This is fixed now on the master branch.
