### ISSUE TITLE
The specified stream(s) 'high, best' could not be found.

### ISSUE THREAD

**Issue by qwaszer** [streamlink/streamlink-twitch-gui#452]
This only happens when trying to use "high" on some streams. I believe it is on 60fps streams when 720p60_alt should be pulled up I assume (720p60 being source, 480p medium), but unfortunately it always fails.

Running the latest 1.3.0 and 0.6.0

**Comment by bastimeyer** [comment]
Which stream are you trying to watch and which qualities are available?
Please post the output of
`streamlink twitch.tv/{CHANNEL}`

**Comment by qwaszer** [comment]
It was happening on every stream I tried last night. But less now, although here's one stream for example: twitch.tv/dsharp3

I get this message:

error: The specified stream(s) 'high, best' could not be found.
Available streams: audio_only, 160p, 360p, 480p, 720p60

but using streamlink only, will display this: http://i.imgur.com/GUqXejW.png

I understand now that the twitch-gui high setting tries to display 540p or 720p, and that if 720p_alt and/or 720p60_alt were added to that, there would be conflictions as some streams (twitch.tv/draqu_ for example) have both 720p and 720p60_alt options.

**Comment by bastimeyer** [comment]
> Available streams: audio_only, 160p, 360p, 480p, 720p60
> high setting tries to display 540p or 720p

No, it tries to find the best available quality between 540p and 720p30.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.0/src/app/models/stream/qualities/streamlink.js#L30

To be honest, the second constraint in each exclusion rule can be removed, as we only need to remove better qualities than the one selected. The `best` alias will still select the best of the remaining ones, even if the lower qualities are not excluded. In this case, this means that if there's no quality between 540p and 720p30, it'll use the next best, 480p. Admittedly, this would be the same as medium, but that's ok for a stream with fewer quality options (360p is the min quality accepted by the Twitch GUI).

**Comment by qwaszer** [comment]
ah yes 720p30 is what i meant. ok so i can just add the extras I want for now in the advanced options. thanks.

**Comment by bastimeyer** [comment]
Reopening for visibility until the next release...

**Comment by bastimeyer** [comment]
`v1.3.1` has been released containing the fixes for this issue...
https://github.com/streamlink/streamlink-twitch-gui/releases/latest
