### ISSUE TITLE
Unable to to load up 720p_alt or 720p60_alt streams 

### ISSUE THREAD

**Issue by FireLord334** [streamlink/streamlink-twitch-gui#454]
With v1.2.1 I was able to load stream for 720p_alt and 720p60_alt. With the new update (v1.3.0) I understand now that you put in the quality settings you don't want the stream loaded in, but these two quality settings (I would assume all '_alt' setting) just don't load up no matter what I try. For example the available streams for a channel on twitch are 'audio_only, 720p_alt, 160p, 360p, 480p, 720p (best)'. I now want to access the 720p_alt quality setting. How would I go about doing this in v1.3.0?

**Comment by bastimeyer** [comment]
The exclusion list is just used by the `best` alias. You can still add explicit quality names in the second column, like before.

**Comment by FireLord334** [comment]
I am unable to click within the second column to change the quality setting.

**Comment by bastimeyer** [comment]
I'm sorry, you're right. I got confused here for a sec.
I'll see if I can add this in the upcoming bugfix release.

If this is a big issue for you, just downgrade back to 1.2.1.

**Comment by FireLord334** [comment]
ok thanx
