### ISSUE TITLE
Tag/Keyword followed channels

### ISSUE THREAD

**Issue by tezJR** [streamlink/streamlink-twitch-gui#456]
This is a feature request to tag my hundreds of followed channels so I may remember why I followed them. On the channel page, I can add/edit/delete keywords (such as the channel I met them in, the game I enjoyed them playing, or any helpful keyword). I could then search, and find all channels with that keyword.

This would help me group them and remember why they're relevant to me. People I've mentioned the idea to like it. Is there an easy way to add this and is this in-scope?

**Comment by bastimeyer** [comment]
Thanks for the suggestion.

> Is there an easy way to add this

It's pretty simple to implement such a feature in Ember apps. It's a bit of work, though, and I'm not sure yet what the best way would be to add this (layout-wise). Also, to be able to search for tags, the search bar would need to be updated first, which means that there is some additional work.

This kind of feature would be very low priority for me, so this may not be added in the *near* future as I want to focus on other things first.

> is this in-scope?

I don't know. There are a couple of issues. The currently used client-side data adapter (HTML5 localStorage) may not be a good fit for storing information of hundreds of records that require an index structure. I'd first need to look for an alternative.
