### ISSUE TITLE
Couldn't validate python script error message on OS X

### ISSUE THREAD

**Issue by jhanssen** [streamlink/streamlink-twitch-gui#459]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

I started getting an error message saying `Couldn't validate python script` when launching twitch streams after upgrading from 1.2.1 to 1.3.0. Downgrading to 1.2.1 makes the problem go away.

### Reproduction steps

1. Open the app
2. Select a stream and try to watch it

### Environment details (operating system, etc.)

Streamlink Twitch GUI 1.3.0, OS X, Python 3.6.1, streamlink installed from pip.

### Comments, logs, screenshots, etc.

The log file contains entries like the following

```
[2017-05-24T02:40:57.084Z][error][StreamingService]
Error: Couldn't validate python script
    at n.a (chrome-extension://kjlcknihpadniagphehmpojkkdigigjp/main.js:7:192748)
```

**Comment by bastimeyer** [comment]
You have custom paths set in the settings menu?
Could you please post the results of
```bash
which streamlink
head -n 1 $(which streamlink)
```

**Comment by jhanssen** [comment]
I tried several different paths, right now my custom paths are `/usr/local/opt/python3/bin/python3.6` for Python executable and `/usr/local/bin/streamlink` for Streamlink python script.

```
$ which streamlink
/usr/local/bin/streamlink

$ head -n 1 $(which streamlink)
#!/usr/local/opt/python3/bin/python3.6

$ /usr/local/opt/python3/bin/python3.6 --version                                                                      ⏎
Python 3.6.1
```

**Comment by bastimeyer** [comment]
I can't think of a possible reason right now why this shouldn't work. Unfortunately, the error message doesn't tell you what exactly is failing here. I'll see if I can improve this in the next release.

Could you please run a dev build and set a break point in this line:
https://github.com/streamlink/streamlink-twitch-gui/blob/050fbc1addcfbeac19ad97c61f4bdbb342086489/src/app/services/StreamingService/provider/resolve.js#L96
Instructions can be found [here](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.0/CONTRIBUTING.md#developing-and-building)...

Thanks

**Comment by jhanssen** [comment]
Sure, I might not have time tonight. I did a bit of digging though and see that the following exception is raised: 
```json
{ "errno": -2, "code": "ENOENT", "syscall": "stat", "path": "/usr/local/opt/python3/bin/python" }
```
There's no `python` file in `/usr/local/opt/python3/bin/`, but there is a `python3` file there and also a `python3.6` file which is the one my custom path is set to. Hopefully this is sufficient, otherwise I can do more debugging tomorrow.

**Comment by bastimeyer** [comment]
Thanks. This is exactly what I need. 👍 
See here:
https://github.com/streamlink/streamlink-twitch-gui/blob/050fbc1addcfbeac19ad97c61f4bdbb342086489/src/app/services/StreamingService/provider/find-pythonscript-interpreter.js#L65-L68

The reason for this logic is that there are two python executables on Windows. One which requires a Windows command prompt (`python.exe`) and one *normal* one (`pythonw.exe`). Unfortunately, the shebang in the streamlink script on Windows is including the wrong one and that's why only the dirname is being used here. The expected executable name is then added to that path. This works when the python executable name is the same as the expected one(s), which is usually the case on all supported OSes:
https://github.com/streamlink/streamlink-twitch-gui/blob/050fbc1addcfbeac19ad97c61f4bdbb342086489/src/config/streamprovider.json#L31-L35

This can be fixed by either adding `python3` (and `python2`) to the list of expected executable names, or by improving the resolver logic, so that it also checks the explicit path in case of an error.

**Comment by jhanssen** [comment]
Aha, thanks for the detailed info. I created a `python` symlink in `/usr/local/opt/python3/bin` and streams are indeed launching now. I can live with this as a workaround until this gets fixed.

**Comment by bran** [comment]
This doesn't seem to be working for me as my UI config seems to be pointed to the correct python versions:

/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/python3.5
and
/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/streamlink

Yet I'm still getting that error.

**Comment by bran** [comment]
`$ ls /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/
2to3                    idle3                   pip3.5                  python3-config          python3.5m-config
2to3-3.5                idle3.5                 pydoc3                  python3.5               pyvenv
easy_install            pip                     pydoc3.5                python3.5-config        pyvenv-3.5
easy_install-3.5        pip3                    python3                 python3.5m              streamlink`

**Comment by jhanssen** [comment]
@bran The problem I was having was that the app would take the basename from streamlink and append `python` to that and not using the one specified in the UI. If you're having the same problem then making a symlink from `python3.5` to `python` in `/opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/` should fix this. I.e.

```
cd /opt/local/Library/Frameworks/Python.framework/Versions/3.5/bin/
ln -s python3.5 python
```

**Comment by bran** [comment]
@jhanssen yep can confirm this works! Thanks for clarifying.
