### ISSUE TITLE
"Interrupted! Exiting..." when using verbose

### ISSUE THREAD

**Issue by GreyAsteroid** [streamlink/streamlink-twitch-gui#463]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Opening a stream using streamlink-twitch-gui fails with "Interrupted! Exiting..."  when the verbose player option is active in my .streamlinkrc file.

### Environment details (operating system, etc.)

Linux
streamlink-twitch-gui v1.3.1
streamlink 0.6.0

### Comments, logs, screenshots, etc.

When using mpv `statusline: (Buffering) AV: 03:02:54 A-V: 0.000 Cache: 0s
statusline:
[+-----------------------------------------------------------------------------]
Interrupted! Exiting...`

When using vlc `[0000000000845148] core libvlc: Running vlc with the default interface. Use 'cvlc' to use vlc without interface.
Interrupted! Exiting...`

**Comment by bastimeyer** [comment]
Thanks for reporting...

One of the output messages seems to be treated as an error message.
I can't reproduce this with mpv, but vlc fails when using the `-v` custom streamlink parameter.
