### ISSUE TITLE
VLC Immediate Crash on macOS

### ISSUE THREAD

**Issue by 404NetworkError** [streamlink/streamlink-twitch-gui#464]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

VLC on macOS crashes immediately after successfully launching a stream through the GUI.

My fix on pre-1.3.x versions of the GUI was to use `--verbose=0` as a parameter to VLC.  I know that this does nothing for VLC, but it allowed the stream to play.  This fix doesn't work on current versions of the GUI because of the bug I believe you are aware of from #463.

What does appear to work is using `rtmp` as the passthrough option.  I tried both `http` and `hls` and both crashed VLC in a similar manner.  The error I received from VLC when using `http` or `hls` is shown in figure [1](https://cloud.githubusercontent.com/assets/10837458/26596836/b603eec6-4535-11e7-9435-835767a73698.png).  Figure [2](https://cloud.githubusercontent.com/assets/10837458/26596855/c28ef032-4535-11e7-8ee2-9c1d0538f6a4.png) shows what happens when I attempt to pass `-v` to VLC.  I have also included the GUI logs which correspond to the 2 test cases.

### Expected / Actual behavior

VLC will not crash when playing a stream with either `http` and `hls` passthrough.

### Reproduction steps

1. Install streamlink v0.6.0 via pip, streamlink-twitch-gui v1.3.1 from GitHub releases, and VLC v2.2.5.1 from the official site.
2. Start a random stream.
3. VLC opens with error log message and then immediately closes.

### Environment details (operating system, etc.)

macOS 10.11.6
streamlink 0.6.0 (installed via pip)
streamlink-twitch-gui 1.3.1
VLC 2.2.5.1

### Comments, logs, screenshots, etc.

Figure 1. VLC Error Log
![vlc error log](https://cloud.githubusercontent.com/assets/10837458/26596836/b603eec6-4535-11e7-9435-835767a73698.png)

Figure 2. GUI Error Message
![gui error](https://cloud.githubusercontent.com/assets/10837458/26596855/c28ef032-4535-11e7-8ee2-9c1d0538f6a4.png)

Log 1. GUI log for normal operation
[GUI Log (Normal Operation).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1039222/GUI.Log.Normal.Operation.txt)

Log 2. GUI log for VLC verbose
[GUI Log (VLC Verbose Operation).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1039223/GUI.Log.VLC.Verbose.Operation.txt)

**Comment by bastimeyer** [comment]
Thanks for the detailed report!

The VLC issue on MacOS in combination with the http passthrough method has been reported in #445 (let's discuss this here, though), but I don't know what is causing it. As you can see in your first screenshot, VLC interprets the local http URL as a relative path for some reason. Since the Twitch GUI has nothing to do with spawning the player process, this issue is most likely caused by either Streamlink or VLC itself.

Regarding your second screenshot, I must say that it confuses me. Why is streamlink complaining about invalid parameters, if all that has been changed was the content of the `--player-args` param? This doesn't make sense to me.

Could you please run streamlink with the same parameters listed in the log from your shell (don't forget to properly escape the param values) and post the results?

**Comment by 404NetworkError** [comment]
Here are the logs from different tests using streamlink from a shell.  It appears that streamlink is not running properly when `-v` is being used as the [only parameter](https://github.com/streamlink/streamlink-twitch-gui/files/1040100/Streamlink.Log.HTTP.VLC.only.-v.txt) or the [1st parameter](https://github.com/streamlink/streamlink-twitch-gui/files/1040104/Streamlink.Log.HTTP.VLC.Verbose-beginning.txt).  If `-v` happens to be in the [middle](https://github.com/streamlink/streamlink-twitch-gui/files/1040103/Streamlink.Log.HTTP.VLC.Verbose-middle.txt) or at the end, it works fine (even in `http` mode).

When ignoring the `-v` issue, I think I might found where the instant crash is coming from.  Using [this](https://github.com/streamlink/streamlink-twitch-gui/files/1040116/Streamlink.Log.HTTP.no.continuous-http.txt), I was able to see that without `--player-continuous-http`, VLC played correctly.  (I can submit an issue with streamlink devs if you want.)

[Streamlink Log (HTTP).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040106/Streamlink.Log.HTTP.txt)
[Streamlink Log (HTTP VLC only -v).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040100/Streamlink.Log.HTTP.VLC.only.-v.txt)
[Streamlink Log (HTTP VLC Verbose-beginning).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040104/Streamlink.Log.HTTP.VLC.Verbose-beginning.txt)
[Streamlink Log (HTTP VLC Verbose-middle).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040103/Streamlink.Log.HTTP.VLC.Verbose-middle.txt)

[Streamlink Log (HTTP no continuous-http).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040116/Streamlink.Log.HTTP.no.continuous-http.txt)

[Streamlink Log (RTMP).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040101/Streamlink.Log.RTMP.txt)
[Streamlink Log (RTMP VLC Verbose-beginning).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040102/Streamlink.Log.RTMP.VLC.Verbose-beginning.txt)
[Streamlink Log (RTMP VLC Verbose-middle).txt](https://github.com/streamlink/streamlink-twitch-gui/files/1040105/Streamlink.Log.RTMP.VLC.Verbose-middle.txt)

**Comment by 404NetworkError** [comment]
After a little more testing, the instant crash in VLC only happens when both `--play-and-exit` and `--input-title-format "{name} - {game} - {status}"` are used simultaneously.  If used individually or neither, VLC works just fine.

**Comment by bastimeyer** [comment]
> I can submit an issue with streamlink devs if you want.

Sure... This is obviously a bug. This happens with every single hyphen parameter, not just `-v`.

```bash
$ streamlink -p vlc -a "-a {filename}" twitch.tv/CHANNEL best
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: argument -a/--player-args: expected one argument

$ streamlink -p vlc -a "a {filename}" twitch.tv/CHANNEL best
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
^CInterrupted! Exiting...

$ streamlink -p vlc -a "--a {filename}" twitch.tv/CHANNEL best
[cli][info] Found matching plugin twitch for URL twitch.tv/CHANNEL
^CInterrupted! Exiting...
```

> the instant crash in VLC only happens when both --play-and-exit and --input-title-format are used simultaneously.

#355
VLC on MacOS is ridiculous...
Well then, I guess the best option would be disabling custom titles in MacOS. The `--play-and-exit` param can't be removed and is necessary to be able close streams from the GUI, so that VLC doesn't ignore SIGTERM signals sent by Streamlink.
