### ISSUE TITLE
Couldn't validate python script [File does not exist]

### ISSUE THREAD

**Issue by Predder** [streamlink/streamlink-twitch-gui#468]
### Description
I keep getting this error when launching a stream using the Twitch GUI:

Couldn't validate python script
ENOENT: no such file or directory, stat 'C:\Program Files (x86)\Streamlink\Python\python3.5-32.

I checked, and the file is indeed not  there. I even tried with a clean installation.

Even using the cli, streamlink throws me errors.
...

### Expected / Actual behavior

...

### Reproduction steps

1. ... Use the Twitch GUI to launch any stream.
2. ...
3. ...

### Environment details (operating system, etc.)
Windows 10, x64.
...

### Comments, logs, screenshots, etc.
https://puu.sh/w8ENX/91180e6a9e.png
https://puu.sh/w8ERp/dce64ae860.png
...

**Comment by bastimeyer** [comment]
Are you using the latest Streamlink Twitch GUI version (`1.3.1`)?
How did you install Streamlink?
Do you have custom settings set in the "streamlink" settings menu of the Twitch GUI?

**Comment by Predder** [comment]
I am using the latest version. 

I used the latest Windows installer build. 

I have No custom settings set.

**Comment by bastimeyer** [comment]
> the latest Windows installer build

So a nightly build then? See the linked issue above...

Streamlink Twitch GUI is only able to work if Streamlink itself is working correctly. There are some guides in the wiki on how to set up Streamlink in the Twitch GUI:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by Predder** [comment]
Thanks. Will try it out when i wake up.

**Comment by bastimeyer** [comment]
Did you manage to get to to work?

**Comment by Predder** [comment]
Yes, it does indeed work now.... Closing.
