### ISSUE TITLE
Will not recognise 720p60_alt streams

### ISSUE THREAD

**Issue by qwaszer** [streamlink/streamlink-twitch-gui#470]
Description:

I would like 720p60_alt streams to be in the "high" quality preset, but it will not use this quality. If I add this, then the better quality (720p60) will be chosen.

This is what happens normally for "high" without any additional settings:

Found matching plugin twitch for URL twitch.tv/fazz
Attempting to authenticate using OAuth token
Successfully logged in as qwaszer
Available streams: audio_only, 720p60_alt, 160p (worst), 360p, 480p (best), 720p60
Starting player: C:\Program Files\VideoLAN\VLC\vlc.exe
Got HTTP request from VLC/2.2.6 LibVLC/2.2.6
Opening stream: 480p (hls)

This is what happens for "high" when I add either just "720p60_alt" or ">720p60_alt":

Found matching plugin twitch for URL twitch.tv/fazz
Attempting to authenticate using OAuth token
Successfully logged in as qwaszer
Available streams: audio_only, 720p60_alt, 160p (worst), 360p, 480p, 720p60 (best)
Starting player: C:\Program Files\VideoLAN\VLC\vlc.exe
Got HTTP request from VLC/2.2.6 LibVLC/2.2.6
Opening stream: 720p60 (hls)

any "_alt" quality just can not be utilised.

**Comment by bastimeyer** [comment]
If you want to select any _alt qualities, you need to list them explicitly in the second column. I don't know if there's currently a way in Streamlink to filter the alternative streams.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#stream-qualities
> The stream quality preset list is made of two columns per row: The first column is being used by the --stream-sorting-excludes parameter, the second column represents the actual quality selection.
