### ISSUE TITLE
vlc ENOENT for v1.2.0 and newer

### ISSUE THREAD

**Issue by mikeboy91** [streamlink/streamlink-twitch-gui#472]
### Checklist

- [x] This is a bug report.
- [x] Streamlink is working correctly on my system without using the Twitch GUI.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

Getting an error on launching a stream "watch vlc ENOENT". This happens with v1.2.0 and newer. v1.1.1 works as expected. Below is the log entry from trying to launch a stream.

### Expected / Actual behavior

Click play and watch the stream with VLC :)

### Reproduction steps

1. start any stream

### Environment details (operating system, etc.)

OS: Kubuntu 16.04 LTS (64Bit)
VLC: 2.2.2
streamlink: 0.6.0
node: v7.9.0
npm: 4.2.0

### Comments, logs, screenshots, etc.

```
[2017-06-03T18:55:47.139Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "rocketbeanstv",
    "quality": "source",
    "gui_openchat": false,
    "started": "2017-06-03T18:55:47.075Z",
    "stream": "47627824",
    "channel": "47627824"
}

[2017-06-03T18:55:47.174Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": "",
        "params": "",
        "pythonscript": ""
    }
}

[2017-06-03T18:55:47.180Z][debug][StreamingService]
Found streaming provider
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/local/bin/streamlink"
    ],
    "env": null
}

[2017-06-03T18:55:47.192Z][debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/local/bin/streamlink",
        "--version",
        "--no-version-check"
    ],
    "env": null
}

[2017-06-03T18:55:48.433Z][debug][StreamingService]
Validated streaming provider
{
    "version": "0.6.0"
}

[2017-06-03T18:55:48.435Z][error][StreamingService]
Error: watch vlc ENOENT
{
    "id": "rocketbeanstv",
    "quality": "source",
    "gui_openchat": false,
    "started": "2017-06-03T18:55:47.075Z",
    "stream": "47627824",
    "channel": "47627824"
}
```

**Comment by bastimeyer** [comment]
Could you please try running the latest version? You seem to be using an older release where the player resolve process is not being logged.

Please also check your player configuration in the settings menu. An `ENOENT` error means that the player executable file could not be found in the file system and "watch vlc" doesn't look like a correct name for the vlc executable.

**Comment by mikeboy91** [comment]
Found out, that I had no Player Preset in my Player Settings. So it was just a misconfiguration. Everything is running now, after I had problems related to https://github.com/streamlink/streamlink/issues/963 and https://github.com/streamlink/streamlink/issues/966 but downgrading `requests` to `2.15.1` resolved that issue aswell.
