### ISSUE TITLE
Naming player window with VLC

### ISSUE THREAD

**Issue by masterbater089** [streamlink/streamlink-twitch-gui#473]
Hello I am having trouble trying to find a command to name the window of the player through VLC

I use
streamlink  --player "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --meta-title=<imaqtpie>  twitch.tv/imaqtpie best

but then it says The system cannot find the file specified.

And if I use
streamlink  --player "C:\Program Files (x86)\VideoLAN\VLC\vlc.exe" --meta-title "imaqtpie " twitch.tv/imaqtpie best

then it says
streamlink-script.py: error: unrecognized arguments: --meta-title best

So do you guys know the right way to use this meta-title?

**Comment by masterbater089** [comment]
The first one was --meta-title=<imaqtpie>

**Comment by masterbater089** [comment]
--meta-title= < imaqtpie >  was the first command

**Comment by bastimeyer** [comment]
Wrong repo, this is **Streamlink Twitch GUI** and not **Streamlink**.
See the [Streamlink CLI documentation](https://streamlink.github.io/cli.html#command-line-usage) for a list of available parameters and usage examples.

Let me try to help you anyway:
What you are looking for are **player parameters** and not **streamlink parameters**. `--meta-title` is not a streamlink parameter, as you can see in the error message.
If you want to specify player parameters, you can do this by adding them to the value of the [`--player`](https://streamlink.github.io/cli.html#cmdoption-p) parameter or by using the [`--player-args`](https://streamlink.github.io/cli.html#cmdoption-a) parameter.

Btw, the Streamlink Twitch GUI has a set of convenient options to automatically configure your player, including the window title.

**Comment by masterbater089** [comment]
Sorry

**Comment by bastimeyer** [comment]
It's okay...
I'll close this thread here then
