### ISSUE TITLE
Multi User Login

### ISSUE THREAD

**Issue by soulmansoulman** [streamlink/streamlink-twitch-gui#474]
### Description
u cant change to a different userlogin. it always log u in with the first user logindata used first
u cant change the user after a first login with a user. please update streamlink twitch gui for multiple user use.
...

### Expected / Actual behavior
i use windows streamlink twitch gui and i cant login as a other user, it always login as the same user logged in first.
please make multiple userlogins possible
...

### Reproduction steps

1. ... Use Windows 7
2. ... Install Livestreamer and Streamlink Twitch GUI
3. ... Login with a User
4. Try to Change the User / try to Login With a other User (it wont work)

### Environment details (operating system, etc.)
windwos 7
...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
Streamlink Twitch GUI uses the OAuth 2.0 protocol for authenticating on Twitch. The reason for being signed in automatically is the Twitch.tv website where you're authorizing the application connection. It automatically uses the account you're already signed in with your browser's cookies. If you log out on the Twitch.tv website, you'll be prompted again when using Streamlink Twitch GUI to log in.

There's a `force_verify` parameter though, that forces the user to re-authenticate the application with their account. And while being asked to re-authenticate the user has the option to switch accounts, which means that adding this parameter fixes the issue.
