### ISSUE TITLE
Do not create an icon on desktop

### ISSUE THREAD

**Issue by nyakze** [streamlink/streamlink-twitch-gui#483]
### Description

After every installation/update, the installer puts an icon on my desktop, which I have to delete

### Expected / Actual behavior

Option/tick to disable desktop icon creation. (There is none)

### Reproduction steps

1. Install/update Streamlink Twitch GUI
2. Look at the desktop and see the icon there

### Environment details (operating system, etc.)

Windows 7 x64

### Comments, logs, screenshots, etc.

I only have 1 icon on desktop and want to keep it that way.

**Comment by bastimeyer** [comment]
Thanks for the suggestion
