### ISSUE TITLE
Create a setting that allows you to minimize application instead of closing.

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink-twitch-gui#488]
Right now when I exit STG (streamlink-twitch-gui) with my sxhkd shortcut that closes the window it closes it and this is a correct behaviour, but STG is a type of application that I would like to keep in my background but I always close it by accident because that's what I do for any window. 

It would be a real quality of live improvement for linux users who use tiling window managers. For reference discord minimizes to tray on the same operation instead of completely closing and that is kind of behaviour I would want to see in STG. I am bspwm user myself but I reckon this is the case for any other window manager.

**Comment by callyama** [comment]
+1 on the _classic_ "close to tray" setting :)
