### ISSUE TITLE
SSL CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by osztenkurden** [streamlink/streamlink-twitch-gui#489]
### Checklist

- [x] This is a bug report.
- [x] I used the search function to find already opened/closed issues or pull requests.

### Description

After trying to open any stream, SSL certificate error shows up. In settings I have set both Python and Streamlink locations (in Streamlink directory) and I tried to set '--http-no-ssl-verify' however nothing changed.

### Expected / Actual behavior

Obviously it should just open VLC with stream opened.

### Reproduction steps

Click on any stream in Streamlink Twitch GUI

### Environment details (operating system, etc.)

Windows 7 64bit

### Comments, logs, screenshots, etc.

`Found matching plugin twitch for URL twitch.tv/pgl
Unable to open URL: https://usher.ttvnw.net/api/channel/hls/pgl.m3u8?allow_audio_only=true&sig=c50e8c21df1edfae549d901a57afbb7798c41b27&player=twitchweb&allow_spectre=false&type=any&allow_source=true&p=689950&token=%7B%22adblock%22%3Afalse%2C%22player_type%22%3Anull%2C%22platform%22%3Anull%2C%22user_id%22%3Anull%2C%22channel%22%3A%22pgl%22%2C%22channel_id%22%3A21681549%2C%22expires%22%3A1500202237%2C%22chansub%22%3A%7B%22view_until%22%3A1924905600%2C%22restricted_bitrates%22%3A%5B%5D%7D%2C%22private%22%3A%7B%22allowed_to_view%22%3Atrue%7D%2C%22privileged%22%3Afalse%2C%22source_restricted%22%3Afalse%2C%22https_required%22%3Afalse%2C%22show_ads%22%3Atrue%2C%22device_id%22%3Anull%2C%22turbo%22%3Afalse%2C%22subscriber%22%3Afalse%2C%22hide_ads%22%3Afalse%2C%22partner%22%3Atrue%2C%22game%22%3A%22counter_strike_global_offensive%22%2C%22mature%22%3Afalse%2C%22ci_gb%22%3Afalse%7D ([SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:645))
Waiting for streams, retrying every 1.0 second(s)`

**Comment by bastimeyer** [comment]
This is a Streamlink issue which is unrelated to the Twitch GUI.
Please make sure that Streamlink itself is working correctly on your system without using the Twitch GUI.

You may want to open a new thread on the Streamlink issue tracker:
https://github.com/streamlink/streamlink/issues

You should take a look at this first, though:
https://github.com/streamlink/streamlink/issues/966
