### ISSUE TITLE
Stream tiles and settings text is bugging out

### ISSUE THREAD

**Issue by Nepturian** [streamlink/streamlink-twitch-gui#493]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Stream tiles are bugging out while hovering over different streams.
Also texts in settings is messed up.
...

### Expected / Actual behavior
When hovering over any live stream tiles it just messes up the program. 
...

### Reproduction steps

1. ...Go to Live streams
2. ...Hover over the streams
3. ...

### Environment details

Operating system and version: ... Windows 10 PRO (1703-483)
Streamlink Twitch GUI version: ... 1.3.1
Streamlink version: ... 0.6.0
Configuration details: ...
*Advanced enabled
*Smooth scrolling enabled
*Allow external commands
*Custom channel names - both
*Flags and Info bar enabled
*Stream title displayed

### Comments, logs, screenshots, etc.

![twitch gui live stream tiles issue](https://user-images.githubusercontent.com/29153523/28647908-5851d254-726a-11e7-8a3c-f843e49e6c2e.png)
![twitch gui text issue](https://user-images.githubusercontent.com/29153523/28647938-8cec6aa6-726a-11e7-8799-5e6ae2b271f1.png)

**Comment by Nepturian** [comment]
Changing to Streamlink 0.7.0 doesn't help by the way.

**Comment by h1z1** [comment]
What do you mean by "bugging out"?

**Comment by Nepturian** [comment]
Text is being garbled, seems other programs have this issue.
Tried Photo in Win 10 and it's worse there, gonna try reversing the newest NVIDIA driver to be sure.
![text garbled](https://user-images.githubusercontent.com/29153523/28651612-2825434a-7283-11e7-8d88-052f37f7dd25.png)

**Comment by Nepturian** [comment]
Seems it was NVIDIA was the cause somehow after complete wipe and reinstall of new driver.
