### ISSUE TITLE
"j[F].trim is not a function" Error

### ISSUE THREAD

**Issue by Suluss** [streamlink/streamlink-twitch-gui#495]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

When trying to open a stream by any means, the stream info box will open and read
'Error
j[F],trim is not a function'

### Expected / Actual behavior

When trying to open a stream, it will open VLC

### Reproduction steps

1. Open ST Gui
2. Press 'play' on any stream
3. Error message would show.

### Environment details

Operating system and version: Windows 10 Ver. 10, Build 15063
Streamlink Twitch GUI version: 1.3.0
Streamlink version: 0.7.0
Configuration details: What do you mean?

### Comments, logs, screenshots, etc.

![untitled](https://user-images.githubusercontent.com/31057202/29347682-f8e232dc-8213-11e7-83cf-8ee8bf97d6d4.png)
Image of my error

![working](https://user-images.githubusercontent.com/31057202/29347719-4d8e58c4-8214-11e7-9a08-99b486269874.png)
Image of streamlink working properly

Sorry if I'm missing something obvious... I'm not too good with any kind of code and have very little experience with Python.

**Comment by bastimeyer** [comment]
This looks like an issue related to the stream quality selection.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.1/src/app/models/stream/Stream.js#L173-L186

Since you're not using the latest version (`1.3.1`), I have to ask, did you downgrade Streamlink Twitch GUI to `1.3.0`?

#454 introduced a change to the quality selection logic, which is not backwards compatible...

**Comment by bastimeyer** [comment]
@Suluss Did you downgrade, or not?

**Comment by Suluss** [comment]
@bastimeyer I did not downgrade, that was the release I had installed actually. I think however me updating Java and also going to 1.3.1 did help out with the error. Sorry about the long time without response.

**Comment by bastimeyer** [comment]
Java is completely unrelated to either Streamlink or Streamlink Twitch GUI...
You must have been using an older release which is unable interpret the structure of the stored settings object created by newer releases. The settings are stored in your `%LOCALAPPDATA%` folder on Windows, or in the dir specified by Chromium's [`--user-data-dir`](https://chromium.googlesource.com/chromium/src/+/master/docs/user_data_dir.md#Overriding-the-User-Data-Directory) launch parameter. So if you like to use an older release, make sure to use a custom config directory.

Closing the thread now...
