### ISSUE TITLE
1.3.1  Does not work

### ISSUE THREAD

**Issue by Lafko** [streamlink/streamlink-twitch-gui#497]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Version 1.3.1 does not work gives an error "Invalid version check output" 
There are no such problems with 1.3.0
I use 64 bit ver

### Expected / Actual behavior (I do not understand what it is)

...

### Reproduction steps (I do not understand what it is)

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Windows 10 1703 15063,540
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.7.0
Configuration details: 

streamlink - Standalone 
Path - C:\Program Files (x86)\Streamlink\bin\streamlink.exe
Stream type -  rtmp
HLS live edge - 5
HLS segment threads - 10
Launch attempts - 1
Retry delay - 3

Player VLC

### Comments, logs, screenshots, etc.

https://yadi.sk/i/KAC069D-3MAE8A

**Comment by bastimeyer** [comment]
There is no "Streamlink standalone" option. The standalone option is only available if you're using Livestreamer, which works differently.

Please follow the wiki if you want to specify custom streamlink paths.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

If you're on Windows and you've installed Streamlink via its Windows installer, then you don't need to set any custom paths in the Twitch GUI at all...

**Comment by Lafko** [comment]
https://yadi.sk/i/KAC069D-3MAE8A 
Here are my settings in 1.3.0 works without problems but in 1.3.1 does not work

**Comment by bastimeyer** [comment]
You have selected "Livestreamer" as streaming provider, while using "Streamlink" related files.

`1.3.1` had some bugfixes for other config edge cases and overall made the configuration more strict. You are simply using invalid settings. This is not a bug.

Again, as I've said, please follow the wiki for anything configuration or installation related.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by Lafko** [comment]
I can not choose streamlink
Solved the problem by writing the way to Livestreamer 
Can close. Thank you

**Comment by bastimeyer** [comment]
> I can not choose streamlink

What exactly do you mean?
There is a dropdown at the top of the settings menu where you can choose between `Streamlink`, `Livestreamer` and `Livestreamer standalone` (on Windows).

The Livestreamer project is dead since two years now. Its usage has been deprecated and you should be using Streamlink instead.

**Comment by Lafko** [comment]
I apologize, did not notice

**Comment by bastimeyer** [comment]
No worries...
Did you manage to get it to run with Streamlink? Please try removing all custom paths first, since the Twitch GUI is able to automatically find the necessary files if you've installed Streamlink correctly.

**Comment by Lafko** [comment]
Yes, it works fine
