### ISSUE TITLE
Incorrect position of icons on channel page

### ISSUE THREAD

**Issue by sadiablos** [streamlink/streamlink-twitch-gui#498]
### Checklist

- [x] This is a bug report.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.

### Description

Icons for following, opening chat, copying url etc are snapping to the bottom of window instead of being at the same level as lower part of stream preview

### Expected

![expected_1](https://user-images.githubusercontent.com/24566138/29496713-bafb8cca-85d8-11e7-946d-07e43fef0c26.png)

### Actual behavior

![actual_1_1](https://user-images.githubusercontent.com/24566138/29496716-c4ec59b2-85d8-11e7-9d1c-a872e46613ef.png)
_(Avatar and name hidden for privacy reasons)_ 

### Reproduction steps

Go on any profile that doesn't have any info underneath the stream

### Environment details

Operating system and version: win7 x64
Streamlink Twitch GUI version: 1.3.1
Streamlink version: 0.7.0

**Comment by bastimeyer** [comment]
Thanks for reporting and sorry for the late response...
