### ISSUE TITLE
--min Parameter

### ISSUE THREAD

**Issue by Jonah2804** [streamlink/streamlink-twitch-gui#507]
- [ ] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

Using Streamlink for a long time now, because its much better than twitch in my webbrowser.
Btw. Thumbs up for what you've done there!
My problem, i want the GUI to be minimized as soon as its autostarting on windows startup.
I read the wiki and found the "--min" parameter, but I do not really get where I have to put it. I tried some things, but nothing worked.
Maybe you can explain me how to setup it right.
I'm using Win10 64bit.

Best regards,
Jonah

**Comment by bastimeyer** [comment]
Hi, thanks...

On Windows, you can set parameters in each shortcut here:
![virtualbox_windows 10_14_11_2017_22_44_44](https://user-images.githubusercontent.com/467294/32806688-bf4dd758-c98d-11e7-8c4b-ed73b2948eae.png)

I just noticed that the `--min` parameter appears to not be working sometimes due to the main application window being still hidden during the initialization... Fixed in 6f7a7556bfebab04ebb7b9d5865be7a965936336

**Comment by Jonah2804** [comment]
okay, I tried that with --min and nothing happens. But I'll try it with --tray.
Does it matter where I put the parameter in? because my target line is pretty long as you can see (don't know if thats normal):

> "C:\Program` Files\Streamlink Twitch GUI\streamlink-twitch-gui.exe" --user-data-dir="C:\Users\jonah\AppData\Local\streamlink-twitch-gui\User Data" --profile-directory=Default --app-id=kjlcknihpadniagphehmpojkkdigigjp

**Comment by bastimeyer** [comment]
These are all explicitly set default parameters, but they are not required and can be omitted.

> Will be there a fix for that in future

It is already fixed, as mentioned above, and will be included in the next release. If you don't want to wait, you are free to [compile the application by yourself off the master branch](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building).
