### ISSUE TITLE
macOS preferences hotkey

### ISSUE THREAD

**Issue by skulblakka** [streamlink/streamlink-twitch-gui#508]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Instead of using the usual "command+," hotkey for preferences the program uses just ",". Not only does this go against the common hotkey used for preferences on mac os but also causes issues when entering a comma into a text field on the GUI.

### Expected / Actual behavior
I think the GUI should use the usual "command+," hotkey for preferences

### Environment details
Operating system and version: macOS Sierra
Streamlink Twitch GUI version: 1.3.1 (installed via homebrew)

**Comment by bastimeyer** [comment]
Thanks for the report!
