### ISSUE TITLE
[1.4.0] Check / Uncheck all doesn't work

### ISSUE THREAD

**Issue by sadiablos** [streamlink/streamlink-twitch-gui#510]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
Settings>Languages>Check all / Uncheck all doesn't work at all

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: Win 7 SP1 x64
Streamlink Twitch GUI version: 1.4.0
Streamlink version: 0.9.0

### Comments, logs, screenshots, etc.
![screenshot_8](https://user-images.githubusercontent.com/24566138/32991177-dc4257ba-cd36-11e7-9733-7dd286a3dec8.png)

**Comment by bastimeyer** [comment]
Thanks 👍
This has somehow not been changed in the recent changes. Unfortunately the controller responsible for these actions doesn't have any tests (yet).

Luckily, 1.4.1 is already on its way due to unexpected macOS packaging issues.
