### ISSUE TITLE
BattleEye conflict?[waiting for moderation]

### ISSUE THREAD

**Issue by gilsy** [streamlink/streamlink-twitch-gui#513]
### Checklist

- [x] This is a bug report.

### Description

Hello.
I have pretty strange problem and i don't know if it is actually appropriate here.
And I can't really distinguish if this problem is even streamlink-twitch-gui specific, but...
After last update of streamlink-twitch-gui every time I launch PUBG parallel to some stream already launched through HTTP to mpv I get PUBG crash after some time in-game with preliminary BattleEye log message "[INFO] Blocked loading of file: "<mpv_location>\mpv.exe".
I tried 3 different mpv versions, and for me result is the same.

### Reproduction steps

1. Launch streamlink-twitch-gui
2. Set player to mpv and streaming method to HTTP
3. Launch some stream
4. Launch PUBG
5. Wait some time

### Environment details

Operating system and version: Windows 7
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.7.0, i think

**Comment by gilsy** [comment]
Also happens for me on "Standard Input" streaming method(or how i should call it?). Other 2 methods don't work for me at all

**Comment by bastimeyer** [comment]
> [INFO] Blocked loading of file: "<mpv_location>\mpv.exe

I'm sorry, but I can't help you here. This looks like an issue regarding BattleEye or MPV.
Streamlink Twitch GUI is "just" a parameter generator for Streamlink and has nothing to do with the player processes, as these are launched by Streamlink and not the Twitch GUI.
Please try running Streamlink without the Twitch GUI and go on from there.
