### ISSUE TITLE
Rainmeter Skin Hooks Possible???

### ISSUE THREAD

**Issue by callyama** [streamlink/streamlink-twitch-gui#515]
Hi!

Is it a feasible idea for Streamlink Twitch GUI to make its data available and update a Rainmeter desktop skin with who is live/what they're playing (among other things potentially but at least those two) either in a simple list (the main idea) or other ways like thumbnails or up-time, etc? Many ideas but a list that updates itself is the core. The final (important) part of the idea I think would be awesome is that if a user were to click one of the names in the list, it would open the stream using whatever settings are configured in the GUI.

HOW AMAZING would this be? I'm not asking for the actual skin to be created, although I'm guessing it would be simple enough. However, if it is possible, I'm sure you devs would need to create a way to supply the information that ends up being displayed, and also the mechanism that would enable clicking the name and triggering the launching of the stream??

Thanks for your time either way! This program has made my life so much better and I can't thank you guys + the streamlink people enough for it existing :)

### Checklist
- [X] This is a feature request.

### Environment details
Operating system and version: win10 pro 64 bit
Streamlink Twitch GUI version: (newest as of Dec 6)
Streamlink version: (newest as of Dec 6)
Configuration details: irrelevant to post

**Comment by bastimeyer** [comment]
> make its data available

What you are looking for is direct access to Twitch API and not Streamlink Twitch GUI. The last time I've used Rainmeter was 10 years ago before I switched to Linux, so I don't know how this works, but I'm sure you're able to make simple https requests, parse JSON and iterate over the returned stream list. Check out the Twitch developer documentation if you want to know what needs to be done.

> it would open the stream using whatever settings are configured in the GUI

You can launch streams via a command line parameter in the Streamlink Twitch GUI. See the wiki for that.
