### ISSUE TITLE
Unauthorized to verify my email?

### ISSUE THREAD

**Issue by AkiraFenix** [streamlink/streamlink-twitch-gui#525]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [X] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

So, I _try_ to verify my E-mail, and it fails. Every. Single. Time.
The error message is this:
{"error":"Unauthorized","status":401,"message":"authentication failed"}

### Expected / Actual behavior

It's supposed to send an email to my gmail account with a link to verify my account, but inestead, it fails.

### Reproduction steps

1. I tried to chat in a streamer's stream chat, watching a tBoIA+ Stream in the Twitch app with dark mode on, and it said my E-mail isn't verified
2. It tells me to go to https://www.twitch.tv/settings/profile , and click Verify
3. AAAAAND it fails just like every other time i try to verify it
Error that it shows : {"error":"Unauthorized","status":401,"message":"authentication failed"}

### Environment details

Operating system and version: Windows 10
Streamlink Twitch GUI version: What even is Streamlink Twitch GUI? Does it matter when i have no games or never streamed?
Streamlink version: What even is Streamlink and does it even matter here?
Configuration details: The settings are pretty much the default ones but i use Dark Mode and use Friend Snyc.

...

### Comments, logs, screenshots, etc.

Here, actual step by step screenshots.
**
![image](https://user-images.githubusercontent.com/33667869/34540013-111bc4b6-f0ba-11e7-87d5-3becaa9bf9d8.png) Step 1 (Skipped once on twitch.tv/settings/profile)
![image](https://user-images.githubusercontent.com/33667869/34540036-2c5d3840-f0ba-11e7-8516-5f2d00b234bc.png) (Confirmar means Confirm/Verify) ((Step 2))
![image](https://user-images.githubusercontent.com/33667869/34540058-3a54f0be-f0ba-11e7-9f32-db92b30df639.png) (Step 3) Rince and repeat skipping step 1

**
ps nothing works on that page it just says i'm "unauthorized" to change my own account's settings, so might as well note that everything else on the page is broken.

**Comment by bastimeyer** [comment]
> What even is Streamlink Twitch GUI? Does it matter when i have no games or never streamed?
> What even is Streamlink and does it even matter here?

How about reading the readme before opening such an issue here?
https://github.com/streamlink/streamlink-twitch-gui

You're looking for the official Twitch desktop app...
Good luck
