### ISSUE TITLE
French translation

### ISSUE THREAD

**Issue by vic8200** [streamlink/streamlink-twitch-gui#528]
Let me know when i18n is done so i can start to work on the translation.

PS : Thank you Sebastian Meyer for the answer.

**Comment by bastimeyer** [comment]
I've rebased my previous work from April last year on the i18n branch to the head of the master branch. This is now up2date, but still requires a huge amount of work. You can subscribe to the pull request #529, so you can see the progress over there. But as I've mentioned on Gitter, don't expect me to finish this anytime soon. Thanks.

**Comment by vic8200** [comment]
I try my best to understand what you are trying to explain but it's hard xD Anyway , i have subscribed to #529 , waiting for news :')

**Comment by bastimeyer** [comment]
The i18n branch has been merged last week (#529), which means that if anyone wants to work on adding translations, it can be done now. I've also upgraded the wiki just now with a translation guide:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Translating
I hope it's not too complex, and if there's anything unclear, missing or wrong, please tell me, so it can be improved.

/cc @Caf 

Thank you

**Comment by vic8200** [comment]
I'll try , if i have any questions stay tuned ;)
