### ISSUE TITLE
Authentication failing when trying to do anything in the settings page.

### ISSUE THREAD

**Issue by AkiraFenix** [streamlink/streamlink-twitch-gui#531]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first. (There isn't anything about this in the wiki.)
- [X] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

As i said, when i try to do anything at all in my Twitch.tv profile settings, it just gives me an error saying that it failed the authentication. I'm posting this again since the first time i posted this and god the issue closed i were left with NO SOLUTION whatsoever.

...Almost as if noone cared about an account problem.
Im pretty sure this is only happening to me for no reason.

### Expected / Actual behavior

When clicking on the Verify button to verify my email by sending an email to my gmail account
...

### Reproduction steps

1. Go to https://www.twitch.tv/settings/profile
2. Click anything there
3. Fail
4. RINCE AND REPEAT skipping step 1.

### Environment details

Operating system and version: Windows 10 (Normal. not Redstone)
Streamlink Twitch GUI version: ?
Streamlink version: ?
Configuration details: Does this matter?

...

### Comments, logs, screenshots, etc.
![image](https://user-images.githubusercontent.com/33667869/35108071-b8d6577a-fc59-11e7-8dcc-2ed15921e27f.png)
![image](https://user-images.githubusercontent.com/33667869/35108123-d7ad659e-fc59-11e7-915c-11c7833a0366.png)
....

**Comment by BradyThe** [comment]
☒ I understand the difference between Streamlink Twitch GUI and TwitchTV.

This has nothing to do with **Streamlink Twitch GUI**, my man. Currently I am getting a similar error message. Twitch is probably feeling a little twitchy. It likes to do that, especially on the Settings pages.

Remember, when in doubt, blame Twitch.

**Comment by bastimeyer** [comment]
@AkiraFenix 
Why are you opening an issue again which is totally unrelated to this application? You are not even a user of this program. You don't even know what Streamlink Twitch GUI is or even what its purpose is.

You are having issues with the Twitch website, in your web browser, so what does Streamlink Twitch GUI have to do with it? Nothing. You're wasting my and others time - again. Stop it, or you'll get blocked from posting here.

I already told you last time to read the readme of this project, but you didn't do this.
