### ISSUE TITLE
Watch vod

### ISSUE THREAD

**Issue by Dhavih** [streamlink/streamlink-twitch-gui#533]
### Checklist

- [ ] This is a bug report.
- [x] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

...I want to watch VOD on Streamlink but i dont know do this. This VOD I want https://www.twitch.tv/videos/139928794. How do I watch this?

### Expected / Actual behavior

...

### Reproduction steps

1. ...
2. ...
3. ...

### Environment details

Operating system and version: ...Windows 7 SP1
Streamlink Twitch GUI version: ...Last
Streamlink version: ...Last
Configuration details: ...-

...

### Comments, logs, screenshots, etc.

...https://prnt.sc/i49j7o

**Comment by bastimeyer** [comment]
This is the **Streamlink Twitch GUI** repository, not **Streamlink**. This is also not a helping/advice forum or something of that kind, but an **issue/bug** tracker instead.

If you don't know how to use Streamlink, you should read its documentation here:
https://streamlink.github.io/

Regarding Twitch VODs in Streamlink Twitch GUI, there is already an existing issue thread:
#81 

Judging from your attached screenshot, which looks like Portuguese which I don't speak, you didn't install Streamlink correctly and your system is not able to find the Streamlink executable when you're entering the "streamlink" keyword. Again, see the Streamlink documentation for how to install Streamlink on Windows.
