### ISSUE TITLE
Copying channel url on offline channel gives 'undefined'

### ISSUE THREAD

**Issue by sadiablos** [streamlink/streamlink-twitch-gui#546]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

Copying channel url on offline channel gives string 'undefined'

### Expected / Actual behavior

Copying channel url should work the same for button aswell as for right click menu

### Reproduction steps

1. Go to any offline channel
2. Right click on thumbnail
3. Copy channel url
4. Paste anywhere 

### Environment details

Operating system and version: Win7 x64 
Streamlink Twitch GUI version: 1.4.1
Streamlink version: 0.9.0

### Comments, logs, screenshots, etc.

![stg](https://user-images.githubusercontent.com/24566138/37230109-95401576-23e6-11e8-8b34-47b924f494d4.png)
![stg1](https://user-images.githubusercontent.com/24566138/37230134-a0adf04a-23e6-11e8-9bbd-69109697a152.png)
![stg2](https://user-images.githubusercontent.com/24566138/37230140-a5158ed6-23e6-11e8-9197-04a3321b65ab.png)

**Comment by bastimeyer** [comment]
Thanks for reporting!
