### ISSUE TITLE
Popout window listing online followed streams (or other categories)

### ISSUE THREAD

**Issue by taalas** [streamlink/streamlink-twitch-gui#547]
Hi,

I would like to propose and additional window (possibly quite small and/or transparent) that can be configured to show a simple list of online followed streams (or other categories) which automatically updates automatically. This could be used as a desktop widget when one prefers not to have the main window opened while still being able to have an overview over the current stream options.

Thanks!

**Comment by bastimeyer** [comment]
Sorry for the late response...
I don't think that something like this belongs here into this app. If you need a desktop widget, overlay, or something of that kind, there are other solutions for that. For now, the notification system will tell you once a streamer you want to watch has come online.
