### ISSUE TITLE
Missing translation message (live streams)

### ISSUE THREAD

**Issue by MrLint** [streamlink/streamlink-twitch-gui#557]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] I tried solving my issue by reading the project's wiki first.
- [x ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
When there are no streams the live stream dialog shows a missing translation message.
...

### Expected / Actual behavior

I think this is meant to show no hosted streams?

### Environment details

Operating system and version: w10 x64 en-us
Streamlink Twitch GUI version: 1.5.0
Streamlink version: .11
Configuration details: All parts are using portable versions.

...

### Comments, logs, screenshots, etc.

![2018-04-25 09_43_22-streamlink twitch gui](https://user-images.githubusercontent.com/18565454/39250106-35ab3882-486e-11e8-97f0-9ceba21d5ff9.png)

**Comment by bastimeyer** [comment]
Thanks, @MrLint...
This was caused by an unnoticed typo in the localization key `routes.user.followedStreams.empty.streams` (a0b534f0ff9c7fba516a9ddb6ed6eb48dffaf223).
