### ISSUE TITLE
New icon?

### ISSUE THREAD

**Issue by emilweth** [streamlink/streamlink-twitch-gui#558]
Hi there,

This is an open suggestion for finding a new system tray icon / streamlink-twitch-gui logo
No real issues,  just a practical problem : I use both twitch/curse app, and streamlink-twitch-gui and this happens : 
![system tray screenshot](https://user-images.githubusercontent.com/7402764/39340662-aa796cb2-49cf-11e8-8efd-16151cf1f853.png)

Maybe think of a simple recolor to begin ?

**Comment by MrLint** [comment]
What are the bitmap sizes that need to be generated?

**Comment by bastimeyer** [comment]
This depends on the target OS and their use case:

- **App icons**
  - **Windows**
    16, (24), 32, 48, (64), (128) and 256 in a single `ico` format  
    Requires Inkscape, Gimp, Photoshop or NodeJS modules (**\***).
  - **macOS**
    16, 32, 64, 128, 256, 512, 1024 in a single `icns` format  
    Requires special dependencies, eg. `icnsutils` on a Ubuntu build machine like TravisCI or special apps on macOS (proprietary bullshit) (**\***).
  - **Linux**
    A single (`svg`), or `png`s for 16, (24), 32, 48, 64, 128, 256, (512)  
    These are added to the `hicolor` freedesktop icon theme, but DEs can and will use the icons of the currently used theme set by the user. `hicolor` is the ultimate fallback theme. (**\***)
- **Tray bar icons**
  - **Windows**
    16, 16@2x, 16@3x (hi-dpi scaling)  
    Currently uses colored png icons, which isn't ideal on Windows 8+ where monochrome icons are preferred. A fix is quite simple. Another option could be giving the user a choice.
  - **macOS**
    18, 18@2x, 18@3x  
    Special monochrome png icons with a black mask. Currently not as crisp as they should be, because they got scaled down from the original Twitch icon, making them a bit blurry (both bicubic and lanczos). New icons should be created with monochrome versions and their crispness in mind.
  - **Linux**
    16@3x, 16@3x, 16@3x  
    Originally, the same scaling was used as on Windows, but since there's no strict layout on Linux DEs, I decided to use the one with the highest res on all DPI scaling factors, as most DEs are able to properly scale the tray bar icons. On KDE Plasma, this doesn't work and needs to be fixed. I didn't notice that until recently.  
    In the last couple of days, I've written and published a NodeJS module for figuring out the icon paths on Linux for a given icon theme name. In addition to another module for figuring out the icon theme name (which I am still working on), static tray bar icons on Linux will be gone and the ones of the current theme can be used.


Back to your question... The actual bitmap sizes are not really important. These can be created quite easily from a proper vector graphic.

(**\***) Ideally, this should be done during the webpack/grunt build/compile steps via [`Sharp`](https://github.com/lovell/sharp/), [`to-ico`](https://github.com/kevva/to-ico) and `icnsutils`. The icon sizes mentioned above in parenthesis are currently not being used.

**Comment by FoxBJK** [comment]
Twitch has all of their assets available for download here:
https://www.twitch.tv/p/brand/

Definitely agree that this app needs a different icon. Maybe just use the white or black one that Twitch provides, and put it on a different color background?

**Comment by KaXaSA** [comment]
<img src="https://user-images.githubusercontent.com/6237603/81514071-5183d280-9303-11ea-8129-5638c00b3f12.png" width="64" height="64">

There are some other (similar) suggestions in the [SVG file](https://drive.google.com/file/d/1CnjdTLuvtU_VSgxC8oKkIcMwJNr7aNIj/view?usp=sharing).
I'm not sure if it will look great as a tiny icon but maybe someone else can improve it.

**Comment by bastimeyer** [comment]
Thanks for the logo suggestions, @KaXaSA.

I don't think though that it's possible to modify the Twitch "Glitch" icon in that way. See Twitch's trademark guidelines:
https://www.twitch.tv/p/legal/trademark/

> Don’t modify or alter Twitch Brand Assets in any way, such as changing the color or design of our logos, app icons, or screen shots. Please refer to the brand assets page.

**Comment by scowalt** [comment]
Logo idea I had. I think it looks okay in the smaller sizes, and it should follow Twitch's branding guidelines just fine

![Untitled](https://user-images.githubusercontent.com/1100550/103431703-5a266300-4b89-11eb-9dd5-db3e70a995bd.png)
![small](https://user-images.githubusercontent.com/1100550/103431705-5e528080-4b89-11eb-863a-49b775158511.png)
![smallest](https://user-images.githubusercontent.com/1100550/103431704-5c88bd00-4b89-11eb-96f0-70ea4bea2770.png)

**Comment by bastimeyer** [comment]
The problem with this is that the tray icon is barely recognizable (the tray icon is even smaller than the smallest icon you've posted on `@1x` DPI scaling - 16x16 px). And then there are also monochrome tray icons, making this even more difficult. Also the badge overlay (on supported OSes) which show the number of live followed channels.

The best solution would probably be using the streamlink logo and adding the Twitch logo "eyes" to it, but it's possible that this would fall into the twitch logo modification category.
