### ISSUE TITLE
Enabling "Close stream popup" also closes popups on error

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#560]
### Checklist

- [x] This is a bug report.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
When the player streamlink-twitch-gui would like to launch isn't here, it silently fail.

### Expected / Actual behavior

It shouldn't silently fail, and should even fallback to another one if available.
Player list should be cleaned from unavailable players, default should be moved to an existing one, and anyway in the worst case there should at least have a test the player is running and an error displayed to the user.

### Reproduction steps
1. At basis, computer had both VLC and MPV present. None was explicitely picked in settings, it was on "no preset". Application therefore show it defaults to VLC.
2. Uninstall vlc from your computer.
3. streamlink-twitch-gui is still defaulting on VLC **even if it was restarted**
4. Launch a stream, everything act as usual, excepted than player never launch.

### Environment details

Operating system and version: Archlinux
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.11

...

### Comments, logs, screenshots, etc.

...

**Comment by bastimeyer** [comment]
Same reason as described in #559.
The Twitch GUI doesn't know which player is being launched, since no player profile has been selected. Since Streamlink is launching the player and not the Twitch GUI, all it can do is reacting to Streamlink's output, which is being done here:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.5.0/src/app/services/StreamingService/errors.js#L31-L35

If you're selecting a player profile, the defined player executable path (or the list of fallback paths) is being resolved first before launching the stream:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.5.0/src/app/services/StreamingService/player/resolve.js

See the Twitch GUI's log file for that:
```
streamlink-twitch-gui --loglevel debug
cat /tmp/streamlink-twitch-gui/logs/*
```

**Comment by Porkepix** [comment]
If I understand correctly your comment, especially first code link, then it should show an error message stating the player isn't here by reading streamlink's logs? Because currently it doesn't.

**Comment by bastimeyer** [comment]
Do you have a modified Streamlink config file or have you set custom Streamlink parameters in the Twitch GUI?
Can you post the entire stdout and stderr of Streamlink when you run this?
```
$ streamlink -l debug twitch.tv/CHANNEL best
```
Since you don't have VLC installed, it should print the same error message...

**Comment by Porkepix** [comment]
If I run it in the terminal, I get the line
```
error: The default player (VLC) does not seem to be installed. You must specify the path to a player executable with --player.
```
I have no streamlink configuration file at all.

I have set a few options for GUI, but really not much. No idea about how to give a diff between what changed and the defaults though: it doesn't seem to store only changed values.

**Comment by bastimeyer** [comment]
> I have no streamlink configuration file at all.

Is the Twitch GUI launching the same Streamlink you're launching via the shell? Meaning, have you set custom streaming provider paths in the Twitch GUI and are by accident using a different Streamlink?

Other than that, I don't know why this error shouldn't pop up.

Please launch the Twitch GUI with the `--loglevel debug` parameter and post the log here. The log files are in the `/tmp/streamlink-twitch-gui/logs/` directory (not ideal on Linux and still needs to be changed, btw). Don't forget to remove any private strings like access tokens, etc. when you're posting the content of the log file.

**Comment by Porkepix** [comment]
Okay, so:

Terminal contain (cleaned a bit)
```
[debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": false,
    "version-check": false,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
[21639:21639:0501/235041.300998:ERROR:browser_main_loop.cc(292)] GLib-GObject: g_object_unref: assertion 'G_IS_OBJECT (object)' failed
[debug][StreamingService]
Preparing to launch stream
{
}
[debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": null,
        "params": null,
        "pythonscript": null
    }
}
[debug][StreamingService]
Found streaming provider
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/bin/streamlink"
    ],
    "env": null
}
[debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/bin/streamlink",
        "--version",
        "--no-version-check"
    ],
    "env": null
}
[debug][StreamingService]
Validated streaming provider
{
    "version": "0.11.0"
}
[debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/bin/streamlink",
        "--http-header",
        "Client-ID=",
        "--no-version-check",
        "--twitch-disable-hosting",
        "--twitch-oauth-token",

        "--hls-live-edge",
        "3",
        "--hls-segment-threads",
        "1",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/chess",
        "best"
    ],
    "env": null
}
[error][StreamingService]
Error: error: The default player (VLC) does not seem to be installed.
{
}

```
Then there are two log files, the first one contain
```
[2018-05-01T20:32:50.418Z][error][StreamingService]
Error: error: The default player (VLC) does not seem to be installed.

[2018-05-01T20:33:07.448Z][error][StreamingService]
Error: error: The default player (VLC) does not seem to be installed.

[2018-05-01T21:21:55.756Z][error][StreamingService]
Error: error: The default player (VLC) does not seem to be installed.

[2018-05-01T21:23:22.068Z][error][StreamingService]
Error: error: The default player (VLC) does not seem to be installed.
```
While the other one actually contain exactly my first paste from terminal.

And no, I've no other streamlink installation nor I have messed with this.

As you can see, it's aware of the missing VLC, but still not showing me the popup in the GUI :/

**Comment by bastimeyer** [comment]
I know why this isn't working... Do you have the "Close stream popup" option set at the bottom of the "Streams" settings menu?

There seems to be an issue with the behavior of popups when the stream launch attempt has failed and the option has been enabled. I'll investigate this tomorrow...

**Comment by Porkepix** [comment]
Yeah, you found the culprit. Disabling it indeed shows the error.
I thought to such issue but got confused and mixed it up with the "Do not close the player" option when testing, my bad.
