### ISSUE TITLE
Is there any way to block a stream from showing up in the streams list?

### ISSUE THREAD

**Issue by xaxxon** [streamlink/streamlink-twitch-gui#564]
### Checklist

- [] This is a bug report.
- [X ] This is a feature request.
- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] I tried solving my issue by reading the project's wiki first.
- [X] I have read the contribution guidelines und used the search function to find already existing threads.

### Description
I would like to be able to block a stream from showing up in the all streams list.

### Expected / Actual behavior

 I could go under settings and set a regex for streams not to show.  Then it wouldn't show that stream anywhere ever.
...

### Comments, logs, screenshots, etc.
Thank you.

**Comment by bastimeyer** [comment]
Sorry, but any kind of client side filtering, especially via loose user settings like a regex, won't be implemented. This has been asked for so many times, but the idea of client side filtering is just bad and most of the time, the people requesting it haven't made any further thoughts about the implications of it.

If streams could be filtered on the side of Twitch, via API request parameters or via user profile settings, there would be no reason to not implement such kind of feature, but you can't do this. See my comment from an older thread here why client side filtering is bad:
https://github.com/streamlink/streamlink-twitch-gui/issues/151#issuecomment-183581175
This was regarding language filtering though, which wasn't working properly back then, but the idea is the same and the point still stands.
