### ISSUE TITLE
Python executables not Found.

### ISSUE THREAD

**Issue by h3x1e** [streamlink/streamlink-twitch-gui#569]
*Thanks for reporting an issue!*
*Please read the contribution guidelines first! (see the link above)*

*Feel free to use the following template. Be as detailed as possible.*
*Please see the text preview to avoid unnecessary formatting errors.*
*Don't forget to remove this text before submitting.*

----

### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Couldn't Find python script
Executables were not found

Please check your settings and / or reinstall

### Expected / Actual behavior

Stream to open when clicked on.

### Reproduction steps

1. Click Stream, wont launch.
2. ...
3. ...

### Environment details

Operating system and version: ...
Streamlink Twitch GUI version: ...
Streamlink version: ...
Configuration details: ...

...

### Comments, logs, screenshots, etc.

Tried manually inputting pythonw.exe paths for both Python 2.7 and 3.6 nothing works still get the same error.

**Comment by bastimeyer** [comment]
Did you follow the wiki while installing Streamlink and Streamlink Twitch GUI?
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration

Your issue doesn't include any further information, so there's no chance of anyone to help you. There is a reason why the issue template exists.

**Comment by h3x1e** [comment]
Fixed it myself, no need for the attitude.
