### ISSUE TITLE
401 forbidden when on ubuntu

### ISSUE THREAD

**Issue by campones** [streamlink/streamlink-twitch-gui#574]
- [ x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

When I try to restream an iptv channel, a demo link that is supposed to work only on vlc (I setup user agent vlc), then I tried on the shell of my ubuntu server, and I get a 401 client forbidden. While doing the same with the windows run command, it works just fine. 

` streamlink "httpstream://http://xxx.ts" best --http-header "User-Agent=VLC media player - version 0.7.0 Bond - (c) 1996-2003 VideoLAN"-O | /usr/local/bin/ffmpeg -re -i pipe:0 -c:v copy -c:a libfdk_aac -f flv "rtmp://stream.vkuserlive.com:443/live?srv=xxxxx"
`
`(401 Client Error: Unauthorized for url: h`

Is there anything I can do to use that link from a linux server?

**Comment by bastimeyer** [comment]
Wrong repo...
https://github.com/streamlink/streamlink/issues
