### ISSUE TITLE
When browsing by game, only the first few streams listed have that game set

### ISSUE THREAD

**Issue by undeference** [streamlink/streamlink-twitch-gui#575]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

When browsing Twitch streams by game, only the first page of results is for the correct game

### Expected / Actual behavior

All streams listed should have the stream game set to the game searched

### Reproduction steps

1. Select "Games"
2. Pick any game with more than one page of results
3. Scroll down ("game" query parameter is missing from XHR URI)

### Environment details

Operating system and version: Fedora release 28 (Twenty Eight), 4.16.14-300.fc28.x86_64
Streamlink Twitch GUI version: built from a local branch merging nwjs-0.31 and master@4425206 (11 June 2018)
Streamlink version: 0.6.0

**Comment by bastimeyer** [comment]
Thanks for reporting!

**Comment by undeference** [comment]
I can still reproduce this after c42f06a

**Comment by bastimeyer** [comment]
Can you give a couple of more details please?
Are you running the latest build?

The HTTP requests made by the infinite scroll mechanism are now correctly including the game parameter in the GamesGameRoute, eg:
```
initial:
https://api.twitch.tv/kraken/streams?broadcaster_language=de%2Cen&game=Dota%202&limit=12&offset=0&_=1528828788242

first scroll event:
https://api.twitch.tv/kraken/streams?broadcaster_language=de%2Cen&game=Dota%202&limit=12&offset=12&_=1528828788244

second scroll event:
https://api.twitch.tv/kraken/streams?broadcaster_language=de%2Cen&game=Dota%202&limit=12&offset=24&_=1528828788245
```

**Comment by undeference** [comment]
Ok, apparently I had a broken script. It's fixed.
