### ISSUE TITLE
Communities access under “my“ section

### ISSUE THREAD

**Issue by atwak** [streamlink/streamlink-twitch-gui#579]
### Checklist

- [x] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.

### Description

Can be the subscribed “communities” list be available under “my” section?

**Comment by bastimeyer** [comment]
I don't know how I feel about adding more stuff which isn't officially supported. For now, I won't add more stuff, but I will re-consider this when I'm going to upgrade to the new Twitch API later this year.
I have summed up the whole Twitch API situation recently, see here:
https://github.com/streamlink/streamlink-twitch-gui/issues/549#issuecomment-375975415

**Comment by bastimeyer** [comment]
Communities are now a deprecated feature on Twitch...
https://blog.twitch.tv/introducing-tags-and-new-categories-33744ef7b04f
