### ISSUE TITLE
"write" text for initial issue post requests

### ISSUE THREAD

**Issue by atwak** [streamlink/streamlink-twitch-gui#580]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] I have read the contribution guidelines und used the search function to find already existing threads.

### Description

The following text – "I have read the contribution guidelines und used the search function to find already existing threads." – has “und” instead of “and“ (which makes sense in a german way).

You can possibly change three dots for input sections change for ellipsis (i.e. – “...” and “…", first is three symbols, second is one). Which is typographically natural, and easier to delete.

**Comment by bastimeyer** [comment]
> und

Damn, that typo has survived for almost a year now without being noticed. Good find! :smiley: 
3a906938d2eddf4fc1fb8cbc30eb32a13482f87a
Do you want to send a quick PR?

> three dots

The issue with using special characters like this is that you have to be sure that they get rendered correctly on each user's system. The unicode character for `…` is U+2026, so this shouldn't be too much of a big concern and should work. However, three simple dots will always work. You'll never know when using special characters. Send a PR.

**Comment by atwak** [comment]
I’m not proficient with github, it might be easier to do for you, though I’m eager to learn.
I see, however that the issue is closed, so that might mean it’s done.
Thank you for listening.
