### ISSUE TITLE
Couldn't launch a stream (invalid version check output) 

### ISSUE THREAD

**Issue by adrianmak** [streamlink/streamlink-twitch-gui#581]
Windows 10 x64 OS

There is no other python binary search path in PATH env variable

I use the streamlink portable version.  It is working fine standalone.

![baidushurufa_2018-6-20_8-50-45](https://user-images.githubusercontent.com/1168716/41631432-2d646a02-7467-11e8-9ce2-84fb0e1335fe.png)
![baidushurufa_2018-6-20_8-50-55](https://user-images.githubusercontent.com/1168716/41631438-310fc4d0-7467-11e8-82b0-09afe2fce554.png)

**Comment by kyle-miller** [comment]
I had the same issue on Ubuntu 18.04 starting this morning; it worked fine last night. I was able to fix it by switching from `python` to `python3` in the Python Executable section of the Streaming tab. This doesn't appear to be your direct issue, but I hope it helps troubleshooting.

**Comment by bastimeyer** [comment]
@adrianmak 
What is the output when you run this from the Windows CMD shell?
```
"F:\Streamlink_For_Windows_Portable_v0.13.0\Python 3.6.3\pythonw.exe" "F:\Streamlink_For_Windows_Portable_v0.13.0\Streamlink\Streamlink.py" --version
```

**Comment by adrianmak** [comment]
@bastimeyer 

empty


![baidushurufa_2018-6-23_16-17-24](https://user-images.githubusercontent.com/1168716/41807375-f7c124ca-7700-11e8-861b-a57648ce9526.png)

**Comment by bastimeyer** [comment]
Can you please try the regular Streamlink installation? I am not familiar with Streamlink portable and it often times as some silly issues. If you're using the Streamlink installer, it'll add Streamlink's install dir to the system's `PATH` env var and you don't need to specify any custom paths in the Twitch GUI.

**Comment by back-to** [comment]
the portable streamlink **version** is not valid for

https://github.com/streamlink/streamlink-twitch-gui/blob/54a2284ae77f9e4b3233dd64c52be2e257d61773/src/config/streaming.json#L14-L16

because it replaces the version, instead of building it.

```
Streamlink.exe 0.13.0@aee0b9e
```

https://github.com/streamlink/streamlink-portable/commit/a1699d9706c915ef9139ec30e3597bb47f20055b

**Comment by bastimeyer** [comment]
This should be fixed in Streamlink portable now:
streamlink/streamlink-portable#26

Download the latest version and rebuild it. Or just use the regular way of installing Streamlink.
