### ISSUE TITLE
no longer works

### ISSUE THREAD

**Issue by lextra2** [streamlink/streamlink-twitch-gui#586]
When I open the streamlink-twitch-gui I get this screen
https://i.imgur.com/QLT3mqC.png
Still worked just yesterday. I'm using this release
https://github.com/streamlink/streamlink-twitch-gui/releases/download/v1.5.0/streamlink-twitch-gui-v1.5.0-win32.zip

**Comment by bastimeyer** [comment]
This looks like it's an issue with the config/cache folder of NW.js.
Probably the same as #487.

Please try and delete the `%LOCALAPPDATA%\streamlink-twitch-gui` folder.

**Comment by lextra2** [comment]
Apparently it is a network routing issue with the VPN I had on at the time. Turning the VPN off and restarting my pc fixed the issue.
