### ISSUE TITLE
Stream won't start in macOS Mojave

### ISSUE THREAD

**Issue by Germanko** [streamlink/streamlink-twitch-gui#587]
In macOS 10.14 PB1 I cannot start stream. When I launch it, it immediately crashes the VLC player. I can manually start stream from streamlink command line.

**Comment by bastimeyer** [comment]
What do you mean with it crashes the VLC player? So is it a VLC issue then?
Are you using the same Streamlink parameters from the shell which the Twitch GUI is using/generating? What is the log output? Check the `$TMPDIR` (or `$HOME/Library/Logs` if you're using a newer (development) version than `1.5.0`)

**Comment by Germanko** [comment]
I was assuming it would be GUI issue because I was able to start stream from command line with same parameters, but I could be wrong. Yes, I tried using same arguments in cmd and it started just fine. I am using latest release (1.5.0). And I couldn't find any log outputs I checked both directories but found none.

**Comment by bastimeyer** [comment]
Please try using the `--loglevel debug` Twitch GUI parameter and check the log file directory again:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel
You will find the generated Streamlink parameters and the resolved Python executable and Streamlink script path in this file. The Streamlink output itself should be displayed by the Twitch GUI in the stream popup, though.

**Comment by Germanko** [comment]
Ok, sorry for the delay. Today I just found out that the crash is probably caused by NodeJS package not GUI. I am sorry for delay and false report.

**Comment by bastimeyer** [comment]
ok, np
