### ISSUE TITLE
"Unexpected version check output" with the new Streamlink Ubuntu Package

### ISSUE THREAD

**Issue by Randommer** [streamlink/streamlink-twitch-gui#589]
### Checklist

- [x] This is a bug report.
- [ ] This is a feature request.
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] I have read the contribution guidelines and used the search function to find already existing threads.

### Description

Streamlink Twitch GUI don't want to launch a stream, I have an "Unexpected version check output" error, since Streamlink was updated in WebUpd8 PPA.

### Expected / Actual behavior

Streamlink Twitch GUI should launch a stream.

### Reproduction steps

1. I launch Streamlink Twitch GUI
2. I try to launch a stream
3. I get "Unexpected version check output"

### Environment details

Operating system and version: Ubuntu MATE 17.10/18.04
Streamlink Twitch GUI version: 1.5.0
Streamlink version: 0.10.0 from the Ubuntu 18.04 repository and 0.14.2 from WebUpd8 PPA (Bionic and Artful)
Configuration details: OS 32 bit/64 bit

### Comments, logs, screenshots, etc.

I usually use Streamlink from WebUpd8 PPA but when I got the error the first time, I did go back to the Streamlink package in the official repository.
On the same computer (the 32 bit one) I run Streamlink Twitch GUI 1.5.0 and Streamlink 0.14.2 on Windows without problems.
On both computers, I can launch a stream with Streamlink 0.10.0 or 0.14.2 in a terminal without issues.

**Comment by bastimeyer** [comment]
That's a resolver issue in the Twitch GUI. It's using `/usr/bin/python` which symlinks to python2.7 on Ubuntu, but the Streamlink package requires python3.

In order to manually fix it for now, set the python executable to `python3` or `/usr/bin/python3` in the streaming settings menu.
