### ISSUE TITLE
v1.6 Flagged as Ransomware in Malwarebytes

### ISSUE THREAD

**Issue by Bullet25fxbx** [streamlink/streamlink-twitch-gui#592]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
V1.6.0

**Streamlink version:**  
V0.14.2

### Description

Malwarebytes flaggs V1.6 as ransomware.

### Expected / Actual behavior

No be flagged as ransomware.

### Additional comments, screenshots, etc.
![ransomware](https://user-images.githubusercontent.com/20262825/43661722-522b24c4-9731-11e8-85f4-cd09480b3b3a.PNG)

**Comment by bastimeyer** [comment]
False positive... Report this to the developers of this "anti-malware" software if you want, I can't do anything about this.

Related: https://github.com/streamlink/streamlink-twitch-gui/issues/455#issuecomment-302890251
https://travis-ci.org/streamlink/streamlink-twitch-gui/builds/410895637
