### ISSUE TITLE
Notifications do not display on Windows Preview Buiilds.

### ISSUE THREAD

**Issue by Xesyto** [streamlink/streamlink-twitch-gui#594]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 Build 17728.r5_release_180727-1712

**Streamlink Twitch GUI version:**  
Streamlink Twitch GUI 1.6.0

**Streamlink version:**  
streamlink-script.py 0.13.0

**Configuration details:**  
https://i.imgur.com/57sjRwl.png

### Description

On the last few months of windows preview and version 1.5 and 1.6 of Streamlink Twitch GUI notifications do not work. Selecting growl or windows notifications manually does not make a difference. Running Streamlink Twitch GUI as Administrator also makes no difference. 

I don't expect perfect results when using what is known to be a beta version of windows, however this bug has been present for long enough that I suspect it will continue into the next major windows 10 update. 

This does not seem to be an across the board problem for third party applications, for instance Discord displays notifications as normal. 

### Expected / Actual behavior

Regardless of windows version notifications should display when triggered as configured or when someone presses the Test Notification button. 

### Reproduction steps

1. Install and fully update Windows 10 Preview, either the Slow or Fast ring
2. Install Streamlink Twitch GUI 
3. From the Notifications tab in the settings menu press Test Notification observe no Notification
4. Try both Windows toast notifications and Growl notifications instead of Automatic selection, observe no Notification on any of these options.

### Log output
1. Started Streamlink Twitch GUI with debug level logging
2. Opened the Settings Menu, opened the Notifications tab
3. Pressed Test notification once
4. Checked Windows toast notifications, clicked apply
5. Pressed Test notification twice
6. Checked Growl Notifications, clicked apply
7. Pressed Test notification twice

https://gist.github.com/Xesyto/3442f217edbd8230d7c4e68d61034b09

### Additional comments, screenshots, etc.

As this is as preview build of windows I'm not particularly upset when bugs or weird interactions occur, however this has been broken for months now over multiple builds both in the slow and fast ring. I believe it is likely that this issue will carry over to the next normal major window 10 update.

**Comment by bastimeyer** [comment]
Do you have notifications enabled in your system settings / control center? See the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications#toast-notifications-windows-8

The Windows Toast Notifications are being created/shown by [SnoreToast](https://github.com/bastimeyer/snoretoast/tree/binaries), a third party program which is included in Streamlink Twitch GUI on Windows. These notifications also require a special start menu shortcut which includes the application ID string. If it is missing, notifications can't be shown, but SnoreToast should always try to create one initially. These are the two dependencies, notifications have to be enabled on your system (which can be set for each registered application) and the special startmenu shortcut needs to exist.

As you can see in the logs, there are no errors being reported, which would be the case if something went wrong.
- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/services/notification/providers/snoretoast.js#L40-L64
- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/services/notification/providers/snoretoast.js#L66-L117

Disabled notifications in the system settings don't yield any errors on the client side, so this might be the reason for this. If it's not, then it has to be an issue of SnoreToast itself, or your system / system configuration. However, I doubt that MS would introduce any breaking changes in their notification API. If they did, you could try and debug this by using SnoreToast yourself.
https://github.com/bastimeyer/snoretoast/tree/binaries

If you're trying to use Growl notifications instead, you need to have Growl installed and running on your system.

**Comment by mepherion** [comment]
I had the same issue and I had to delete the existing start menu shortcut and let SnoreToast recreate it:

1. Delete the existing Streamlink Twitch GUI shortcut under `%appdata%\Microsoft\Windows\Start Menu\Programs`
1. Relauch Streamlink Twitch GUI
1. Open Streamlink Twitch GUI Settings -> Notifications and test the notification. The Windows notification should show now
1. Sometimes you may need to adjust the Windows Settings for it under Settings -> System -> Notifications & actions -> Streamlink Twitch GUI

**Comment by bastimeyer** [comment]
It's possible that the app-id of the shortcut was changed, which caused the notifications to fail. However, this is not Streamlink Twitch GUI's fault and can only be fixed by SnoreToast.
