### ISSUE TITLE
Channel settings not saving

### ISSUE THREAD

**Issue by djkirbee** [streamlink/streamlink-twitch-gui#595]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Windows 10 Pro v1083

**Streamlink Twitch GUI version:**  

1.6.0 x64

**Streamlink version:**  

0.14.2

### Description

Channel settings aren't saved. When checking off per-channel quality, desktop notifications and etc and trying to apply, settings appear to be saved but when switching from something back to channel settings, the settings are all back to default. I thought maybe it would save if I ran the program as admin but I got the same results. I've tried mixing and matching various settings and some appeared to have saved but didn't actually after I re-opened the program.

### Expected / Actual behavior

Channel settings should be saved but they aren't.

### Reproduction steps

1. Click on a channel to bring up channel info
2. Check whatever and apply settings.
3. Switch to another tab then back to channel settings.
4. Settings are wrong or only some have "saved."
5. Restart program.
6. Go back to channel settings.
7. All settings are back to default and nothing has changed.

### Log output

```
[2018-08-31T01:48:21.024Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2018-08-31T01:48:33.117Z][error][Application]
Error: Attempted to handle event `didSetProperty` on <channelSettings:finestko> while in state root.empty. Called with {name: streaming_quality, oldValue: undefined, originalValue: undefined, value: null}.

[2018-08-31T01:48:43.848Z][error][Application]
Error: Attempted to handle event `didSetProperty` on <channelSettings:finestko> while in state root.empty. Called with {name: streaming_quality, oldValue: null, originalValue: undefined, value: medium}.
```

**Comment by bastimeyer** [comment]
Thanks for reporting... I'll take a look at it when I get the time. There might be an unnoticed issue regarding EmberData and the state of the channel settings records.

**Comment by Stoofoo** [comment]
I have the same issue. Attempted to save settings for a channel and the settings appear to save after mashing the "Apply" button, then going into another tab and back into the Settings. But after exiting Streamlink Twitch GUI and starting it up again, the settings for that individual channel are gone.

**Comment by tr37ion** [comment]
Same here. The channel settings are no more persistent and clicking the `desktop notifications` doesn't save the channel in `channel list` anymore. This was quite handy as that way you had at least bookmarks of channels you like even without signing in.

Additionally, it would be nice if one could set a time frame for requesting if channels from the list are on or offline without signing in.
