### ISSUE TITLE
category and stream tags

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-twitch-gui#597]
### Feature request

Category and stream tags are a new feature which was introduced yesterday:
https://blog.twitch.tv/introducing-tags-and-new-categories-33744ef7b04f

----

I will take a look at adding new features like this after migrating to the new Twitch API, which has to be done until the end of the year, as we are still using v5 here.

Related post to the API migration:
https://github.com/streamlink/streamlink-twitch-gui/issues/549#issuecomment-375975415

**Comment by m4gnify** [comment]
Just curious, is there any news on this topic?

**Comment by bastimeyer** [comment]
See #856
