### ISSUE TITLE
Accessibility Access request

### ISSUE THREAD

**Issue by ghost** [streamlink/streamlink-twitch-gui#598]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
macOS 10.14

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
0.14.2

**Configuration details:**  
-

### Description
macOS window shows up when launching stream:

"Accessibility Access (Events)
"Streamlink Twitch GUI" would like to control this computer using accessibility features.
Grant access to this application Security and Privacy preferences, located in System Preferences."

### Expected / Actual behavior
The window shouldn't show up

### Reproduction steps
Start a stream

### Additional comments, screenshots, etc.

If it's an expected behavior, why does the software needs this access?

**Comment by skulblakka** [comment]
I can not confirm this. The window did not pop up for me and Streamlink-Twitch-GUI is not listed under Privacy->Accessibility in system preferences.


Streamlink: 	0.14.2
maxOS:		10.14 (Mojave)
GUI:			1.6.0 (installed via brew)

**Comment by stevek123** [comment]
I reinstalled the computer, installed streamlink, streamlink twitch GUI and VLC all via brew, and it still happens.
