### ISSUE TITLE
VLC - Your input can't be opened VLC is unable to open the MRL

### ISSUE THREAD

**Issue by stevek123** [streamlink/streamlink-twitch-gui#600]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
macOS 10.14

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
0.14.2

### Description

When I open a stream in VLC from the GUI, the stream starts to play, but there is an additional item before that which results in the following error popup:

Your input can't be opened
VLC is unable to open the MRL 'file:///Applications/Streamlink%20Twitch%20GUI.app/Contents/Resources/app.nw/false'. Check the log for details.

### Expected / Actual behavior

It shouldn't try to play "false"

### Reproduction steps

Install streamlink, streamlink twitch gui and vlc via brew

### Log output

```
Your input can't be opened
VLC is unable to open the MRL 'file:///Applications/Streamlink%20Twitch%20GUI.app/Contents/Resources/app.nw/false'. Check the log for details.
```

### Additional comments, screenshots, etc.

Streamlink, Streamlink Twitch GUI and VLC were installed via brew

**Comment by bastimeyer** [comment]
Thanks for the report.

Looks like there's a problem in VLC's parameter definition list and how these parameters get validated. This `false` VLC parameter comes from the [`--no-one-instance`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/config/players.json#L29) parameter definition, which has to be disabled on macOS, as VLC doesn't support this on macOS (#354). In combination with the default user settings which enable this parameter (even if it's [hidden in the settings menu on macOS](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/ui/routes/settings/player/controller.js#L35)) and a [check against a `null` value](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/services/streaming/player/resolve.js#L124) in the StreamingService's player resolver, this `false` value gets used as a string in the VLC parameter list. This is a bug.

Btw, you can see which parameters were used by launching the Twitch GUI with the `--loglevel debug` parameter. On macOS, you can do this by running `open "/Applications/Streamlink Twitch GUI.app" --args --loglevel debug`.

**Comment by stevek123** [comment]
@bastimeyer Will there be a new release anytime soon?

**Comment by bastimeyer** [comment]
I'm looking into upgrading the used NW.js version first, but I haven't had much time working on it, so I don't know when another release will be published.
Just build the app yourself from the master branch until then.
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building
