### ISSUE TITLE
Unable to open Games tab or use the search bar

### ISSUE THREAD

**Issue by WintersunMark** [streamlink/streamlink-twitch-gui#602]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
0.14.2

**Configuration details:**  
64 bit

### Description

Every time I try to open the Games tab I get "There was an error trying to display this page". Also I cannot search for anything on the search bar.

### Expected / Actual behavior

Games actually showing up and being able to use the search bar.

### Reproduction steps

1. ... I open the app
2. ... Try to switch from any tab to the Games tab
3. ... Get the same error every time (see screenshot below)

### Log output

I didn't quite understand how to use parameters.

### Additional comments, screenshots, etc.

![error](https://user-images.githubusercontent.com/44517297/47599887-196da680-d98e-11e8-9ad1-2cf5c9a663dd.jpg)

**Comment by bastimeyer** [comment]
> Error 400 Bad Request
> Malformed locale

See #448

**Comment by WintersunMark** [comment]
Wow, I did search for the same issue but couldn't find anything, I'll try that solution tomorrow.
