### ISSUE TITLE
Indicate if x86 or x64 version is used in About

### ISSUE THREAD

**Issue by Wiethoofd** [streamlink/streamlink-twitch-gui#606]
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description
There is currently no way to figure out the instruction set of the version of the app you are using.

In the *About* it only shows the current version, without x86 or x64 indication. Of course the 64-bit version simply won't start on an 32-bit OS and throw an error, but when doing an in-place upgrade for a portable version on a 64-bits OS you could be running either version without knowing for sure.

### Additional comments, screenshots, etc.
A *readme* or *version.txt* in the zip of portable downloads containing this info could also work.

There's also no indication of instruction set/version in the .dlls or .exe, which might help too.

**Comment by bastimeyer** [comment]
Thanks for the suggestion.
