### ISSUE TITLE
Support for player-internal Twitch.tv streaming

### ISSUE THREAD

**Issue by Doosty** [streamlink/streamlink-twitch-gui#608]
Hi, it would be awesome if Twitch GUI would support PotPlayerExtentions (https://github.com/23rd/PotPlayerExtentions). Its a Potplayer plugin that makes potplayer able to open twitch urls without the need for streamlink at all. Its a very good alternative to streamlink but it still needs to be paired with some kind of UI. I was thinking of writing a JS greasemonkey script that would open twitch streams from their website in potplayer, but i much prefer the streamlink-twitch-gui interface of browsing twitch. The workaround that kind of works for me is adding a custom parameter for Daum Potplayer - "https://www.twitch.tv/{name}". But i still gotta wait for streamlink to start up and only then it goes for the launching of potplayer with parameter. So it opens the stream first in streamlink and wastes time when the only thing it needs to do is open with custom parameter "PotPlayer.exe https://www.twitch.tv/{name}". 

Id love it if streamlink-twitch-gui would support PotPlayerExtentions as an option next to Streamlink / Livestreamer. Or something like a "PotPlayerExtentions streaming" checkbox when i select Daum Potplayer as my player and it would disable running of streamlink since its unneeded. Thanks.

**Comment by bastimeyer** [comment]
I answered a similar question on Gitter roughly a month ago:
https://gitter.im/streamlink/streamlink-twitch-gui?at=5bba514ec7bf7c3662ce6727

I'll tag this as a feature request, but don't expect it to be happening any time soon (or at all)...

**Comment by esotericDisciple** [comment]
Problem is, no ad-blocking twitch player offers VOD support either
