### ISSUE TITLE
Conditional Notifications

### ISSUE THREAD

**Issue by Haukinger** [streamlink/streamlink-twitch-gui#612]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

I'm following streamers that stream different games, but I'm really interested in some of them. Twitch notifies me when the streamer goes online, but most of the time he's streaming a game I'm not interested in. It would be great if I could create a condition on the online-notification to limit it to a certain game. 

I image an option in the channel-settings-screen, where one can select either "always" or add games to a white list  (or perhaps black list) to filter notifications.

The notification mechanism would need to be adapted to be able to notify not only when the online-state of a stream changes, but if the streamed game changes, too.

### Additional comments, screenshots, etc.

none yet

**Comment by gyvess** [comment]
I didn't want to open a new issue and as this is related so I'll just add on to your request.

It would also be nice if notifications had a time limit on how often they can occur.  Sometimes streamers suffer from various technical issues which result in several stream launches, this in turn sends a notification each time the stream begins.  

An option to limit sent notifications from a specific channel if one had previously been sent within X amount of time would likely work.  Could even be a drop down selection of one, two, or five minutes much like the refresh content option for GUI.

**Comment by azizLIGHT** [comment]
#617 should be implemented first so that this feature can happen later down the line as well

**Comment by MannixMD** [comment]
Chatty has something similar. It throws a notification everytime a streamer changes game category. So it would be cool to see that as an option here.
