### ISSUE TITLE
request plugin https://streamcraft.com 

### ISSUE THREAD

**Issue by zxosazx** [streamlink/streamlink-twitch-gui#614]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Suddenly I found a streaming service https://streamcraft.com. Is it possible to add a plugin for it?

**Comment by sadiablos** [comment]
- [x] I understand the difference between *Streamlink* and *Streamlink **Twitch** GUI*.
I think it's not possible to add it to STG, but you can ask at Streamlink repo about that

**Comment by bastimeyer** [comment]
Wrong repo. Please go to the Streamlink issue tracker, use the plugin request issue template and provide the necessary infos which you are being asked about there.

https://github.com/streamlink/streamlink/issues/new?template=plugin_request.md

**Comment by zxosazx** [comment]
sorry, miss repo
