### ISSUE TITLE
Ads and players crashing

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-twitch-gui#621]
**Updating this post with new information, since I don't want to create a new one**

If you're still seeing embedded ads on Twitch streams, update to the **latest** Streamlink version, which is currently 1.6.0, and see the Streamlink changelog.
- https://streamlink.github.io/install.html
- https://github.com/streamlink/streamlink/releases/latest
- https://github.com/streamlink/streamlink/blob/master/CHANGELOG.md

-----

Since I've been getting a lot of questions over the past couple of days, I've decided to open this issue and talk about the recent changes on Twitch regarding the ads and what can be done in order to return to a more pleasant viewing experience.

## Embedded ads

A couple of days ago, Twitch has started to embed ads directly into the streams. This wasn't the case previously and ads were simply loaded from an external source by their web player, which meant that Streamlink wasn't affected by this, as it's just a simple HLS client which doesn't have to follow their advertisement rules.

These new ads however are put directly into the HLS stream (with metadata) and replace the HLS segments of the regular live stream you're watching. Since there's no way around that, you're forced to watch the ads and have to wait for Twitch to resume providing you with regular stream data. Unfortunately, there's no ultimate fix for that, so we all will probably have to deal with ads in the future on Twitch, either by watching them or by filtering them out and accepting a gap in the live stream. 

When I built Streamlink/Livestreamer Twitch GUI, the intention was never to bypass their ads when watching streams. It was meant as a simple front-end for watching streams efficiently in your local video player via Streamlink/Livestreamer. Therefore, I never had and still don't have anything against ads and I think they have their purpose (for the most part). Unfortunately though, due to the nature of how Streamlink works, these embedded ads can cause issues with certain players like VLC when the stream data changes (eg. different encoding, resolution, framerate, bitrate, etc). Their web player doesn't have this problem, because it consumes the HLS stream directly and can parse the included metadata, which is telling it to reset its decoding/rendering state whenever a new block of ads starts or ends. When using Streamlink, your local player needs to be able to do that just from reading the stream data alone. I've seen people complaining that VLC often crashes while switching to ads, but in my experience, MPV was working fine on my system all the time. So if you're seeing ads and are fine with that, you should consider switching to MPV.

## Preventing ads from being shown

Please upgrade to the latest releases of Streamlink and Streamlink Twitch GUI and make sure that you're using `Streamlink` or `Streamlink (Windows)` as streaming provider in the streaming settings menu. Then simply enable the "disable ads" option further down in the menu.

*I will upgrade this post with more infos later and will also move it to the wiki once finalized*

**Comment by xaxxon** [comment]
Is streamlink 1.0.0+46.g42105d8 the development version?  

I'm getting ads.

**Comment by bastimeyer** [comment]
Hm, this wasn't supposed to be a support thread, but here we go...

@xaxxon Make sure that you are actually running the latest Streamlink version. There are many users who have multiple versions of Streamlink installed and accidentally use the wrong one. Since you didn't provide a debug log, I am not sure whether you've done the same mistake. Please completely uninstall Streamlink and then install the latest development version.

Any version of Streamlink newer than `streamlink 1.0.0+38.g9ae6756` is fine.

**Comment by xaxxon** [comment]
Sorry about that.   It was more an informational post than a request for help, but here's the debug log - I was seeing ads when I stopped it:
```

zhansen-MacBookPro15:v8 zhansen$ /Users/zhansen/Library/Python/2.7/bin/streamlink --version
streamlink 1.0.0+46.g42105d8
zhansen-MacBookPro15:v8 zhansen$ /Users/zhansen/Library/Python/2.7/bin/streamlink twitch.tv/summit1g best -l debug
[cli][debug] OS:         macOS 10.13.6
[cli][debug] Python:     2.7.15
[cli][debug] Streamlink: 1.0.0+46.g42105d8
[cli][debug] Requests(2.21.0), Socks(1.6.7), Websocket(0.55.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/summit1g
[plugin.twitch][debug] Getting live HLS streams for summit1g
[utils.l10n][debug] Language code: en_US
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 900p60 (best)
[cli][info] Opening stream: 900p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 5
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 3; End Sequence: None
[stream.hls][debug] Adding segment 3 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Download of segment 3 complete
[stream.hls][debug] Download of segment 4 complete
[cli][info] Starting player: /Applications/VLC.app/Contents/MacOS/VLC
[cli.output][debug] Opening subprocess: /Applications/VLC.app/Contents/MacOS/VLC --input-title-format twitch.tv/summit1g -
[stream.hls][debug] Download of segment 5 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 6 to queue
[stream.hls][debug] Adding segment 7 to queue
[stream.hls][debug] Download of segment 6 complete
[stream.hls][debug] Download of segment 7 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 8 to queue
[stream.hls][debug] Adding segment 9 to queue
[stream.hls][debug] Adding segment 10 to queue
[stream.hls][debug] Download of segment 8 complete
[stream.hls][debug] Download of segment 9 complete
[stream.hls][debug] Download of segment 10 complete
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 11 to queue
[stream.hls][debug] Adding segment 12 to queue
[stream.hls][debug] Download of segment 11 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[cli][info] Stream ended
[cli][info] Closing currently open stream...

```

**Comment by bastimeyer** [comment]
If that's so, then please open a new thread on the Streamlink repo, as it's an issue of Streamlink, not the Twitch GUI.

**Comment by JoneeAL** [comment]
Hello Latest version off Streamlink iam missing the Follow button have to login in the browser to find it.
Any chanse you could fix it ? 👍

**Comment by bastimeyer** [comment]
This is not the right thread. Please don't ask off-topic questions here. If you are having issues with the login in the Twitch GUI, you can open a new issue and fill in the necessary details which is issue template is asking you. Also make sure that you are using the latest version of the Twitch GUI (currently 1.7.1), as there as been an issue with the login in the 1.7.0 one.
