### ISSUE TITLE
Stream title is html formated 

### ISSUE THREAD

**Issue by pquerner** [streamlink/streamlink-twitch-gui#623]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] I tried solving my issue by reading the project's wiki first.
- [ ] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  
Ubuntu 18.04

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
streamlink 0.13.0

### Description

Stream title is html tag styled, can this lead to anything inappropriate?

### Expected / Actual behavior

Stream title is plain text only

### Reproduction steps

Not sure. Find a streamer who does that to his stream.

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/4364044/54726187-38a1e600-4b72-11e9-8d74-d0b916c468e7.png)

**Comment by bastimeyer** [comment]
This is regular unicode from the ["Mathematical Alphanumeric Symbols"](https://www.compart.com/en/unicode/block/U+1D400) block

```bash
$ curl -s \
    -H 'Accept: application/vnd.twitchtv.v5+json' \
    -H 'Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8' \ 
    'https://api.twitch.tv/kraken/streams/67029440' \
    | jq .stream.channel.status
"𝑽𝒆𝒊𝒏𝒚 𝑯𝒐𝒕𝑺 𝒃𝒂𝒏𝒈𝒆𝒓 𝒇𝒐𝒓 𝒎𝒚 𝒅𝒂𝒚 𝒐𝒏𝒆𝒔\n"
```

HTML is properly sanitized and escaped by EmberJS when used in a Handlebars template:
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/ui/components/list/stream-item/template.hbs#L13
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.6.0/src/app/ui/components/stream/stream-preview-image/component.js#L32

And it's also properly escaped in player parameters and notifications:
https://github.com/streamlink/streamlink-twitch-gui/tree/v1.6.0/src/test/tests/utils/parameters
