### ISSUE TITLE
Twitch ads are being runned when using Twitch GUI program...

### ISSUE THREAD

**Issue by Nepturian** [streamlink/streamlink-twitch-gui#624]
Ads are being displayed with MPCHC when I have installed python and gotten the streamlink script installed.
PLEASE fix this, or there is no reason for me to have this software!

## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 1809

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
1.0.0

**Configuration details:**  

### Description

It plays ads at the beginning of the streamor during a stream... which is annoying!

### Expected / Actual behavior

Fix the API changes and dont let the player play ads!

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment]
See #621
