### ISSUE TITLE
Notifications can display unconverted HTML entities

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#626]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
ArchLinux

**Streamlink Twitch GUI version:**  
1.6.0

**Streamlink version:**  
streamlink 1.0.0

### Description

Environment used is Gnome. sometimes there's notifications from followed channels. And sometimes those notifications display raw HTML entities, unconverted to standard utf-8 character.

### Expected / Actual behavior

HTML entities should be converted to utf-8 character.

### Reproduction steps

No reliable reproduction steps other than being follower of a channel that might emit notifications with html entities characters.

**Comment by bastimeyer** [comment]
Thanks!
