### ISSUE TITLE
Pinned taskbar icon/shortcut tries to open chrome_proxy.exe

### ISSUE THREAD

**Issue by Carrybag1** [streamlink/streamlink-twitch-gui#629]
I'm unsure if this is because of Streamlink/Streamlink GUI or my PC but figured just encase it's happening to anyone else.

When I updated to the newest streamlink/GUI release and pinned the application to my taskbar it would try to open "chrome_proxy.exe" instead of streamlink (no issue with a shortcut created from the .exe, just the pinned one on my taskbar).

**FIX**
Right click pinned shortcut > right click stream link > properties > point target/start in to streamlink

**Comment by bastimeyer** [comment]
That's a bug in the latest NW.js release which was already fixed once in an earlier version:
https://github.com/nwjs/nw.js/issues/5991

Btw, you can simply right click the application name in the right click menu again and edit the shortcut. No need to go to the %APPDATA% folder.

**Comment by bastimeyer** [comment]
I've opened a new issue on the NW.js repo:
https://github.com/nwjs/nw.js/issues/7033

**Comment by Carrybag1** [comment]
> Btw, you can simply right click the application name in the right click menu again and edit the shortcut. No need to go to the %APPDATA% folder.

Did not realise you could right click the app again, useful to know. Thanks

**Comment by bastimeyer** [comment]
The issue has been fixed in NW.js and will be fixed here once I've upgraded to a newer (stable) NW.js release.

**Comment by patrikhuber** [comment]
I'm seeing exactly the same behaviour. Looking forward to the fix, thanks a lot! Awesome work!

**Comment by bastimeyer** [comment]
No new stable NW.js release yet:
https://nwjs.io/blog/

Issue was fixed on 2019-04-10:
https://github.com/nwjs/nw.js/issues/7033#issuecomment-481491657

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/releases/latest
