### ISSUE TITLE
Suggestion: Add Chrome's "--app" mode as a default "Chat application"

### ISSUE THREAD

**Issue by martinsstuff** [streamlink/streamlink-twitch-gui#631]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

It's fairly straight forward and already possible to do manually with the parameters shown in the screenshot ("--app=https://www.twitch.tv/popout/{channel}/chat").

I personally like it because it is a fairly minimal window and is independent from the rest of the open tabs while still supporting browser extensions like FFZ, etc.

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/29005772/55789996-731fe400-5a89-11e9-87b7-5f112d05a09f.png)

![image](https://user-images.githubusercontent.com/29005772/55790283-06f1b000-5a8a-11e9-90e4-7427bb871215.png)

**Comment by skulblakka** [comment]
You should already be able to select Google Chrome as Chat application. 

Am 9. April 2019 11:49:36 MESZ schrieb Martin Winkelmann <notifications@github.com>:

**Comment by martinsstuff** [comment]
Oh lol, I always just assumed it would be the same as the default browser option if Chrome is default. You're right, it's already a feature, closing the issue.

**Comment by jack-cole** [comment]
Sorry to bring this issue up, but this really needs to be documented better in the UI. I have been using this for months, and constantly wished for this feature. I only figured it out after searching issues.

**Comment by bastimeyer** [comment]
This is documented in the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Chat-configuration
