### ISSUE TITLE
Unexpected version check output

### ISSUE THREAD

**Issue by AinsworthK** [streamlink/streamlink-twitch-gui#643]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [ ] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  
Arch Linux

**Streamlink Twitch GUI version:**  
1.7.1

**Streamlink version:**  
1.1.1
**Configuration details:**  

### Description

When launching stream, failed and return "Unexpected version check output"
But running `streamlink <url for twitch> best` work and stream start.
Streamlink seems fine.

### Reproduction steps

1. ...click on any stream
2. ...
3. ...

**Comment by bastimeyer** [comment]
Executing `streamlink` from the shell is not always the same as opening a stream in the Twitch GUI, as the Twitch GUI supports custom streamlink/python paths with different resolving strategies and doesn't ignore error/warning messages of Streamlink. By default, the same resolving strategy as your shell should be used though, so make sure that you have no custom paths set in the streaming settings menu and that Streamlink itself is not returning any error or warning messages, as this will cause the version check error to be shown. You can find enough information about this error message and how to solve it on this issue tracker and on the wiki.

https://github.com/streamlink/streamlink-twitch-gui/issues/636#issuecomment-486047650
https://github.com/streamlink/streamlink-twitch-gui/issues?q=unexpected+version+check+sort%3Aupdated-desc
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

As you can see, this is a very common error on misconfigured systems. Unfortunately, I still haven't found the time/motivation to overhaul/improve the error handling with better and more useful information.

**Comment by AinsworthK** [comment]
Seems like the streamlink do have error message but the stream still works.
If you run into:
 `/usr/lib/python3.7/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.25.2) or chardet (3.0.4) doesn't match a supported version!
`
update urllib3.

related issue: https://github.com/streamlink/streamlink/issues/2448

Thanks for the help!
