### ISSUE TITLE
Channel settings not loading when accessed a second time

### ISSUE THREAD

**Issue by GenesisFR** [streamlink/streamlink-twitch-gui#646]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  Windows 10 x64 1809

**Streamlink Twitch GUI version:**  1.7.1

**Streamlink version:**  1.1

**Configuration details:**  English language

### Description

When accessing channel settings for the second time, it doesn't load and shows the following error message instead:

`"Attempted to handle event `loadedData` on <channelSettings:channel_name> while in state root.loaded.created.uncommitted."`

It affects all channels individually and the application must be restarted to make the channel settings load again.

### Expected / Actual behavior

It should show channel settings like it does the first time we access the channel settings menu.

### Reproduction steps

1. Click on Streams.
2. Click on any channel name to access its page.
3. Click on the Settings tab.
4. Click on any other tab.
5. Click on the Settings tab again.

### Log output

```
No log despite using "--loglevel debug".
```

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/3614449/59468767-e551d380-8e00-11e9-905c-9c72fee29f02.png)
![image](https://user-images.githubusercontent.com/3614449/59468788-f3075900-8e00-11e9-9a2d-cf51e4666742.png)

**Comment by bastimeyer** [comment]
Thanks for the bug report!
