### ISSUE TITLE
Confirmation window pops up after typing a number in the settings menu

### ISSUE THREAD

**Issue by nikuolive** [streamlink/streamlink-twitch-gui#647]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Arch Linux x86_64 

**Streamlink Twitch GUI version:**  
1.7.1

**Streamlink version:**  
1.1.1

**Configuration details:**  
Fresh install from AUR using yay

### Description
Typing a number in one of the input area in the settings menu pops out a confirmation window even I'm not done typing. Does not happen when I'm typing any characters other than numbers.

### Expected behavior
Confirmation window only pops up if I when to any other menu before saving / discarding any changes in the settings menu

### Reproduction steps

1. Go to the settings menu
2. Select any input area in the settings menu
3. Type a number in the input area
4. Confirmation window should pops up

### Additional comments, screenshots, etc.

![Peek 2019-06-19 22-32](https://user-images.githubusercontent.com/52004342/59780270-f5c3eb80-92e3-11e9-89c1-b9963affccb5.gif)

Confirmation window did not pops up if you are typing a character.

![Peek 2019-06-19 22-33](https://user-images.githubusercontent.com/52004342/59780280-f9f00900-92e3-11e9-80da-7f631bd12342.gif)

Pops up if you type a number

**Comment by bastimeyer** [comment]
Thanks for the bug report!

This issue here was related to the HotkeyService and the hotkeys 0-9 for navigating the menus. Something must have changed recently and this went through unnoticed.

It's fixed on the master branch now (you can use the `-git` AUR package if you want). I will probably have to publish a patch release because of this bug.
