### ISSUE TITLE
VOD

### ISSUE THREAD

**Issue by Chris230291** [streamlink/streamlink-twitch-gui#653]
Already seen the posts explaining why we don't have VODs.
Not sure how long this has been a thing but VLC just straight up plays VOD urls complete with seeking, time remaining etc. Is it possible to show VODs in your UI and just pass the video url to VLC, skipping streamlink?

Thanks,
Chris

**Comment by bastimeyer** [comment]
I've answered this question a couple of times over the past months.
See one of my answers here, which can also be applied to VOD support:
https://github.com/streamlink/streamlink-twitch-gui/issues/608#issuecomment-440534328
