### ISSUE TITLE
V1.8.1 Frozen gui when resuming Windows after long sleep

### ISSUE THREAD

**Issue by BourgeoisM** [streamlink/streamlink-twitch-gui#657]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 Profesional version 1803 on my laptop 
**Streamlink Twitch GUI version:**  

v1.8.1
NW.js 0.39.3
**Streamlink version:**  

Streamlink 1.1.1
**Configuration details:**  

### Description

Since the Update Streamlink Gui is not working properly when i put/exit the sleep mode of my laptop
When I resume from sleep, the interface is frozen, none of the buttons/scroll bar etc. reacts 
But when i click in the window where the stream selection is, it start reading the stream and launch player normaly.
It seems to happend after a long duration of sleep (usually over the night, but the bug can occur with ~2hr of sleep mode). I have not problem when doing sleep/resume fast

### Expected / Actual behavior

On version 1.7.1, when i put and resume from sleep mode of windows, 
The Gui is working fine, it just needed a refresh of the available streams.

### Reproduction steps

1. Launch Streamlink Gui, start a stream
2. put the computer in Sleep state
3. Resume after long period
4. Open the gui that should still be opened
5. See the gui Frozen

### Log output

here are the logs i have from the entering sleep to the exit sleep.
The laptop has been put in sleep around 17h50 and resumed at ~19h45 but no logs at the resume of windows

```
[2019-08-11T16:00:57.262Z][error][StreamingService]
Error: error: Error when reading from stream: Read timeout, exiting
{
    "id": "cohhcarnage",
    "quality": "source",
    "chat_open": true,
    "started": "2019-08-11T15:00:43.644Z",
    "stream": "26610234",
    "channel": "26610234"
}

[2019-08-11T16:02:45.354Z][error][Application]
unhandledrejection: TypeError: Failed to fetch
{}

[2019-08-11T17:50:31.645Z][error][Application]
Ember error: TypeError: Failed to fetch

[2019-08-11T17:50:36.267Z][debug][NotificationService]
Showing notification
{    
	"provider": "auto",
    "current": "snoretoast",
    "data": {
        "title": "Certain des chaînes que vous suivez ont commencé à stremer",
        "message": [
            {
					bunch of streams
	    }
        ],
        "icon": "C:\\Users\\Maxime\\AppData\\Local\\Temp\\nw25952_2325\\img\\icon-256.png",
        "settings": 1
    }
}
```

### Additional comments, screenshots, etc.

totally appart from the bug : 
note that it may have a translation error : 
in the debug log i see for notification title  : 
""title": "Certain des chaînes que vous suivez ont commencé à stremer"."
should probably be : 
""title": "Certain**es** des chaînes que vous suivez ont commencé à str**e**amer

**Comment by bastimeyer** [comment]
> resume from sleep, the interface is frozen

This is a NW.js / Chromium issue. Streamlink Twitch GUI upgraded from NW.js 0.37.4 (Chromium 73) to NW.js 0.39.3 (Chromium 75) during the upgrade from v1.7.1 to v.1.8.1.

You could try and see if this freezing issue also happens in Chromium / Chrome. The current stable version is 77, though. There are a couple of related issues on the [Chromium bugtracker](https://bugs.chromium.org/p/chromium/issues/list):
https://bugs.chromium.org/p/chromium/issues/detail?id=991972
https://bugs.chromium.org/p/chromium/issues/detail?id=992351

All I can do here is upgrading to a more recent NW.js/Chromium version, but as you may have seen in the current changelog, the recent upgrade has caused major issues in v1.8.0 (NW.js 0.40.0) and I had to downgrade NW.js again in v1.8.1. This has to be resolved first by the NW.js devs.

Just close Streamlink Twitch GUI for now before putting your system to hibernate.

----

> translation error

All translations except English and German are community contributions. Franch translations have just been added in v1.8.0 and there are probably a few more remaining issues. If you find a translation error or any kind of misspelling, please send a pull request with a correction. Thank you very much.

See the wiki:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Translating

And the translations here:
https://github.com/streamlink/streamlink-twitch-gui/tree/master/src/app/locales

**Comment by jfrisby9** [comment]
Sorry if bumping this is wrong, but I didn't want to make a new report - I've been having this issue since the latest version in win10 2004.
