### ISSUE TITLE
Please add support in gui/settings for "--player-external-http"

### ISSUE THREAD

**Issue by iXPert12** [streamlink/streamlink-twitch-gui#659]
## Feature request

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ x] This is a feature request and I have read the contribution guidelines.

### Description

Streamlink has a command line option "--player-external-http" and "--player-external-http-port" for starting a http stream server instead of running directly the vlc player, so i can connect and watch the stream remotely, for example on  mobile.

**Comment by bastimeyer** [comment]
This is not what Streamlink Twitch GUI was built for and I don't want to implement and maintain more edge cases like this. You will have to use an alternative solution, like a general purpose GUI for Streamlink or a shell script.
