### ISSUE TITLE
Stream previews/thumbnails not loading after DNS change

### ISSUE THREAD

**Issue by Tibuq** [streamlink/streamlink-twitch-gui#662]
### Environment details

**Operating system and version:**  
Windows 10 Home 64bit

**Streamlink Twitch GUI version:**  
1.8.1

**Streamlink version:**  
1.2.0

### Description

The DNS server I was using stopped working so I chose a new one and afterwards all the previews/thumbnails wouldn't load anymore:

![image](https://i.imgur.com/IO7uWw3.png)

EDIT:
![image2](https://i.imgur.com/XPEelnf.png)
It's not an issue specific to Streamlink Twitch GUI apparently, but maybe someone here can still help?

**Comment by KiraYamatoSD** [comment]
Thumbnails are loaded from static-cdn.jtvnw.net

You need to unblock this connection.

`static-cdn.jtvnw.net`

**Comment by bastimeyer** [comment]
All Twitch stream assets are being served via a single CDN under a single hostname, `static-cdn.jtvnw.net`, just like @KiraYamatoSD said.

Example:
```bash
$ curl -s \
  -H "Accept: application/vnd.twitchtv.v5+json" \
  -H "Client-ID: phiay4sq36lfv9zu7cbqwz2ndnesfd8" \ 
  "https://api.twitch.tv/kraken/streams?limit=1" \
  | jq '[ .streams[0] | .preview.template, ( .channel | .logo, .video_banner, .profile_banner ) ]'
```
```json
[
  "https://static-cdn.jtvnw.net/previews-ttv/live_user_esfandtv-{width}x{height}.jpg",
  "https://static-cdn.jtvnw.net/jtv_user_pictures/7cf28a3d-6b92-46c8-9be8-3f3662f95e21-profile_image-300x300.png",
  "https://static-cdn.jtvnw.net/jtv_user_pictures/95f2227b-a741-4916-80cc-a037d8e8a4b3-channel_offline_image-1920x1080.png",
  "https://static-cdn.jtvnw.net/jtv_user_pictures/dde47429-2611-4c3e-b78a-036785c73bca-profile_banner-480.jpg"
]
```

You will have to switch your network interface's DNS server or add a custom resolving rule, statically or dynamically.

Since it's not a Streamlink Twitch GUI related issue, I will close the thread.
