### ISSUE TITLE
Couple errors when launching streams...

### ISSUE THREAD

**Issue by melloman33** [streamlink/streamlink-twitch-gui#668]
## Bug report

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
<Windows 7-->

**Streamlink Twitch GUI version:**  
 The release version. 

**Configuration details:**  

### Description

Without any changes to anything, I just randomly started getting error messages when trying to launch streams. I've reinstalled both the GUI and livestreamer many times. Livestreamer 1.12.2.

### Reproduction steps

I'm starting streams from my followed stream list, and then I get the error codes. I will say this, my error message changed when I experimented with changing the installation folder. But both are fail to open errors. I will post the log for the first error, and then the one after changed the folder in the error logs. 

### Log output

Error Type 1, the initial error 

```
Found matching plugin twitch for URL twitch.tv/peeve
Attempting to authenticate using OAuth token
Unable to open URL: https://api.twitch.tv/kraken/user.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Waiting for streams, retrying every 1.0 second(s)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)
Unable to open URL: https://api.twitch.tv/api/channels/peeve/access_token.json ([Errno 1] _ssl.c:504: error:1407742E:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert protocol version)


```
Error 2, after installing to a different C folder. 

Found matching plugin twitch for URL twitch.tv/lirik
Attempting to authenticate using OAuth token
Unable to open URL: https://api.twitch.tv/kraken/user.json ((<requests.packages.urllib3.connection.VerifiedHTTPSConnection object at 0x037D6E30>, 'Connection to api.twitch.tv timed out. (connect timeout=20.0)'))
Waiting for streams, retrying every 1.0 second(s)

**Comment by bastimeyer** [comment]
#667
