### ISSUE TITLE
VLC is unable to open the MRL

### ISSUE THREAD

**Issue by oskars2x** [streamlink/streamlink-twitch-gui#670]
Your input can't be opened:
VLC is unable to open the MRL 'file://./pipe/streamlinkpipe-4632'. Check the log for details.

picture with error - http://prntscr.com/pmqp6x
i use newest versions of livestreamer and twitch gui
before i had error with was solved with thx of #667 special thx to melloman33. But still i cant open help me with this VLC MRL error

**Comment by bastimeyer** [comment]
> i use newest versions of livestreamer and twitch gui

Why do you say that you're using Livestreamer? It is not supported anymore, as you've already read in #667 and the error message in VLC is Streamlink related.

> streamlinkpipe

You seem to be using the named pipe / fifo player input method, which VLC from some reason doesn't interpret incorrectly. Maybe this is a bug on Windows or your VLC version is too old. I don't know.

Switch to the default player input method (standard input) or to the http input method in the Twitch GUI's streaming settings menu.
