### ISSUE TITLE
Couldn't find executable

### ISSUE THREAD

**Issue by toastmonster10** [streamlink/streamlink-twitch-gui#671]
I downloaded the lasted streamlink gui and installed on windowss 10 after I formatted my computer.

Logged into twitch account and tried playing a broadcast but I'm getting:

"Couldn't find executable"

My setting is set to the Streamlink (Windows) option.

I don't know where I'm supposed to find "streamlinkw.exe"

**Comment by bastimeyer** [comment]
> I downloaded the lasted streamlink gui

This sounds like you forgot to also install Streamlink.

https://github.com/streamlink/streamlink-twitch-gui
> A graphical user interface on top of the Streamlink command line interface.

> Please remember that Streamlink Twitch GUI, as the name already suggests, is only a graphical user interface (GUI) built on top of Streamlink. This means that Streamlink has to be installed on your system in order to be able to launch streams. Once again, see the wiki if you need help, as it also covers installing Streamlink.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

**Comment by toastmonster10** [comment]
Thank you
