### ISSUE TITLE
Http 410 on API

### ISSUE THREAD

**Issue by Zanndorin** [streamlink/streamlink-twitch-gui#672]
Hi since there is noone else complaining about this I am not sure if the issue is on my end...

Anyway I am getting HTTP 410 on more and more occasions (i.e. not always) and the only issue I could find being reported was quite old. I was using 1.7.1 but the issue persists in 1.8.1

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.8.1 (and 1.7.1)

**Streamlink version:**  
1.1.1

### Log output

Unable to open URL: https://api.twitch.tv/api/channels/dogdog/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/dogdog/access_token.json?as3=t&platform=_&oauth_token=XXX)

**Comment by bastimeyer** [comment]
This is a Streamlink related issue which is being tracked here:
streamlink/streamlink#2680

**Comment by Zanndorin** [comment]
ok thanks man, wasn't sure why my search function was unable to find that one...

edit: Whoops, saw that one opened 19minutes ago and I have had that for some days now haha :D
