### ISSUE TITLE
410 Client Error

### ISSUE THREAD

**Issue by ichmyselfandi** [streamlink/streamlink-twitch-gui#673]
I  get this error message since today. Nothing was changed.
Newest version, streamlink, ubuntu

Found matching plugin twitch for URL twitch.tv/xyz
Attempting to authenticate using OAuth token
Successfully logged in as XXX
Unable to open URL: https://api.twitch.tv/api/channels/xyz/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xyz/access_token.json?as3=t&platform=_&oauth_token=tv06sp5pclx42ofufjr7vmm4aby0yw)
Waiting for streams, retrying every 1.0 second(s)

**Comment by skulblakka** [comment]
This is a streamlink issue and was already reported over here https://github.com/streamlink/streamlink/issues/2680

**Comment by gravyboat** [comment]
Closing since this is the wrong repo. Please follow the link above.
