### ISSUE TITLE
App freezing

### ISSUE THREAD

**Issue by kleshas** [streamlink/streamlink-twitch-gui#674]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Arch i3 fully updated, multiple installs

**Streamlink Twitch GUI version:**  
1.8.1

**Streamlink version:**  
1.2.0

**Configuration details:**  

### Description

The app freezes, any time from 15mins to a couple of hours.  Doesn't matter whether I am watching a stream (mpv and chatty in use) or not.  Sometimes the app window cannot be moved but will be clickable (ie when I try to move or click on the X to close it, another stream will pop up).  Cannot stop the app when using htop - the listed app is streamlink-twitch-gui but is not stoppable (htop cannot find the app even though it has it listed) but CAN stop it using "pkill streamlink-twit" (not a mistype - this is the full process name)

### Reproduction steps

I leave the app open all day, and it will freeze at least 4 or 5 times during that time.  This has been going on for weeks, and over at least 2 reinstalls of the operating system.  Reinstalling streamlink-twitch-gui does not help

Nothing in log when app freezes.

**Comment by bastimeyer** [comment]
> Nothing in log when app freezes.

Did you enable Chromium logging?
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#chromium-logging

Have you tried the latest version from the master branch? This includes an NW.js/Chromium upgrade. Check CONTRIBUTING.md for build instructions or the `-git` AUR package.

**Comment by kleshas** [comment]
Can't test anything as streamlink-twitch-gui is completely broken right now with the "410 client error: Gone for url" reported elsewhere...

**Comment by bastimeyer** [comment]
So you're only seeing freezes while watching streams? This is hardly a Streamlink Twitch GUI issue then, since it's just a launcher for Streamlink and has nothing to do with actual streaming.
You could try testing this while watching other streams/videos. Maybe disabling GPU acceleration for the Twitch GUI (`--disable-gpu`) could help with your problem.

**Comment by kleshas** [comment]
It also freezes when not watching streams, as I said in my orignal post.
I will try --disable-gpu when and if the app starts working again (watching your posts in the 410 client error issue)

**Comment by kleshas** [comment]
I'm thinking I MIGHT'VE fixed it - I was using an incorrectly configured notification daemon I think (plasma-workspace was listed, was installed as a dependency).  Now I have dunst, I haven't had a freeze yet.

**Comment by kleshas** [comment]
Been hours and not one crash/freeze, so I think it was the misconfigured notification system.  Thanks for the feedback.
