### ISSUE TITLE
Add native input for MPV to the "Streaming" settings

### ISSUE THREAD

**Issue by lextra2** [streamlink/streamlink-twitch-gui#675]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

These days, all you really need is mpv+youtube-dl for a stream to work flawlessly. No need for bloated phyton scripts (Streamlink / Livestreamer).

You can literally drag-and-drop any twitch channels url onto mpv and it will play as long as youtube-dl is also in the same location as mpv.

So this is my request: Add direct mpv input to the "Streaming" settings. And what I mean by that is, simply launch mpv with the selected channels url. Done.

**Comment by bastimeyer** [comment]
#608
