### ISSUE TITLE
blocked client id?

### ISSUE THREAD

**Issue by Elcius** [streamlink/streamlink-twitch-gui#676]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
win7

**Streamlink Twitch GUI version:**  
1.7.0 and 1.8.1 tested

**Streamlink version:**  
1.1.1 and 1.2.0 tested

**Configuration details:**  

### Description
when using the application generated url (clicking the login button) to generate an access token, passport.twitch.tv returns [Forbidden - CSRF token invalid].

### Reproduction steps

1. logout/clear access token
2. attempt to login
3. request fails

### Additional comments, screenshots, etc.
[the generated url](https://passport.twitch.tv/sessions/new?client_id=phiay4sq36lfv9zu7cbqwz2ndnesfd8&force_verify=true&oauth_request=false&redirect_path=https%3A%2F%2Fid.twitch.tv%2Foauth2%2Fauthorize%3Fresponse_type%3Dtoken%26client_id%3Dphiay4sq36lfv9zu7cbqwz2ndnesfd8%26redirect_uri%3Dhttp%253A%252F%252Flocalhost%253A65432%252Fredirect%26scope%3Duser_read%2Buser_blocks_read%2Buser_blocks_edit%2Buser_follows_edit%2Buser_subscriptions%2Bchat_login%26force_verify%3Dtrue&redirect_uri=http%3A%2F%2Flocalhost%3A65432%2Fredirect&response_type=token&scope=user_read+user_blocks_read+user_blocks_edit+user_follows_edit+user_subscriptions+chat_login&username=)

**Comment by bastimeyer** [comment]
Everything that happens on Twitch's end related to the login is none of Streamlink Twitch GUI's business. After a successful login, Twitch will send your web browser to the local webserver that's being launched after clicking the sign in button. That's where the OAuth token is retrieved.
