### ISSUE TITLE
Unable to open URL/Client Error: Gone for url

### ISSUE THREAD

**Issue by AirPhforce** [streamlink/streamlink-twitch-gui#677]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Win 10

**Streamlink Twitch GUI version:**  
1.8.1

**Streamlink version:**  
1.2.0

**Configuration details:**  
Nothing special. 

### Description

Worked this AM. Later this AM I get;

Found matching plugin twitch for URL twitch.tv/XXXXX
Attempting to authenticate using OAuth token
Successfully logged in as XXXXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Waiting for streams, retrying every 1.0 second(s)
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX
Unable to open URL: https://api.twitch.tv/api/channels/tekken/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/tekken/access_token.json?as3=t&platform=_&oauth_token=XXX

On every stream. Like I said this worked this morning. I checked to see if the twitch API was up, and it is. I have cleared Streamlinks cache.

### Expected / Actual behavior

Stream loads.

### Reproduction steps

1. ... Try and launch any stream

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment]
This is a Streamlink related issue, not Streamlink Twitch GUI.
streamlink/streamlink#2680

I'll leave this thread open, because I've already had several duplicates here yesterday when the issue occured for a few minutes, and I don't want more.

**Comment by AirPhforce** [comment]
Ah! Sorry about that!

**Comment by BoredSloth** [comment]
Trying to open web page of any streamer returns error 410:
Error
There was an error while trying to display this page.
Name HTTP Error
Message Gone
Detail this API has been removed.
Status 410
Host api.twitch.tv
Path api/channels/drdisrespect/panels

As an addition Streamlink Twitch GUI fails to get authorization token from id.twitch.tv/oauth2/authorize:
{"status":401,"message":"invalid csrf token"}

**Comment by Jackblqc** [comment]
Getting same errors , started happening like 1 or 2 hours ago , was working fine during the day/evening , hope we can fix this.


Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Waiting for streams, retrying every 1.0 second(s)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)
Unable to open URL: https://api.twitch.tv/api/channels/xqcow/access_token.json (410 Client Error: Gone for url: https://api.twitch.tv/api/channels/xqcow/access_token.json?as3=t&platform=_&oauth_token=vddxfmurd212vqfqv2z2xwum2osdo5)

**Comment by bastimeyer** [comment]
Read the thread I've linked. This is not the right place to discuss this.
