### ISSUE TITLE
Cannot read property 'killed'of undefined 😢

### ISSUE THREAD

**Issue by MonkeyDMax92** [streamlink/streamlink-twitch-gui#679]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**   _Windows 10 Ver. 1903_

**Streamlink Twitch GUI version:** _1.8.1_

**Streamlink version:**  _1.2.0_

**Configuration details:**  _X_

### Description

_Hi, 
For some time, twitch does not work well on third party applications (Potplayer + Extensions, Unstream app etc.). Despite what I tried to solve the problem, I still have these errors (see screenshots). I don't  know how to solve these problems knowing that Livestreamer and Streamlink are good and well installed on my computer._

### Additional comments, screenshots, etc.

**_I forgot to put Labels_**

**_Streamlink (Windows) config :_** 

![TGUIProblems](https://user-images.githubusercontent.com/42703828/68623687-5d6a1580-04d5-11ea-9315-542553d430d2.png)

**_Livestreamer config :_** 

![TGUIProblems2](https://user-images.githubusercontent.com/42703828/68624359-e766ae00-04d6-11ea-8ece-67ab5557e591.png)

**_Livestreamer (Standalone) config :_** 

![TGUIProblems3](https://user-images.githubusercontent.com/42703828/68624439-2432a500-04d7-11ea-85c9-509a137d6c64.png)

**Comment by bastimeyer** [comment]
> C:\\Program Files (x86)\\Streamlink\\Streamlink.launch.pyw

Why did you set this path? This is nonsense.

If you're using the Streamlink installer on Windows, you don't have to select any custom paths at all. But if you decide to set a custom path, then you need to point it towards `streamlinkw.exe`.

Just follow the wiki if you're having trouble setting this up:
https://github.com/streamlink/streamlink-twitch-gui/wiki

Be aware of the current issue regarding the Twitch API though:
streamlink/streamlink#2680

----

Btw, Livestreamer doesn't work anymore (#667). It's already been deprecated since two years and the next release will remove the support for it entirely.

**Comment by MonkeyDMax92** [comment]
Thank you for answering me, 
I can not find `streamlinkw.exe` but I find `streamlink.exe` in the Bin file. 
that gives me as result (see screenshot) while I have the latest version to install ... If I leave the default line (Streamlink executable), I have a Time Out

![TGUIProblems](https://user-images.githubusercontent.com/42703828/68627323-c6558b80-04dd-11ea-9a52-8104c98969ce.png)



-------------------------------------------------
_Livestreamer does not work anymore, ok  😅_

**Comment by bastimeyer** [comment]
You are trying to use an outdated Streamlink version. You need to upgrade.

**Comment by MonkeyDMax92** [comment]
It works, the fact of not having to uninstall the previous version has bugged the installation of the new version. I changed player because VLC had problems: 😅

![TGUIProblems](https://user-images.githubusercontent.com/42703828/68629356-c8224d80-04e3-11ea-9e68-64e1efa05fce.png)
