### ISSUE TITLE
MPV OSC Title not set to --title

### ISSUE THREAD

**Issue by Tenyun** [streamlink/streamlink-twitch-gui#683]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Archlinux

**Streamlink Twitch GUI version:**  
1.8.1
NW.js 0.39.3

**Streamlink version:**  
1.2.0

**Configuration details:** 
OS specific
I'm on i3-gaps (so no window decoration or title bars)

* Streaming 
  * Player input = Standard input
* Player
  * Player preset = mpv
  * Player window title = Set custom title

### Description

Open a stream with the given streamlink-twitch-gui config (see Configuration details). The title is set for mpv window but not in the OSC inside mpv. The OSC shows a "-" as title.

### Expected / Actual behavior

The title information should be visible in the OSC when the stream starts.

### Reproduction steps
1. Launch Streamlink Gui, start a stream

### Additional comments, screenshots, etc.
In "htop" i can see that the "--title" options ar set like this:
```
/usr/bin/mpv --title twitch.tv/jjacko --keep-open=no --title $>Jjacko - Planet Zoo - Tag 353 | Unbegrenzt genießbarer Stream (Außerhalb von Asien) | #H1oo --no-border --force-window -
```
But the OSC title is set to the last "-" in this line.

**Comment by bastimeyer** [comment]
The OSD is showing the "media title", read from the stream's/container's metadata, or just the source where MPV is reading the data from if there is no metadata, stdin in this case, hence the dash.

The media title can be changed via [`--force-media-title`](https://mpv.io/manual/stable/#options-force-media-title) in addition to `--title`, which just sets a custom window title.

You can do this manually in the custom MPV parameters field by adding
```
--force-media-title "{name} - {game} - {status}"
```
but adding it to the parameters preset list doesn't sound like a bad idea, as it's a reasonable feature. Property expansion doesn't seem to be working here, so `$>` doesn't have to be set.

**Comment by Tenyun** [comment]
Thank you for the hint with `$>`. 
I tested some of the options in the "Custom parameters" setting in the past without luck. 

Now it is working fine.

It would be nice to see this in the future standard configuration.

Thanks a lot!

**Comment by bastimeyer** [comment]
> It would be nice to see this in the future standard configuration.

I've added the parameter to the preset list and the default value is set to true:
https://github.com/streamlink/streamlink-twitch-gui/commit/fa310904daf46cfa5733d84c34968ca8bcf0d751#diff-a40bbccd1218c40a09801c3225ab273cR105

**Comment by Tenyun** [comment]
Thank you 👍
