### ISSUE TITLE
Tooltip colour

### ISSUE THREAD

**Issue by Carrybag1** [streamlink/streamlink-twitch-gui#686]
Hi

Since 1.9.0 the colour of the title of the stream has changed.

It used to be the first image but now is the second image. Can either of the options be made as changes :
- Change color from light white to a grey.
- Remove white box on border
- Revert it

Thanks

![image](https://user-images.githubusercontent.com/15611586/69484143-91bfc900-0e27-11ea-982f-af0a209f6c93.png)

![image](https://user-images.githubusercontent.com/15611586/69484132-7359cd80-0e27-11ea-84a0-f8a8586ffe87.png)

**Comment by bastimeyer** [comment]
That's called a tooltip and it's rendered by NW.js/Chromium and not by the app itself, so there's no control over how this is displayed. The dark tooltips became the default in one of the latest Chromium versions. I've looked for Chromium feature flags in its source code and whether this can be changed, but I couldn't find anything.

There have been some changes a couple of days ago in Chromium though, which will make tooltips on dark system themes light again, but this will be out in Chromium 80 (and be picked up in NW.js 44), so it'll take a while until it's available:
https://github.com/chromium/chromium/commit/5b07d20a39c298fc55f99e307ea4f7035ea6371c
https://bugs.chromium.org/p/chromium/issues/detail?id=1024091#c13

Chromium release schedule:
https://www.chromestatus.com/features/schedule
NW.js release blog:
https://nwjs.io/blog/

**Comment by Carrybag1** [comment]
That sucks, the white is annoyingly way too bright with dark mode.

Thanks for the info.

**Comment by bastimeyer** [comment]
Closing since it's a NW.js/Chromium thing and can't be controlled here. The latest version is used on the master branch, but the Chromium devs haven't changed the tooltip color for dark themes (yet - don't know).
