### ISSUE TITLE
v1.9

### ISSUE THREAD

**Issue by August40th** [streamlink/streamlink-twitch-gui#687]
So with the updated version: after I launch a stream and minimize the program I cannot get it to reappear without restarting or signing out the windows user and relaunching

**Comment by bastimeyer** [comment]
There is nowhere near enough information for me or anyone else to understand what you're trying to say here.

Use the [bug report issue template](https://raw.githubusercontent.com/streamlink/streamlink-twitch-gui/master/.github/ISSUE_TEMPLATE/bug_report.md) and fill in the necessary details.
