### ISSUE TITLE
MacOS Mojave and v1.9 - System Freezing

### ISSUE THREAD

**Issue by ikiPZdU6UP3Gra** [streamlink/streamlink-twitch-gui#688]
I just updated to v1.9 and the app is causing my entire system to intermittently freeze if I do anything with the Streamlink Twitch GUI. Seems to be ok once a stream has opened in VLC, but all interface actions cause heavy freezing (as in no other window or even the mouse cursor is able to move/refresh for 10+ seconds).

I made sure to update Streamlink to v1.3 as well.

**Comment by bastimeyer** [comment]
In `v1.9.0`, the NW.js platform version got bumped to `0.42.3` which uses Chromium `78` under the hood. However, your issue sounds more like an issue with your system configuration rather than NW.js `0.42.3`.

Please check if you can find something in the error / debug log output of NW.js/Chromium ([see the wiki](https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters)) or check if disabling GPU acceleration can fix the problem (via `--disable-gpu`), as it sounds like accelerated animations in the GUI are causing your system to hang.

**Comment by iNko97** [comment]
I am experiencing the same problem, the entire system stutters whenever I either launch Streamlink GUI or a stream.

MacOS Mojave 10.14.6
Streamlink GUI 1.9.0
Streamlink 1.3.0
Python 2.7.17

I have not changed any presets but I have the oauth token flag as parameter for launching streams.

**Comment by bastimeyer** [comment]
> whenever I either launch Streamlink GUI or a stream

As mentioned above, this sounds like a GPU acceleration issue on your system. But since you're also having issues with your video player, this is hardly an issue of Streamlink Twitch GUI itself. Other than asking you to post a debug log, which I've also mentioned above, I can't help.

**Comment by adityakaulagi** [comment]
How can we specify the recommended launch parameter for Streamlink Twitch GUI? I couldn't find any instructions on how to pass these parameters on the [Parameters](https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters) wiki page.

**Comment by bastimeyer** [comment]
On macOS, you need the `open` command, just like with every other app.

```bash
$ man open
NAME

     open -- open files and directories

SYNOPSIS

     open [-e] [-t] [-f] [-F] [-W] [-R] [-n] [-g] [-h] [-b bundle_identifier] [-a application] file ... [--args arg1 ...]

DESCRIPTION

     -a application
	 Specifies the application to use for opening the file

     -b bundle_indentifier
	 Specifies the bundle identifier for the application to use when opening the file

     --args
	 All remaining arguments are passed to the opened application in the argv parameter to main().	These arguments are not opened or interpreted by the open tool.
```

Examples:

```bash
$ open "/Applications/Streamlink Twitch GUI.app" --args --disable-gpu
$ open -a "Streamlink Twitch GUI" --args --disable-gpu
$ open -b streamlink-twitch-gui --args --disable-gpu
```
