### ISSUE TITLE
Streamlink GUI 1.8 onward only shows a black screen

### ISSUE THREAD

**Issue by Salsaparrilha** [streamlink/streamlink-twitch-gui#693]
Hello, I've been using version 1.7.1 up until the changes in the Twitch API because the Streamlink GUI versions after that one just show a black screen instead of the normal GUI screen. I assumed you stopped caring for Win7 after that version but I just wanted to be sure if this was something you may have overlooked now that the old version no longer works. Thanks for GUI!

Streamlink GUI before:
![1 7 1v](https://user-images.githubusercontent.com/17299372/69909789-3f1e7800-13f8-11ea-80c0-a78f0fa46ace.png)
Streamlink GUI now:
![Streamlink 1 8 and more](https://user-images.githubusercontent.com/17299372/69909790-3fb70e80-13f8-11ea-887e-6e6383ed4289.jpg)

**Comment by bastimeyer** [comment]
> black screen

Streamlink Twitch GUI works perfectly fine in a fresh Windows 7 VM on my system.
See #669 and post an error/debug log here please.

> I assumed you stopped caring for Win7

If that was the case then it would have been noted in the changelogs.

**Comment by Salsaparrilha** [comment]
My apologies. After checking post #669 and disabling the GPU it worked. I had seen the post before and believed it didn't apply to my issue by mistake. Thank you for your help.
