### ISSUE TITLE
Remove obsolete gconf dependency

### ISSUE THREAD

**Issue by farid-fari** [streamlink/streamlink-twitch-gui#694]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Arch linux, kernel 5.4.1-arch1

**Streamlink Twitch GUI version:**  
1.9.0-1

**Streamlink version:**  
1.2.0-2 (outdated but this is not a runtime bug)

**Configuration details:**  
none

### Description

The package depends upon `gconf`, which in turn depends on `python2`, which reaches end of life in January 2020. Moreover, `gconf` is obsolete.

### Expected / Actual behavior

The package should not depend upon `gconf`.

### Reproduction steps

1. Install `streamlink-twitch-gui` on Arch Linux.
2. Notice that `gconf` is installed as a dependency.

### Log output

```
none
```

### Additional comments, screenshots, etc.

AUR page: https://aur.archlinux.org/packages/streamlink-twitch-gui/

**Comment by bastimeyer** [comment]
Thanks! I simply forgot to remove some of the dependencies in one of the earlier releases and never looked at it again.

I've decided to create a package repo mirror here:
https://github.com/streamlink/streamlink-twitch-gui-aur

Dependencies were fixed here:
streamlink/streamlink-twitch-gui-aur@46538b9ff404121780565eeedc8c39bad2d4f6e0
and are now the same as the `nwjs-bin` AUR package.

I won't bump the pkgrel though, as it's not really needed and would only trigger an unnecessary upgrade for users of AUR helpers. If these changes are important to you, you can force-re-build the package (in case you haven't already edited the PKGBUILD yourself before building).

**Comment by bastimeyer** [comment]
Btw, please post package related issues on the AUR page next time. This isn't really the right place. Thanks again though!
