### ISSUE TITLE
Streamlink Twitch GUI - Opening in Existing browser session

### ISSUE THREAD

**Issue by LinuxReborn** [streamlink/streamlink-twitch-gui#695]
Everytime I try to run Twitch GUI I get this message in Terminal.
Opening in existing browser session.
Then it doesn't do anything else, no crash no error and it doesn't open.

I am using Elementary OS 5.1 based on Ubuntu 18.04 I believe any idea how to get the application to actually run?

**Comment by bastimeyer** [comment]
> Opening in existing browser session.

If this message gets written to stdout, then you've already got a Streamlink Twitch GUI process running and attempted to start it twice. Streamlink Twitch GUI, like all NWjs based applications, is a singleton app and secondary launches will terminate immediately after sending the parameter string to the already running process.
