### ISSUE TITLE
Reruns disappeared

### ISSUE THREAD

**Issue by BakingBatman** [streamlink/streamlink-twitch-gui#700]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 1903

**Streamlink Twitch GUI version:**  
1.9.0

**Streamlink version:**  
1.3.0
**Configuration details:**  

### Description

Started using Streamlink and GUI few weeks ago. After setting it up, everything was fine, live streams and reruns were visible with reruns being faded. I started playing around in the settings in the next few days. One day no rebroadcast were visible at all. Since then I have tried every possible setting, I didn't find anything that would help. I didn't find a restore default settings to see if I messed something up.
Is the issue user related, on Twitch's side or a bug?

### Expected / Actual behavior

Expect: See all followed streamers that are streaming, live or not.
Reality: Only live streams show up

### Reproduction steps

1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

### Additional comments, screenshots, etc.
On Twitch: https://imgur.com/kEBHGGu
IN GUI: https://imgur.com/DMEjhyU

**Comment by bastimeyer** [comment]
Similar to the sorting issue of the followed streams, this is caused by a change/bug on Twitch's end which I can't fix.

https://discuss.dev.twitch.tv/t/kraken-streams-followed-endpoint-no-longer-returning-re-run-streams/23786

**Comment by BakingBatman** [comment]
Understood, thanks for the fast answer!
