### ISSUE TITLE
streamlink-twitch-gui wont launch

### ISSUE THREAD

**Issue by IsidroPenh** [streamlink/streamlink-twitch-gui#704]
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  
Zorin OS Lite 15.1 based on Ubuntu 18.04.3 LTS

**Streamlink Twitch GUI version:**  
1.9.1

**Streamlink version:**  
1.3.1

### Description

Install everything as the tutorial says but the gui is not starting. I can use streamlink via terminal but not the UI

### Reproduction steps

1. Open streamlink-twitch-gui via menu
2. Nothing happens

**Comment by bastimeyer** [comment]
> Install everything as the tutorial says

Which tutorial?

> 2\. Nothing happens

Post the error log message(s) that you get when you try to run the `streamlink-twitch-gui` executable from the command line shell.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

**Comment by IsidroPenh** [comment]
> Which tutorial?

https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation#linux-1

> Post the error log message(s) that you get when you try to run the streamlink-twitch-gui executable from the command line shell.

How do i open it from the command line shell?

**Comment by bastimeyer** [comment]
```bash
cd dir/where/you/extracted/the/release/archive
./streamlink-twitch-gui
```

**Comment by IsidroPenh** [comment]
Says **Opening in Existing browser session**

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/695#issuecomment-565476126

> If this message gets written to stdout, then you've already got a Streamlink Twitch GUI process running and attempted to start it twice. Streamlink Twitch GUI, like all NWjs based applications, is a singleton app and secondary launches will terminate immediately after sending the parameter string to the already running process.

Can you check and see if a "streamlink-twitch-gui" process is already or still running in the background?

```bash
ps -fp $(pidof streamlink-twitch-gui)
```

**Comment by IsidroPenh** [comment]
There are 2 processes

**Comment by bastimeyer** [comment]
Then you must have started Streamlink Twitch GUI previously and it's still running. As I've said, you can't run the application twice, so any further attempts of launching it will result in the message you've posted earlier, as it will only send the secondary launch parameters to the running instance.

In case that the application didn't terminate properly for whatever reason, try to kill the already running processes manually and start the application again from the command line shell. If the application then doesn't properly launch (or terminate if you close the application window), then you'll probably see what's going on in the terminal, as the process is still attached to it and you can see any messages being written to `stderr` or `stdout`.

**Comment by IsidroPenh** [comment]
Restarted PC and worked. Thanks!
