### ISSUE TITLE
Outdated Twitch emote URLs

### ISSUE THREAD

**Issue by sfkpmr** [streamlink/streamlink-twitch-gui#705]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Description

The button to view a channel's emotes links to https://twitchemotes.com/channel/[channel name], but that page seems to have moved to https://twitchemotes.com/channels/[ID].

Not sure if it's a Twitch ID, or a Twitch Emotes ID, but you can search by channel name on the main page.

**Comment by sfkpmr** [comment]
Example:

Current URL: https://twitchemotes.com/channel/shivfps

Working URL: https://twitchemotes.com/channels/128149102

**Comment by bastimeyer** [comment]
Thanks for reporting!
