### ISSUE TITLE
Add local favorite games list

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#711]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description
Since Twitch's API for favorite games got removed, and Streamlink-twitch-gui therefore removed the feature due to this because it was not working anymore, it would be nice to have it come back as a local only feature, think table of shortcuts to your favorites games pages rather than having to look for those in the general Games page where they have moving place depending on the number of streamers/viewsers.

**Comment by bastimeyer** [comment]
See https://github.com/streamlink/streamlink-twitch-gui/issues/689#issuecomment-559371963
