### ISSUE TITLE
Ability to customize the format of the display of the uptime of channel/stream

### ISSUE THREAD

**Issue by mepherion** [streamlink/streamlink-twitch-gui#713]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Ability to customize the format of the stream's uptime on the Followed Streams page and on the channel page so that one can display hours, minutes, seconds and/or always show hours and minutes when the uptime exceeds 24 hours.

### Additional comments, screenshots, etc.

When the stream's uptime exceeds 24 hours, Streamlink GUI displays the uptime in days and hours. Would like the ability to keep it as hours and minutes.

![screenshot2](https://user-images.githubusercontent.com/20154933/78022198-8e32d600-7322-11ea-9ee7-06eece2caacd.PNG)

![screenshot](https://user-images.githubusercontent.com/20154933/78022207-9428b700-7322-11ea-9d85-49457b0414fb.PNG)

**Comment by bastimeyer** [comment]
Thanks for the suggestion.

0898155 implements an option for switching between the days+hours and hours+minutes format for stream uptimes greater than 24 hours.

No fully customizable formats due to i18n stuff.
