### ISSUE TITLE
Misleading error message when %temp% variable is invalid

### ISSUE THREAD

**Issue by DOFandersolsen** [streamlink/streamlink-twitch-gui#719]
## Bug report

- [ x ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ x ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 Pro, 1909

**Streamlink Twitch GUI version:**  
v 1.9.1

**Streamlink version:**  
1.3.1

**Configuration details:**  
Danish version of Windows

### Description

I closed Streamlink Twitch GUI as a normal program, while my computer was under heavy load (Running programs that manipulated video on all cores) and when I try to start the program afterwards, I get the following message (translated from danish):

```
Could not read the extension from C:\Program Files\Streamlink TwitchGUI\debug
The manifest file is missing or cannot be read
```
![billede](https://user-images.githubusercontent.com/16536056/81018717-5a892580-8e65-11ea-9c56-c2434e9a1fad.png)

Looking inside the C:\Program Files\Streamlink Twitch GUI\ folder, there is no debug-folder at all and no files named debug either
![billede](https://user-images.githubusercontent.com/16536056/81018775-77bdf400-8e65-11ea-8786-45909f4c9d6a.png)

I found out that because I had changed my %TEMP% and %TMP% environment variables to point to a ramdisk, R:\Temp, and then unmounted the ramdisk but not restarted explorer.exe, whenever I would run a program, it would try to access R:\ instead of C:\Users\Anders Olsen\AppData\Local\Temp

By restarting explorer.exe so the default %temp% and %tmp% variables was restored, I could start STG again.

### Expected / Actual behavior

The program should write an error message, saying it cannot write to the temporary folder at <invalid path>

The program writes an error message saying it cannot read a file/folder from C:\Program Files\Streamlink Twitch GUI\

### Reproduction steps

1. Change your %temp% and %tmp% environment variables to an invalid location
2. Try to start STG
3. STG should fail with the above error message
4. Reset %temp% and %tmp% to default and restart explorer.exe
5. Try to start STG
6. STG should start as normal

**Comment by bastimeyer** [comment]
The message you're seeing gets displayed by NW.js, not Streamlink Twitch GUI itself, so there is no way to change this here. The cause of it is how the application code is bundled with the NW.js executable via nwjs-builder. By default, it zips the app code and appends it to the NW.js executable, which means that on each application start, NW.js has to extract the app code into a temporary folder first, before it can run the code. The system's default temp dir gets used for that and the path is read from one of the env vars (not sure which one on Windows). If it can't write into the temp dir for whatever reason, then it won't launch and the message gets shown. If there is a problem with the message, then it needs to be fixed upstream, not here. I don't see this as a problem though, as being able to write into the system's temp dir is a requirement anyway (for many applications), as other runtime files need to be written there regularly.

Regarding the app code bundling though, this has already been changed on the master branch in February and now it doesn't need to extract files on each launch. The next release will include these changes, so this message won't be shown then if the system's temp dir is inaccessible and other temporary runtime files will fail silently.
See f84a5fc5552ecfea195b5085715ff862c2a94a86

**Comment by DOFandersolsen** [comment]
Thanks for your explanation, it makes a lot of sense that it can't do a lot if the unpacking fails.
Since I couldn't find any other issues related to this, I'll just let it end here, but if someone sees this issue because of the same error, he/she can post an issue to nw.js's repository and refer to this issue.
