### ISSUE TITLE
Search sometimes report empty results while there should have some results

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#725]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Bug reproduced on every OS (ArchLinux, mac, Windows)

**Streamlink Twitch GUI version:**  
1.9.1

**Streamlink version:**  
1.3.1

### Description

Sometimes, pressing "enter" on a search result in empty results after the search is done. Then going to click refresh do the same search… and display results.

### Expected / Actual behavior

Results should be shown on pressing enter, without needing to run the search a second time

### Reproduction steps

There's unfortunately no reliable reproduction steps as it happens only sometimes. I think it's more likely to happen if last search/interraction with streamlink-twitch-GUI is already from some times ago.

### Additional comments, screenshots, etc.

Bug doesn't happen from long time ago I think. However, a linked issue that might be related or not and anyway worth checking out in the same time is that pressing enter on a search does absolutely nothing if the currently displayed page is already the same search. (It should allow to refresh the search imho).

**Comment by bastimeyer** [comment]
I can't reproduce this.

> empty results after the search is done

The search route's content can't be empty unless there was an exception/error thrown somewhere and it didn't get caught properly, which is also weird, because exceptions should always get caught.
- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/app/ui/routes/search/template.hbs#L3-L26
- https://github.com/streamlink/streamlink-twitch-gui/blob/v1.9.1/src/app/ui/routes/search/controller.js#L16-L24

Please check the error log file and see if you can find anything there.
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l

Otherwise, please run the app in debug mode and check the dev tools for any errors, either in the console or maybe network tab, if a search response didn't include the proper data.
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building

**Comment by Porkepix** [comment]
I ran `streamlink-twitch-GUI` with the `-l debug` option, but to be honest it doesn't show a lot in the console, and especially nothing when running a search or switching view in the software.

**Comment by bastimeyer** [comment]
It doesn't log everything, even when the loglevel is set to debug. That's why I suggested running a dev build, so you can check the dev tools and network requests.

It would be much more simple if you could tell me which search query actually triggers the empty search result.

**Comment by Porkepix** [comment]
Well, it doesn't seems to depend on the search query, it just sometimes randomly happens.
If I had a reliable way to reproduce it, I would have give it here… :/

I'll keep an eye at it to see if at some point something rings a bell on what could trigger the issue. I would have like a more complete debug feature to pinpoint the issue.

As for building my own dev build, I can give it a try at some point depending on how to do, but does those builds give more debug information? If so, why not have those in release builds, providing that it's behind a debug flag?

**Comment by bastimeyer** [comment]
> but does those builds give more debug information?

You have the full Chromium dev tools available.
https://github.com/streamlink/streamlink-twitch-gui/blob/v1.10.0/CONTRIBUTING.md#developing-and-building

> why not have those in release builds

The releases are based on the [`normal`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.10.0/build/tasks/configs/nwjs.js#L14) NW.js builds, whereas NW.js SDK builds are used for [running dev builds](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.10.0/build/tasks/webpack/plugins/nwjs.js#L7) and the [test runners](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.10.0/build/tasks/custom/runtest.js#L32). Shipping SDK builds in a release isn't something you should do. The release app files are also minified and optimized, and I'd have to add additional sourcemap files, which add to the overall size of the release.

After I have switched the CI stuff to Github actions (which I will be working on next - I think), I will look into adding nightly builds (#360), which I guess could be based on the NW.js SDK builds. That should make testing and debugging new stuff by volunteers easier.

**Comment by Porkepix** [comment]
(For the record, I haven't been experiencing the issue again recently).
