### ISSUE TITLE
Notifications not displaying

### ISSUE THREAD

**Issue by SyniHD** [streamlink/streamlink-twitch-gui#727]
## Bug report

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Windows 10

**Streamlink Twitch GUI version:**  

Streamlink Twitch GUI 1.9.1

**Streamlink version:**  

Streamlink 1.4.0

**Configuration details:**  

### Description

 Notifications on Windows 10 do not display and test notifications do not pop-up. 

### Expected / Actual behavior

Notifications should display. The test notification button should cause a pop-up notification.

### Reproduction steps

1. Open Streamlink Twitch GUI on Windows 10
2. Settings > Notifications
3. Press Test Notification

### Log output

```
None available.
```

**Comment by bastimeyer** [comment]
> Toast notifications (Windows 8+)
> Native notifications on Windows 8 and above, provided by SnoreToast. To be able to see toast notifications, "banner notifications" need to be enabled in the system settings / control center. Another requirement is a special startmenu shortcut linking to the application which also includes the application ID. SnoreToast automatically creates this special start menu shortcut if it is missing.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications#toast-notifications-windows-8

Make sure that these requirements are set.

**Comment by SyniHD** [comment]
> 
> 
> > Toast notifications (Windows 8+)
> > Native notifications on Windows 8 and above, provided by SnoreToast. To be able to see toast notifications, "banner notifications" need to be enabled in the system settings / control center. Another requirement is a special startmenu shortcut linking to the application which also includes the application ID. SnoreToast automatically creates this special start menu shortcut if it is missing.
> 
> https://github.com/streamlink/streamlink-twitch-gui/wiki/Desktop-notifications#toast-notifications-windows-8
> 
> Make sure that these requirements are set.

The requirements had not been met. I solved it using the reference you provided. Thank you
