### ISSUE TITLE
Google/gstatic call from nwjs helper

### ISSUE THREAD

**Issue by Porkepix** [streamlink/streamlink-twitch-gui#728]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Noticed on macOS 

**Streamlink Twitch GUI version:**  
Version 1.10.0 (1.10.0)

**Streamlink version:**  
1.4.1

### Description

First of all, I understand and I'm almost 100% sure the fault lie in dependencies, and therefore have to be reported there. Looking at informations in the screenshot below, I'd say nw.js is at fault, however search find nothing in their code, see https://github.com/nwjs/nw.js/search?q=gstatic&type=Issues, so the purpose of this issue is mostly to be sure of the dependency.

You'll see in the joined screenshot that thanks to Little Snitch, it could be seen calls to gstatic.com from streamlink-twitch-gui.

### Expected / Actual behavior

Google shouldn't be involved.

### Additional comments, screenshots, etc.

![Screenshot 2020-06-02 at 10 14 18](https://user-images.githubusercontent.com/709500/83683286-6fccad80-a5e5-11ea-8da5-b81f4c18ee9f.png)

**Comment by bastimeyer** [comment]
This is a NW.js platform issue, not an issue of Streamlink Twitch GUI or is dependencies. It seems that some parts of Chromium which call certain Google services have not been stripped off NW.js yet. This can happen when new Chromium changes get merged into NW.js' Chromium fork.

Not sure why you're saying you can't find anything about this on the NW.js issue tracker, because this here is the very first result when clicking on your search query link:
https://github.com/nwjs/nw.js/issues/5865

I can't do anything about this here other than trying to use the latest version. As you can see in the changelog, the currently used NW.js version is 0.45.5, which was the latest stable version when I upgraded it here.
https://nwjs.io/blog/

**Comment by bastimeyer** [comment]
I'm not sure whether I want to close the issue, because as I've said, this is an upstream issue and I don't know when this gets fixed. If this is a major problem, try blocking those requests or comment on the upstream issue(s).

**Comment by Porkepix** [comment]
> This is a NW.js platform issue, not an issue of Streamlink Twitch GUI or is dependencies. It seems that some parts of Chromium which call certain Google services have not been stripped off NW.js yet. This can happen when new Chromium changes get merged into NW.js' Chromium fork.
> 
> Not sure why you're saying you can't find anything about this on the NW.js issue tracker, because this here is the very first result when clicking on your search query link:
> [nwjs/nw.js#5865](https://github.com/nwjs/nw.js/issues/5865)

I didn't meant I can't find anything in issues, that's my bad for pointing to an unsufficiently precise link. I meant I didn't find anything in their code.

**Comment by bastimeyer** [comment]
https://github.com/nwjs/chromium.src/search?q=gstatic&unscoped_q=gstatic

**Comment by Porkepix** [comment]
> https://github.com/nwjs/chromium.src/search?q=gstatic&unscoped_q=gstatic

Oh, it's spitted among different projects. I searched there: https://github.com/nwjs/nw.js/search?q=gstatic&type=Code



> I'm not sure whether I want to close the issue, because as I've said, this is an upstream issue and I don't know when this gets fixed. If this is a major problem, try blocking those requests or comment on the upstream issue(s).

Well I guess that it's up to you whether you consider this important for the project or not, leading the project. I think that unnecessary calls are an annoyance (I also caught one to api.github.com, but for this one I'm not sure what layer issued it and if that's something needed by this project or not, it could be for updates for example). But I would understand that considering it does not directly come from this project, you prefer to close it.
