### ISSUE TITLE
People can be multilingual...

### ISSUE THREAD

**Issue by 0xRainy** [streamlink/streamlink-twitch-gui#732]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
1.10.0

### Description

Unable to select more than one language to filter by

### Expected / Actual behavior

People can speak/understand multiple languages. It should be possible to select multiple languages to filter by.

Surely the removal of this feature is a bug :)

### Reproduction steps

1. Be multilingual
2. Update Streamlink Twitch GUI
3. Be unable to select multiple languages to filter by anymore

**Comment by bastimeyer** [comment]
> Unable to select more than one language to filter by
> Surely the removal of this feature is a bug :)

#706

https://github.com/streamlink/streamlink-twitch-gui/blame/v1.10.0/CHANGELOG.md#L14
