### ISSUE TITLE
Adding a way to browse followed directories

### ISSUE THREAD

**Issue by belug23** [streamlink/streamlink-twitch-gui#734]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

In the followed section we have streams and channels, but it's missing directories. The followed directory is a feature I use almost every day on twitch and it's an important feature to discover new smaller streams playing the games you like.

I understand the majority of watchers go to Fortnite or use the top streams, but I still think this is an important feature.

### Additional comments, screenshots, etc.

![image](https://user-images.githubusercontent.com/1516034/87151871-9b952000-c282-11ea-9c56-270a9b707686.png)

**Comment by bastimeyer** [comment]
> followed directory

Do you mean followed games (now called categories)?

This had to be removed in #684 and it's currently unavailable to third party app developers. See #689.

The Twitch devs [have promised earlier this year to improve the whole API situation](https://discuss.dev.twitch.tv/t/update-on-v5-rate-limiting/24043) after they've received a shitstorm for their new plans and their behavior over the past years, but [they've only made minor improvements so far](https://discuss.dev.twitch.tv/t/announcing-the-latest-helix-endpoints-and-hype-train-api/26530) and the essential stuff is still missing. Once all the (old) features are available, I'm more than happy to (re-)implement them here.

**Comment by belug23** [comment]
Sorry for the duplicate, I tried but I still remember "games" named as "directories". Too bad Twitch decided to not continue with this feature, but it's probably like I said, most viewers go to the top streams or top categories so they probably don't care about the others. At this point, I'm almost surprised it's still an option on twitch.

Thanks for the links and infos.
