### ISSUE TITLE
Since Windows 10 2004 May update, app doesn't launch reliably

### ISSUE THREAD

**Issue by AL-An-4546B** [streamlink/streamlink-twitch-gui#738]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Windows 10 version 2004

**Streamlink Twitch GUI version:**  
v1.10.0

**Streamlink version:**  
v1.4.0

**Configuration details:**  
Nothing specific beside using a RAM Disk to store temp folders (this has been the case for several years, long before the issue started to occur). 

### Description

When launching the app, about 75% of the time the app window won't appear, and I'll have to go kill one of the app processes in the "Details" tab of the task manager in order to relaunch the app, which then launches without trouble. 

If I do nothing the processes remain visible and the app window doesn't appear. 
If I try to launch the app again without killing the processes, I see new processes appear, but the app still doesn't show its window. 
In very rare cases the process crash after a couple of seconds. 

The problem is almost systematic right after booting up the computer, and seems to appear less often if the app has already been launched and closed during the session. 

### Expected / Actual behavior

The app should always start at the first attempt. 

### Reproduction steps

1. Reboot
2. Launch the app (through a shortcut or by launching the exe directly)
3. If the app window doesn't appear in 5-10 seconds, the issue has occurred

### Log output

I started the app by adding the --loglevel debug parameter and managed to reproduce the issue. However when I check (without powering off the computer which would erase the content of the %TMP% folder) the path %TMP%\streamlink-twitch-gui\logs I don't find anything. 

The chrome log file when the issue occurs is available here https://gist.github.com/AL-An-4546B/9f6070db6965ae356b2fc0a062cc05c8

**Comment by bastimeyer** [comment]
> When launching the app, about 75% of the time the app window won't appear

Sounds like a platform issue regarding your system config, but without knowing any details, I can't tell you what's going on.

> I started the app by adding the --loglevel debug parameter

This is meant for app related code, but it won't log NW.js/Chromium debug and error messages. Check this wiki page and see whether you'll find anything useful in the Chromium log output:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

**Comment by AL-An-4546B** [comment]
Thank you for your response. 

> Sounds like a platform issue regarding your system config, but without knowing any details, I can't tell you what's going on.

I specified I'm using a ramdisk to store temp folders, but as I wrote I couldn't find anything else to add. 
Would you need hardware info? Or the version of some software running on my system?

> it won't log NW.js/Chromium debug and error messages. Check this wiki page and see whether you'll find anything useful in the Chromium log output:
> https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

I checked the option --enable-logging --log-level=1 and it did generate a log file in %LOCALAPPDATA%\streamlink-twitch-gui.
I'll try to trigger the issue and post the log I get when it occurs.

**Comment by bastimeyer** [comment]
The log output you've posted unfortunately doesn't say much.
Does this issue also occur when using a clean user data directory? Try deleting your current user data dir or change it via the command line parameter (see the wiki link).

You can also try running a recent debug build from here:
https://github.com/streamlink/streamlink-twitch-gui/actions?query=event%3Aschedule+is%3Asuccess+branch%3Amaster
Make sure that all previous STG processes are terminated first and then see whether the debug build works correctly on your system. If it does not, add the `--remote-debugging-port=8888` parameter and go to `http://localhost:8888` in your web browser, where you will find the chrome remote dev tools.

**Comment by AL-An-4546B** [comment]
> Does this issue also occur when using a clean user data directory? Try deleting your current user data dir

I deleted the folder and reinstalled STG but the issue happened at first try. 

I'll go look into the debug build, thank you for your help.

**Comment by bastimeyer** [comment]
NW.js has been bumped to `0.52.2` in 97717576b4e771843a376155a340439fba8253f8.
The next scheduled debug build will include the new version.

I'm going to close this thread though, as there's not much that can be done here without any useful debug/error logs.
