### ISSUE TITLE
ads are back on Twitch GUI 9/14/20

### ISSUE THREAD

**Issue by TheGloriousArgonaut** [streamlink/streamlink-twitch-gui#745]
## Feature request

- [x ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] This is a feature request and I have read the contribution guidelines.

### Description

ads are back on twitch GUI as of 9/14/20, the ads are a generic built in roll with the twitch logo, I suppose this better than the actual crap ad playing but previous builds were able to bypass this. Any future plans to get around the ad roll for 1.1x+ ?

**Comment by bastimeyer** [comment]
> I understand the difference between _Streamlink_ and _Streamlink Twitch GUI_.

No, you don't.
Streamlink Twitch GUI has nothing to do with streaming. You are asking on the wrong place.

See here
https://github.com/streamlink/streamlink/issues/3120#issuecomment-692309197
