### ISSUE TITLE
Twitch Mid-Roll ads makes popular streams crash

### ISSUE THREAD

**Issue by vohzi** [streamlink/streamlink-twitch-gui#746]
## Bug report

- [ ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [ ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

W10 64bits 
**Streamlink Twitch GUI version:**  

**Streamlink version:**  

**Configuration details:**  

1.10.1

### Description

Stream freezes through VLC every 20-30 minutes approximately and crashes, a reload is necessary. 
PS : I have set streamlink to skip ads.

### Expected / Actual behavior

Ads skipping, not crashing.

### Reproduction steps

Watch 30 minutes of the most popular stream you can find
1. ...
2. ...
3. ...

### Log output

```
REPLACE THIS TEXT WITH THE LOG OUTPUT
```

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/745#issuecomment-693295428
