### ISSUE TITLE
Remember the sort method in followed channels

### ISSUE THREAD

**Issue by CrendKing** [streamlink/streamlink-twitch-gui#747]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

In the top right corner of the "Followed Channels" page, there are several sort options. Once clicked, the channels are sorted, but only for this execution. Once the program is closed and reopened, they revert to default. I also can't find any option to change the behavior. Can we remember the user choice and restore on startup?

### Additional comments, screenshots, etc.

![Streamlink](https://user-images.githubusercontent.com/975235/93725772-7c5e1d00-fb66-11ea-8390-f6d4c93ef114.jpg)

**Comment by bastimeyer** [comment]
The helix API (#849) does not support sorting anymore. The feature will need to be removed.
