### ISSUE TITLE
Opening streams now has Commercial Break 

### ISSUE THREAD

**Issue by Sophon** [streamlink/streamlink-twitch-gui#749]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

Windows 10 latest updates, Linux Mint 20

**Streamlink Twitch GUI version:**  
1.10.0

**Streamlink version:**  
1.5.0

**Configuration details:**  

### Description

Opening streams now have a 15s Commercial Break in Progress.

### Expected / Actual behavior

Stream should open immediately.

### Reproduction steps

1. Open any stream.

**Comment by bastimeyer** [comment]
> * I understand the difference between _Streamlink_ and _Streamlink Twitch GUI_.

https://github.com/streamlink/streamlink-twitch-gui#description

> **Streamlink version:**
> 1.5.0

https://github.com/streamlink/streamlink/releases/latest
