### ISSUE TITLE
Error Couldn't launch the stream | Invalid Version Check Output | Oct 2020

### ISSUE THREAD

**Issue by SatisfactoryBug** [streamlink/streamlink-twitch-gui#752]
Windows 10 x64 / SSD / 128GB RAM

My very first time for Streamlink Twitch GUI

I install Streamlink Twitch GUI v1.10.0 Win x64 after Installed I get these Pop-Up as show in screenshot, Can anybody help ??

I did install streamlink-1.6.0 too just in case but still the same

Oh also when i click Restart, nothing happen, the Close work but not the Restart

![Error Couldn't launch the stream](https://user-images.githubusercontent.com/62482684/94795073-be902580-03d4-11eb-8290-bd7dbea7e307.jpg)

**Comment by bastimeyer** [comment]
> I did install streamlink-1.6.0 too just in case

https://github.com/streamlink/streamlink-twitch-gui/blob/master/README.md#description
https://github.com/streamlink/streamlink-twitch-gui/wiki/Installation

> Invalid Version Check Output 

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration
