### ISSUE TITLE
audio speed/buffering

### ISSUE THREAD

**Issue by mastermind6000** [streamlink/streamlink-twitch-gui#755]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] I tried solving my issue by reading the project's wiki first.
- [x] This is not a bug report or feature request and I have read the contribution guides.

### Environment details

**Operating system and version:**  

**Streamlink Twitch GUI version:**  

1.10.0
**Streamlink version:**  

1.7.0
**Configuration details:**  

using VLC as output player

### Description

At some point after Twitch started forcing the opening and mid-roll ads, I sometimes launch a stream and the audio appears sped up, but is very choppy. As if the audio stream gets stuck, and then tries to increase speed and catch up, increasing it's pitch. If I set VLC to playback at 90% it sounds pretty normal, but still has gaps. I can't connect any other evidence to this phenomenon. It doesn't appear to happen after a mid-roll ad, just when initially launching the stream, but when that happens it seems permanent. Seems to be random when it occurs, across any stream. I switched to HLS passthrough and that does not show the phenomenon, but sometimes that just completely fails to launch the ads and I get nothing anyway. I've reinstalled streamlink, but I can't say if it has been fixed, as it's so random in the first place. I could find no discussion here or elsewhere about audio speed/pitch, so I have no other information to connect or corroborate.
Thanks!

### Expected / Actual behavior

normal audio speed.
not normal audio speed.

### Reproduction steps

1. undetermined. occurrence seems random.

**Comment by bastimeyer** [comment]
> I understand the difference between Streamlink and Streamlink Twitch GUI.

Wrong repo. Streamlink Twitch GUI has nothing to do with streaming. This kind of question belongs on the Streamlink issue tracker.
I've also especially made a sticky thread about this here: #754

But as already said there, you need to use a player that can handle stream discontinuities better, like MPV for example. VLC has problems with that and there's nothing that can be done on the side of Streamlink. Both watching ads and removing them is the same problem, however, removing them might be less problematic for the player's demuxer/decoder as there will only be an issue with the stream's timestamps when playback continues after the ad removal from the output stream.
