### ISSUE TITLE
Add Local User Account

### ISSUE THREAD

**Issue by computeristic** [streamlink/streamlink-twitch-gui#762]
### Checklist

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guides.

### Description

I do not have a twitch account and do not intend on creating one for privacy reasons. I am interested in 10 streamers and checking who is online and streaming becomes tiresome when I have to search for them one by one. A local account with a list of followed streamers would be very convenient; similarly [FreeTube](https://github.com/FreeTubeApp/FreeTube) allows local account creation to show videos from channels the user subscribed to on YouTube. This is similar to #548 but I wanted to give my reasoning and ask if this is still a possible feature addition. @bastimeyer mentioned in #548 that it could be possible to group all the requests into one in order to minimise requests to Twitch. I am not interested in notifications so I do not need constant querying of the server, I just want to see available streams from the list of followed streamers possibly by the press of a button or alternatively upon opening the app.

### Additional comments, screenshots, etc.

Thank you for this neat feature-rich GUI that provides a smooth experience!

**Comment by bastimeyer** [comment]
As already explained in #548, this is limited by the Twitch API and can become very inefficient if the user has a huge local list of locally followed channels. With the upcoming switch to Twitch's helix-API, API requests will be rate-limited and this can't therefore be implemented here, as you'd make too many API requests in a short period of time. I also don't have any motivation for spending time on that and figuring out a way that is simple in its implementation and easy for the user to understand/use.

Just create a throwaway account on Twitch and follow channels regularly.
