### ISSUE TITLE
TwitchGui crashes on startup

### ISSUE THREAD

**Issue by ChubbyBoySlim** [streamlink/streamlink-twitch-gui#763]
Twitchgui crashes on startup, every video start with "Commercial Break in progress" and after the 15sec countdown VLC crashes.
Steps I have taken so far, reinstalled streamlink, twitchgui and VLC but problem persist.

Please le me know how to proceed

Thanks in advance!

:Windows 8.1, x64,  Geforce 1070 TI

TwitchGui 1.10.0
 
Streamlink 1.7.0

[2020-11-21T22:10:14.421Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

[2020-11-21T22:10:24.306Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "gladd",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2020-11-21T22:10:24.249Z",
    "stream": "81628627",
    "channel": "81628627"
}

[2020-11-21T22:10:24.309Z][debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": null,
        "params": null,
        "pythonscript": null
    }
}

[2020-11-21T22:10:24.316Z][debug][StreamingService]
Found streaming provider
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlinkw.exe",
    "params": null,
    "env": null
}

[2020-11-21T22:10:24.323Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--version",
        "--no-version-check"
    ],
    "env": null
}

[2020-11-21T22:10:24.792Z][debug][StreamingService]
Validated streaming provider
{
    "version": "1.7.0"
}

[2020-11-21T22:10:24.839Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--no-version-check",
        "--twitch-disable-hosting",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/gladd",
        "best"
    ],
    "env": null
}

[2020-11-21T22:10:56.615Z][debug][StreamingService]
Preparing to launch stream
{
    "id": "datto",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2020-11-21T22:10:56.577Z",
    "stream": "42296879",
    "channel": "42296879"
}

[2020-11-21T22:10:56.660Z][debug][StreamingService]
Spawning process
{
    "exec": "C:\\Program Files (x86)\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--no-version-check",
        "--twitch-disable-hosting",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/datto",
        "best"
    ],
    "env": null
}

`

**Comment by bastimeyer** [comment]
> TwitchGui crashes on startup
> VLC crashes

This is neither an issue of Streamlink Twitch GUI, nor Streamlink. Closing...

> "Commercial Break in progress"
> after the 15sec countdown VLC crashes

Try filtering out embedded ads by enabling the option in the Twitch GUI's streaming settings menu. Embedded ads are a stream discontinuity in the HLS stream, which means that Streamlink's output consists of two different streams stitched together during an ad-transition, and this may cause issues with your player's demuxer/decoder. Also try updating your player, check its own settings for anything that could potentially cause this (maybe disable GPU acceleration), or try using a different player like MPV for example.

Btw, when using the Streamlink CLI, there's the [`-v` / `--verbose-player` parameter](https://streamlink.github.io/cli.html#cmdoption-verbose-player), which will let you show the player's log output, which may contain information about its crash.
