### ISSUE TITLE
Corrupted video, no audio on twitch.tv

### ISSUE THREAD

**Issue by l0b0** [streamlink/streamlink-twitch-gui#764]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
Arch Linux, up to date as of 2020-12-05.

**Streamlink Twitch GUI version:**  
N/A

**Streamlink version:**  
1.7.0

**Configuration details:**  
None - installation defaults only.

### Description

The video and audio streams are both broken. VLC shows some borked video (see screenshot) and no audio stream. With `-p smplayer` the player opens but doesn't start playing.

### Reproduction steps

1. `streamlink twitch.tv/yogscast best` or `streamlink twitch.tv/yogscast worst`

### Log output

```
$ streamlink --loglevel=debug twitch.tv/yogscast best
[cli][debug] OS:         Linux-5.9.11-arch2-1-x86_64-with-glibc2.32
[cli][debug] Python:     3.9.0
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.25.0), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/yogscast
[plugin.twitch][debug] Getting live HLS streams for yogscast
[utils.l10n][debug] Language code: en_NZ
[cli][info] Available streams: audio_only, 160p (worst), 360p, 480p, 720p, 720p60, 1080p60 (best)
[cli][info] Opening stream: 1080p60 (hls)
[stream.hls][debug] Reloading playlist
[stream.hls][debug] First Sequence: 0; Last Sequence: 2
[stream.hls][debug] Start offset: 0; Duration: None; Start Sequence: 0; End Sequence: None
[stream.hls][debug] Adding segment 0 to queue
[cli][debug] Pre-buffering 8192 bytes
[stream.hls][debug] Adding segment 1 to queue
[stream.hls][debug] Adding segment 2 to queue
[stream.hls][debug] Download of segment 0 complete
[cli][info] Starting player: /usr/bin/vlc
[cli.output][debug] Opening subprocess: /usr/bin/vlc --input-title-format twitch.tv/yogscast -
[stream.hls][debug] Download of segment 1 complete
[stream.hls][debug] Download of segment 2 complete
[cli][debug] Writing stream to output
[stream.hls][debug] Reloading playlist
[stream.hls][debug] Adding segment 3 to queue
[stream.hls][debug] Adding segment 4 to queue
[stream.hls][debug] Adding segment 5 to queue
[stream.hls][debug] Download of segment 3 complete
[cli][info] Player closed
[stream.segmented][debug] Closing worker thread
[stream.segmented][debug] Closing writer thread
[stream.hls][debug] Download of segment 4 complete
[cli][info] Stream ended
[cli][info] Closing currently open stream...
```

### Additional comments, screenshots, etc.

In VLC it looks like this (`streamlink twitch.tv/yogscast worst`): ![Screenshot from 2020-12-05 07-10-03](https://user-images.githubusercontent.com/168301/101198831-fa0cd180-365b-11eb-9077-805ca5c35cbc.png)

**Comment by bastimeyer** [comment]
> I understand the difference between Streamlink and Streamlink Twitch GUI.

Wrong repo... This is the Streamlink Twitch **GUI** repository.

----

> VLC shows some borked video

Make sure that your player is working correctly on its own if you're having issues with the demuxing/decoding/rendering of Streamlink's output. Check for hardware decoding issues, etc.

Streamlink's output of Twitch HLS streams is fine, as you can see when you validate it with FFmpeg. It's a progressive MPEG-TS stream of concatenated MPEG-TS segments with a single h264 video stream (main or high profile), a single AAC audio stream and ID3 metadata tags.

> With -p smplayer the player opens but doesn't start playing.

Regarding smplayer, it doesn't support reading from stdin (see https://github.com/streamlink/streamlink/issues/3388#issuecomment-738084305, which I have just answered yesterday on the Streamlink issue tracker).
