### ISSUE TITLE
Notification when category change

### ISSUE THREAD

**Issue by MannixMD** [streamlink/streamlink-twitch-gui#772]
## Feature request

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

### Description

Would it be possible to get new notification any time a streamer changes category / game they play? Something luke that can be found in chatty.

**Comment by bastimeyer** [comment]
You've already asked here
https://github.com/streamlink/streamlink-twitch-gui/issues/612#issuecomment-674740846
