### ISSUE TITLE
Live streams no longer playable

### ISSUE THREAD

**Issue by esotericDisciple** [streamlink/streamlink-twitch-gui#774]
All I get from Konsole is:
```
[error][StreamingService]
Error: Process exited with code 1
```
Orion claims it has a token issue when trying to load a stream, though twire still works so perhaps streamlink needs to copy over whatever they're doing right now?

**Comment by bastimeyer** [comment]
Streams are working fine. And even if there was a problem with streaming, then it'd be a problem with Streamlink and not Streamlink Twitch GUI.

> Error: Process exited with code 1

Your streamlink process is terminating with error code 1. Check your Streamlink configuration. With the very sparse details you've provided, it's not possible for me to tell you what you've done wrong.

If you start the Twitch GUI with the [`--loglevel debug` parameter](https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l), it'll print the used params during the stream initialization to stdout. Please also make sure that you have not set any Streamlink parameters via config files, as the Twitch GUI won't be aware of those.

**Comment by esotericDisciple** [comment]
Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/bin/streamlink",
        "--twitch-disable-hosting",
        "--twitch-disable-ads",
        "--twitch-low-latency",
        "--player",
        "/usr/bin/mpv",
        "--player-no-close",
        "--hls-live-edge",
        "5",
        "--hls-segment-threads",
        "5",
        "--retry-open",
        "5",
        "twitch.tv/marblecantus",
        "best"
    ],
    "env": null
}
[error][StreamingService]
Error: Process exited with code 1
{
    "id": "marblecantus",
    "quality": "source",
    "low_latency": true,
    "disable_ads": true,
    "chat_open": false,
    "started": "2021-01-14T22:30:27.612Z",
    "stream": "246430834",
    "channel": "246430834"
}Spawning process
{
    "exec": "/usr/bin/python",
    "params": [
        "/usr/bin/streamlink",
        "--twitch-disable-hosting",
        "--twitch-disable-ads",
        "--twitch-low-latency",
        "--player",
        "/usr/bin/mpv",
        "--player-no-close",
        "--hls-live-edge",
        "5",
        "--hls-segment-threads",
        "5",
        "--retry-open",
        "5",
        "twitch.tv/marblecantus",
        "best"
    ],
    "env": null
}
[error][StreamingService]
Error: Process exited with code 1
{
    "id": "marblecantus",
    "quality": "source",
    "low_latency": true,
    "disable_ads": true,
    "chat_open": false,
    "started": "2021-01-14T22:30:27.612Z",
    "stream": "246430834",
    "channel": "246430834"
}
The Waterfox Twitch Alternate Player addon might have another hint: "Channel with the specified name does not exist. Perhaps you typed the wrong address."

**Comment by esotericDisciple** [comment]
This seems to be a issue with all linux desktop third-party twitch apps, I haven't touched the config file...If I had time and patience for text editing I wouldn't be using GUIs, which is why I thought this was supposed to go to discussions since I'm here for customer service, not for joining the devteam

**Comment by bastimeyer** [comment]
> I'm here for customer service

This is a FOSS project, so there will never be "customer service", because there are no "customers". If you however provide enough details, I will try to help you with your issue.

> This seems to be a issue with all linux desktop third-party twitch apps

No. As already said, your streamlink process is terminating with error code 1, for whatever reason. This looks like a streamlink/python setup issue on your system.

If you take a look at the log output you've just posted, you can reconstruct the Streamlink launch command and run it from the command line shell, and continue debugging from there.

Post the output of this:
```bash
/usr/bin/python \
  /usr/bin/streamlink \
  --loglevel debug \
  --twitch-disable-hosting \
  --twitch-disable-ads \
  --twitch-low-latency \
  --player /usr/bin/mpv \
  --player-no-close \
  --hls-live-edge 5 \
  --hls-segment-threads 5 \
  --retry-open 5 \
  twitch.tv/marblecantus \
  best
```

**Comment by esotericDisciple** [comment]
```
[cli][debug] OS:         Linux-5.4.85-1-MANJARO-x86_64-with-glibc2.32
[cli][debug] Python:     3.9.1
[cli][debug] Streamlink: 1.7.0
[cli][debug] Requests(2.25.1), Socks(1.7.1), Websocket(0.57.0)
[cli][info] Found matching plugin twitch for URL twitch.tv/marblecantus
[cli][debug] Plugin specific arguments:
[cli][debug]  --twitch-disable-hosting=True (disable_hosting)
[cli][debug]  --twitch-disable-ads=True (disable_ads)
[cli][debug]  --twitch-low-latency=True (low_latency)
[plugin.twitch][debug] Getting live HLS streams for marblecantus
error: No playable streams found on this URL: twitch.tv/marblecantus
```
It gives the same error that I said https://addons.mozilla.org/en-US/firefox/addon/twitch_5/ was having for ALL of my followed channels...shouldn't that imply an API issue?

**Comment by bastimeyer** [comment]
> Streamlink: 1.7.0

You are using outdated versions. The latest Streamlink version is `2.0.0`, which is required by the latest Twitch GUI version, which is `v1.11.0`.

Streamlink 2.0.0 has switched the streaming access token acquirement method from the old private API to Twitch's GQL API, and this is working fine. When I switch back to 1.7.0, I'm seeing the same error, so make sure that you're using the **latest version**.

And as said, this is the Twitch GUI repo, so anything streaming related is off-topic here, as the Twitch GUI is just a launcher for Streamlink.

**Comment by esotericDisciple** [comment]
Why didn't you push that version to Manjaro's repos?

**Comment by esotericDisciple** [comment]
Well, at least the AUR+git versions build and install works...and now streams are watchable again...

**Comment by bastimeyer** [comment]
That's not how packaging on Linux works. Different people maintain those packages, so if you're on a distro that doesn't get updated in time, then notify the responsible package maintainers or switch to a better or more up2date distro.

I always update the Twitch GUI AUR package immediately after publishing a new release:
- https://github.com/streamlink/streamlink-twitch-gui/releases/tag/v1.11.0
- https://aur.archlinux.org/cgit/aur.git/log/?h=streamlink-twitch-gui

And the `streamlink` package of Arch Linux has been bumped on the same day Streamlink had its `2.0.0`:
- https://github.com/streamlink/streamlink/releases/tag/2.0.0
- https://github.com/archlinux/svntogit-community/commits/packages/streamlink/trunk

So if you're having issues on manjaro, then they've either haven't updated their streamlink package yet (which btw may just be a delayed copy of the Arch package repos, as always), or your local mirror is out of date.

Either way, not an issue. If you had used the issue template and filled in the details it's asking for, like the Streamlink version, I could have told you this immediately.

**Comment by esotericDisciple** [comment]
sorry about my crankiness yesterday
