### ISSUE TITLE
This Json error has been persistent for the last year+

### ISSUE THREAD

**Issue by jstrat231** [streamlink/streamlink-twitch-gui#780]
### Checklist

- [x ] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] I tried solving my issue by reading the project's wiki first.
- [x ] This is not a bug report or feature request and I have read the contribution guides.

I'm not a coder or anyone that understands anything about how any of this works. All I used to do was type streamlink twitch.tv/lsdkjdlskdkld best   and it always worked. This stopped working a year ago and it doesn't matter what version of Streamlink I use, I always get greeted with the following message:

https://ibb.co/Yb4zC81

This happens to every single Twitch page and it doesn't even load up YouTube streams either. For YouTube it says no playable streams found. Can someone please help me fix this? Thank you

**Comment by bastimeyer** [comment]
Wrong repo. This is **Streamlink Twitch GUI**, not **Streamlink**

You are using an **outdated** Streamlink version. Make sure to be using the **latest** version.
