### ISSUE TITLE
Game names show with the title for streams

### ISSUE THREAD

**Issue by RossM1993** [streamlink/streamlink-twitch-gui#788]
Feature request
- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a feature request and I have read the contribution guidelines.

Description

Please could there be the game title in the GUI for streams or have this be an option. This would be where the title is shown when hovering over the thumbnails.

**Comment by bastimeyer** [comment]
There's already an option for this in the settings->streams menu, called "Info bar content" with the default being the "Stream title". Just select the "Game being played" option.

**Comment by RossM1993** [comment]
Ahh, thank you very much! I somehow missed this!
