### ISSUE TITLE
Stream titles always display without hovering over thumbnails

### ISSUE THREAD

**Issue by RossM1993** [streamlink/streamlink-twitch-gui#789]
Feature request

- [x] I understand the difference between Streamlink and Streamlink Twitch GUI.
- [x] This is a feature request and I have read the contribution guidelines.

Description

Please could there be an option for stream titles to always display without the need to hover over them. This is where the user needs to hover their cursor over thumbnails to see the stream title. This is also linked to feature request #788 where the game name would always display too.

**Comment by bastimeyer** [comment]
And there's also already an option for that in the settings->streams menu, called "Info bar". Please do at least a bit of research before opening issues.
