### ISSUE TITLE
Option to disable HW acceleration/GPU in the GUI

### ISSUE THREAD

**Issue by skules** [streamlink/streamlink-twitch-gui#790]
## Feature request

- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a feature request and I have read the contribution guidelines.

### Description

Option to disable HW acceleration/GPU in the GUI itself.

I upgraded from nvidia drivers 457.09 to 465.89 and since then the GUI opens in a black screen unless I use the disable GPU parameter. I have the shortcut pinned to my taskbar but it opens it in another section, rather than itself. 

![image](https://user-images.githubusercontent.com/8022147/113312386-241c8a80-9302-11eb-8efb-0d490ce8bac3.png)

Would be great to have an option to disable HW acceleration/GPU in the GUI itself to avoid this issue.

**Comment by bastimeyer** [comment]
Chromium's hardware acceleration can't be changed at runtime, which means an option can't be added to the settings. You'll have to set the `--disable-gpu` command line parameter for that.

See the wiki for all available parameters:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

> I have the shortcut pinned to my taskbar but it opens it in another section, rather than itself.

This is an NW.js issue which has been present for some time now. I can't do anything about it here downstream. I'll look into upgrading to the latest version when I have the time, as it's currently a couple of versions behind.

**Comment by skules** [comment]
Thanks
