### ISSUE TITLE
GUI crashing on macOS Big Sur

### ISSUE THREAD

**Issue by taalas** [streamlink/streamlink-twitch-gui#793]
## Bug report

- [x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  
macOS 11.2

**Streamlink Twitch GUI version:**  
1.11.0 (homebrew)

**Streamlink version:**  
2.1.1 (homebrew)

### Description

While using the Streamlink Twitch GUI, on random occasions, the program exits without any visible cause (window disappears, process disappears). Not sure if this is a known issue, but since there is no issue for this yet, I thought it would be good to add this. Is there any way I can provide more information?

### Expected / Actual behavior

GUI stays visible and usable

### Reproduction steps

Open GUI, use GUI

**Comment by bastimeyer** [comment]
> Is there any way I can provide more information?

You could post the error log
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

but apart from that, there's not much that can be done here other than upgrading to the latest NW.js version, as the JS application code should not be responsible for crashing NW.js. The version [used in `v1.11.0` is `0.45.5`](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.11.0/src/config/main.json#L4), which is from May 2020.

**Comment by bastimeyer** [comment]
I'm going to close this thread now, as there's nothing that can be done here about upstream/platform issues other than upgrading to the latest version.
NW.js has been bumped to `0.52.2` just now: 97717576b4e771843a376155a340439fba8253f8

The next scheduled debug build will include the new NW.js version. Please check and see if this resolves your issues. If not, post an error log.
