### ISSUE TITLE
Can't take a screenshot

### ISSUE THREAD

**Issue by lennie420** [streamlink/streamlink-twitch-gui#802]
## Bug report

- [ x] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [x ] This is a bug report and I have read the contribution guidelines.

### Environment details

**Operating system and version:**  

Arch Linux (5.12.9-arch1-1)

**Streamlink Twitch GUI version:**  

v1.11.0

**Streamlink version:**  

streamlink 2.1.1-1

**Configuration details:**  

### Description

Can't take a screenshot using the s-key shortcut for mpv. I get "Error writing screenshot!" message appear. I have tested using just streamlink -p mpv and a screenshot is taken as expected.

### Expected / Actual behavior

Take a screenshot.

### Reproduction steps

1. Start stream
2. Press s to take a screenshot
3. Error occurs

### Log output

```
streamlink-twitch-gui --loglevel debug
[6304:6304:0607/174100.676010:ERROR:component_loader.cc(169)] Failed to parse extension manifest.
[6304:6333:0607/174100.683272:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.DBus.Properties.Get: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[6304:6333:0607/174100.683429:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.GetDisplayDevice: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[6304:6333:0607/174100.683556:ERROR:object_proxy.cc(632)] Failed to call method: org.freedesktop.UPower.EnumerateDevices: object_path= /org/freedesktop/UPower: org.freedesktop.DBus.Error.ServiceUnknown: The name org.freedesktop.UPower was not provided by any .service files
[6325:6325:0607/174100.755707:ERROR:sandbox_linux.cc(376)] InitializeSandbox() called with multiple threads in process gpu-process.
[debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": false,
    "version-check": false,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
[debug][StreamingService]
Preparing to launch stream
{
    "id": "weplaydota",
    "quality": "source",
    "low_latency": false,
    "disable_ads": false,
    "chat_open": false,
    "started": "2021-06-07T16:41:06.680Z",
    "stream": "67794893",
    "channel": "67794893"
}
[debug][StreamingService]
Resolving streaming provider
{
    "provider": "streamlink",
    "providerUserData": {
        "exec": null,
        "params": null,
        "pythonscript": null
    }
}
[debug][StreamingService]
Found streaming provider
{
    "exec": "/usr/bin/streamlink",
    "params": null,
    "env": null
}
[debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/streamlink",
    "params": [
        "--version"
    ],
    "env": null
}
[debug][StreamingService]
Validated streaming provider
{
    "version": "2.1.1"
}
[debug][StreamingService]
Resolving player
{
    "player": "mpv",
    "playerUserData": {
        "close": true,
        "title": true,
        "media-title": true,
        "minimal": false,
        "window": true,
        "seeking": true,
        "no-cache": false,
        "exec": null,
        "args": null,
        "type": "settings-streaming-player-mpv"
    }
}
[debug][StreamingService]
Resolved player
{
    "exec": "/usr/bin/mpv",
    "params": "--keep-open=no \"--title=$>{name} - {game} - {status}\" \"--force-media-title={name} - {game} - {status}\" --force-window=yes --force-seekable=yes --hr-seek=yes --hr-seek-framedrop=yes",
    "env": null
}
[debug][StreamingService]
Spawning process
{
    "exec": "/usr/bin/streamlink",
    "params": [
        "--twitch-disable-hosting",
        "--player",
        "/usr/bin/mpv",
        "--player-args",
        "--keep-open=no \"--title=$>WePlayDota - Dota 2 - Team Nigma vs Beastcoast | ODPixel & Fogged | WePlay AniMajor | Group Stage | RadiantGreen\" \"--force-media-title=WePlayDota - Dota 2 - Team Nigma vs Beastcoast | ODPixel & Fogged | WePlay AniMajor | Group Stage | RadiantGreen\" --force-window=yes --force-seekable=yes --hr-seek=yes --hr-seek-framedrop=yes",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/weplaydota",
        "best"
    ],
    "env": null
}
```

**Comment by bastimeyer** [comment]
Why did this issue re-appear all of a sudden? It got nuked by Github immediately after being posted and I couldn't access it anymore for multiple days, so I stopped trying eventually.

Now to your issue, Streamlink Twitch GUI doesn't launch the player executable, this is done by Streamlink instead, and the Twitch GUI does only resolve custom player paths if they are set in the player settings menu (or when selecting a player preset) to be able to provide better error messages when the player could not be found on the system.

This means that nothing in regards to the player environment or config is being done except some default Streamlink `--player-args` values, depending on the selected player preset and the selected player parameters. As you can see in the debug log, those MPV parameters are `--keep-open=no`, `--title=TITLE`, `--force-media-title=TITLE`, `--force-window=yes`, `--force-seekable=yes`, `--hr-seek=yes`, and `--hr-seek-framedrop=yes`, as you selected those options and didn't set additional custom MPV parameters.

> Error writing screenshot!

This could mean that MPV is trying to write to a directory where it doesn't have write permissions with the user it's currently being run with. The user is of course inherited from Streamlink, which inherits its user from the Twitch GUI, same with any environment variables, eg. `HOME`. Make sure that nothing funny is going on your system with how you start the Twitch GUI and how you've configured your system.

Closing, as it's not a Twitch GUI issue and this is all I can do to guide you to a solution. Good luck.

**Comment by lennie420** [comment]
Hi @bastimeyer thanks for your reply. After I posted this GitHub flagged my account for some reason. Had to go through support to try get it sorted.

I built the package using AUR.

I have now built the package manually and created a symbolic link to launch and confirm taking a screenshot is working as intended.

Thanks for your help. Peace, love and happiness :)
