### ISSUE TITLE
error: couldn't launch stream due to invalid version check output once updating to new streamlink 2.2.0

### ISSUE THREAD

**Issue by jpancake** [streamlink/streamlink-twitch-gui#804]
### Environment details

**Operating system and version:**  
Windows 10

**Streamlink Twitch GUI version:**  
v1.11

**Streamlink version:**  
2.2.0

### Description

I recently updated to the new streamlink 2.2.0 and when I attempt to load stream on the GUI I receive error

"Invalid version check output"

### Expected / Actual behavior

Stream to play

**Comment by bastimeyer** [comment]
Make sure that `streamlink --version` is not printing any error messages.

https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration#unexpected-version-check-output-error

Streamlink 2.2.0 has deprecated old config paths, as you can read in the changelog, but that shouldn't cause any issues in regards to the output of `--version`.
