### ISSUE TITLE
Player preset volume parameters

### ISSUE THREAD

**Issue by Nullvaettr** [streamlink/streamlink-twitch-gui#808]
## Feature request
- [X] I understand the difference between *Streamlink* and *Streamlink Twitch GUI*.
- [X] This is a feature request and I have read the contribution guidelines.

### Description
Add an option to allow us to choose the default volume when a stream starts.

### Additional comments, screenshots, etc.
I can't count the number of times my ears scream in pain when a streamer screams at the start of the stream...

**Comment by bastimeyer** [comment]
This depends on your chosen video player and its available command line parameters, so there's no universal way to do it. Volume input fields could be added to player presets where the players does support such command line parameters, but the presets currently don't support number inputs.

If you're using MPV, you can simply add `--volume=0.5` to the custom player parameters input field in the player settings menu.
https://mpv.io/manual/stable/

If you're using VLC, add `--volume 0.5 --no-volume-save`.
https://github.com/streamlink/streamlink/discussions/3783

**Comment by Nullvaettr** [comment]
Thank you for your answer!

**Comment by bastimeyer** [comment]
Let's keep this thread open as a feature request
