### ISSUE TITLE
Feature Request: Send notification to notify-send on Linux

### ISSUE THREAD

**Issue by danrobi11** [streamlink/streamlink-twitch-gui#811]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Non-technical user here.

I've enabled the desktop notification option for a few streamers and I never got any desktop notifications. 

I use the [dunst](https://github.com/dunst-project/dunst) notification daemon

Therefore, I assume that `streamlink-twitch-gui` does not send the desktop notifications through `notify-send` on Linux?

I might be wrong tho :/

streamlink-twitch-gui v1.11.0 appimage
OS: MX 19.4 (patito feo) x86_64 based Debian GNU/Linux 10 (buster)
Kernel: 5.10.0-5mx-amd64

**Comment by bastimeyer** [comment]
The `notify-send` CLI utility, which is part of `libnotify`, uses the [`org.freedesktop.Notifications` DBus interface](https://people.gnome.org/~mccann/docs/notification-spec/notification-spec-latest.html) to dispatch notifications.

[NW.js / Chromium implements this DBus interface directly](https://github.com/nwjs/chromium.src/blob/nw52/chrome/browser/notifications/notification_platform_bridge_linux.cc#L61-L62), which means adding a notification profile for a `notify-send` wrapper to Streamlink Twitch GUI doesn't make much sense. In earlier versions there already was a similar native Linux notification implementation, [based on the `gdbus` CLI utility](https://github.com/streamlink/streamlink-twitch-gui/blob/v1.3.0/src/app/utils/notification/NotificationProviderFreedesktop.js), but that got replaced by the available Chromium APIs for obvious reasons.

If you're not seeing any notifications from certain applications, then it's probably the fault of the notification daemon (or its configuration), which reads notifications on this same DBus interface. Make sure that you have not disabled any applications or changed any other configurations. The appimage should not be at fault here, as it's not run in a sandboxed environment like flatpaks or snaps.

To give you a bit of help debugging this, if you run this from your command line shell, you can see all the notifications (for the current user) that are being sent on the DBus interface, which should include those of Streamlink Twitch GUI:
```sh
gdbus monitor --session --dest org.freedesktop.Notifications --object-path /org/freedesktop/Notifications
```
