### ISSUE TITLE
Twitch VODs

### ISSUE THREAD

**Issue by jgsource** [streamlink/streamlink-twitch-gui#833]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Are VODs planned in development? I don't seem to see such functionality in the launcher.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/81#issuecomment-314374666
