### ISSUE TITLE
Danmaku Style Chat

### ISSUE THREAD

**Issue by focusedup** [streamlink/streamlink-twitch-gui#840]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

There are various browser extensions that pull chat messages and display them over the video stream in "danmaku" style. I think this would be a neat feature for streamlink-GUI if possible. Github for the extension I use is here: https://github.com/wheatup/TwitchChatDanmaku/blob/master/CHANGELOG.md.

**Comment by bastimeyer** [comment]
Streamlink Twitch GUI is not a chat application.
