### ISSUE TITLE
As of 3.0.0, Streamlink no longer supports --rtmp-rtmpdump, seemingly completely breaking steamlink-twitch-gui

### ISSUE THREAD

**Issue by ScottRFrost** [streamlink/streamlink-twitch-gui#841]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v1.13.0

### Streamlink version

3.0.1

### Operating system, environment and configuration details

W11 x64

### Description

As seen at https://github.com/streamlink/streamlink/releases/tag/3.0.0 , `--rtmp-rtmpdump` is gone in Streamlink.  I'm unable to watch any streams after updating Streamlink because of it.

### Debug log

```text
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe twitch.tv/joshog best
```

**Comment by bastimeyer** [comment]
Not a Streamlink Twitch GUI problem.

As noted in the Streamlink 3.0.0 changelog, **you will have to update your default Streamlink config file**.
https://github.com/streamlink/streamlink/blame/master/CHANGELOG.md#L27-L29
