### ISSUE TITLE
Seeking with streamlink-twitch-gui and mpv not working

### ISSUE THREAD

**Issue by JeffR1992** [streamlink/streamlink-twitch-gui#848]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

1.13.0

### Streamlink version

2.4.0

### Operating system, environment and configuration details

Windows 11 21H2

### Description

I'm using streamlink + streamlink-twitch-gui + mpv, and have seeking enabled, but when I try and seek backwards using the left arrow key, the stream hangs for about a second but then goes back to the live stream time (i.e. I cannot rewind). Is this a known issue and if so, is there a way to solve this problem? Thanks.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/wiki/Recommendations#player-configuration
