### ISSUE TITLE
Error opening player since update

### ISSUE THREAD

**Issue by Aschenbecher** [streamlink/streamlink-twitch-gui#862]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.0.0

### Streamlink version

3.11

### Operating system, environment and configuration details

Windows 10

### Description

Since last update of Twitch gui and streamlink I cant open streams anymore, see error message below. It happens with MPV player and VLC, before the update everything was fine.
someone has an idea whats going wrong?

### Debug log

```text
ERROR
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe twitch.tv/bonjwa best
```

**Comment by bastimeyer** [comment]
#842
