### ISSUE TITLE
Youtube add on

### ISSUE THREAD

**Issue by TBO1981** [streamlink/streamlink-twitch-gui#875]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

I'm just wondering if anyone is already or if possible to add youtube to this gui, or maybe make a separate one, sorry if this isn't the place, still kinda new to all this and if anyone already knows of something similar plz just let me know. just an idea of having both, I thought there was a time it was the case, could have been a dream lol. anyway. I do have a batch file I made that isn't 2 hard to add new streams, but this gui is so user friendly

**Comment by bastimeyer** [comment]
I've already answered this question multiple times over the past years on this issue tracker, for various other platforms. Not going to happen.

**Comment by TBO1981** [comment]
Thats fine, I searcher, didn't find a yes or no answer, I'll stick with my batch file
