### ISSUE TITLE
building on arm

### ISSUE THREAD

**Issue by brettowe** [streamlink/streamlink-twitch-gui#878]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2

### Operating system, environment and configuration details

Raspberry PI OS 64bit

### Description

was attempting to build the package on my pi400 I was trying to run the grunt build command and it just fails at the NWjs related section.
so I'm wondering if there is a missing step in this

also curious if rather than working on this direction if working on making a functional appimage would be more useful
but not sure what is needed for creating/testing that idea either however as I didn't see any documents related to that.

**Comment by bastimeyer** [comment]
NW.js is not available on ARM (neither Linux nor macOS), so you can't run Streamlink Twitch GUI on a PI or similar platforms. There are community forks of NW.js for armv7 (and aarch64 I believe), but this is all just a hacky solution which I won't support here, especially considering that it's not supported by nw-builder which is used to download nwjs binaries and to assemble production builds. I have already provided help years ago with this via a branch with custom build options, but this got outdated very quickly. You'll have to figure this out on your own. Good luck.
