### ISSUE TITLE
have a toggle for vlc to have a minimal interface 

### ISSUE THREAD

**Issue by killertofus** [streamlink/streamlink-twitch-gui#881]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

have a toggle for vlc to have a minimal interface on load of a stream

**Comment by bastimeyer** [comment]
This already exists. Select the VLC player preset in the player settings menu and toggle the minimal layout button in the VLC options.

Or set VLC's `--qt-minimal-view` parameter yourself via any of the available methods.

- https://github.com/streamlink/streamlink-twitch-gui/wiki/Player-configuration
- https://streamlink.github.io/cli.html#player-options
- https://github.com/streamlink/streamlink-twitch-gui/blame/v2.0.0/src/config/players.json#L50-L59
