### ISSUE TITLE
unrecognized arguments rtmpdump

### ISSUE THREAD

**Issue by pbsk8** [streamlink/streamlink-twitch-gui#883]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.0

### Streamlink version

3.2.0

### Operating system, environment and configuration details

Windows 11 x64 

### Description

Since streamlink gui was updated to 2.0 and streamlink to 3.2.0, I get this error whenever I try to run any stream

**usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: --rtmp-rtmpdump=rtmpdump.exe --hds-segment-threads=9**

printscreen below:

https://i.postimg.cc/90dCShzK/sl.png

I dont know what to do.

**Comment by bastimeyer** [comment]
> I dont know what to do.

https://github.com/streamlink/streamlink-twitch-gui/issues/842#issuecomment-973369948
