### ISSUE TITLE
Can't open the app in Debian 11 Bullseye

### ISSUE THREAD

**Issue by Grimzon** [streamlink/streamlink-twitch-gui#885]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.0.0

### Operating system, environment and configuration details

Debian 11 Bullseye

### Description

I cant open the app. 
Get the following message when trying to open via the terminal. 

### Debug log

```text
me@debian:~/TwitchGUI/streamlink-twitch-gui$ ./streamlink-twitch-gui 
Opening in existing browser session.
me@debian:~/TwitchGUI/streamlink-twitch-gui$ [36279:36279:0401/171922.215805:ERROR:sandbox_linux.cc(380)] InitializeSandbox() called with multiple threads in process gpu-process.
```

**Comment by bastimeyer** [comment]
> Opening in existing browser session.

You've already opened an instance of the program. Only one can exist at the same time. Additional launch attempts will pass the launch arguments to the main process, where it will be handled instead, if you've enabled that feature in the settings menu (requires advanced settings), but that's not relevant here.

Check your system's running processes (eg. via `htop`, `top`, `ps`, etc.) and kill the existing process tree of Streamlink Twitch GUI in case the processes of a previous session didn't terminate correctly for whatever reason while trying to close the app. If that happens again, you should check for any stderr messages when trying to close the main process. Maybe also check the Chromium debug log output:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#nwjs--chromium-parameters

**Comment by Grimzon** [comment]
Thanks it's working now

Op vr 1 apr. 2022 17:38 schreef Sebastian Meyer ***@***.***>:
