### ISSUE TITLE
`/helix/channels` is returning a 500 Internal Server Error response (stream lists don't load / are empty)

### ISSUE THREAD

**Issue by bastimeyer** [streamlink/streamlink-twitch-gui#887]
There's currently an outage on the Twitch API and it returns 500 error codes (Internal Server Error) on the `/helix/channels` API endpoint which is required for querying certain channel data. This affects all stream lists, like top streams, followed streams, followed channels, etc.

As I already mentioned on Gitter/Matrix, this is caused when requesting more than 6 `broadcaster_id`s on the `/helix/channels` API endpoint. 7 or more returns in an error code 500.
https://gitter.im/streamlink/streamlink-twitch-gui?at=625475f1257a35782572b131

I can fix this here by limiting the number of IDs in a single request, which would increase the number of requests that need to be made to the API. Since API requests are rate limited, this is not good, but the limit is high enough so that this shouldn't be a problem.

I'll push a workaround soon.

**Comment by bastimeyer** [comment]
Looks like it is in fact not caused by the number of requested `broadcaster_id`s. This seems to be caused by certain IDs themselves, so this might be an issue with their database cluster and internal network. I'm afraid I can't add a workaround.

```sh
curl 'https://api.twitch.tv/helix/channels?broadcaster_id=31239503' \
  -H 'authorization: Bearer YOUR_OAUTH_TOKEN' \
  -H 'client-id: phiay4sq36lfv9zu7cbqwz2ndnesfd8'
```
```json
{"data":[{"broadcaster_id":"31239503","broadcaster_login":"esl_csgo","broadcaster_name":"ESL_CSGO","broadcaster_language":"en","game_id":"32399","game_name":"Counter-Strike: Global Offensive","title":"RERUN: Outsiders vs. FaZe - Map 2 [Dust2] - ESL Pro League Season 15 - Group B","delay":0}]}
```

```sh
curl 'https://api.twitch.tv/helix/channels?broadcaster_id=26301881&broadcaster_id=23161357&broadcaster_id=108268890&broadcaster_id=50160915&broadcaster_id=49440419&broadcaster_id=39176440&broadcaster_id=31239503' \
  -H 'authorization: Bearer YOUR_OAUTH_TOKEN' \
  -H 'client-id: phiay4sq36lfv9zu7cbqwz2ndnesfd8'
```
```json
{"error":"Internal Server Error","status":500,"message":""}
```

**Comment by bastimeyer** [comment]
I've opened an issue on the twitchdev/issues repo. I am not sure though if any Twitch devs will notice, because they haven't been particularly active over there in the past. This issue may also need to be reported on their dev forums.

**Comment by August40th** [comment]
Maybe due to country/region ? I'm noticing the French channels that are live that I follow are all here but nothing else

**Comment by bastimeyer** [comment]
I have reported this on the twitchdev/issues repo as well as the twitch dev forums, and there's been a response already 50 minutes ago or so

> We have started investigating. Thank you for reporting this

**Comment by idle5** [comment]
I'm experiencing similar issues (error code 500, no lists populating, unable to display the streamer page) and a workaround I've found is by using Chatterino with the Streamlink Twitch GUI installed. 

1. Have the 'Streamlink Twitch GUI' application opened. 
2. Adding the respective channel you want to watch (channel must be online)
3. [Select the more options drop down menu](https://i.imgur.com/3XfYz7X.png)
4. Open in streamlink 

Hope this might help someone!

**Comment by bubibubibub** [comment]
That has nothing to do with Streamlink Twitch GUI though. That's just Chatterino directly adressing Streamlink which you have installed because Streamlink Twitch GUI needs it. So it's less of a workaround and more of another way of using Streamlink which for example you could also do via command prompt.

**Comment by idle5** [comment]
> That has nothing to do with Streamlink Twitch GUI though. That's just Chatterino directly adressing Streamlink which you have installed because Streamlink Twitch GUI needs it. So it's less of a workaround and more of another way of using Streamlink which for example you could also do via command prompt.

Thanks for the clarification, I don't have much knowledge of what's really going on in the backend but I edited my comment to better reflect what someone could do to open a stream while the API issue exists.

**Comment by bigjuice01** [comment]
> I'm experiencing similar issues (error code 500, no lists populating, unable to display the streamer page) and I've been able to open streams by using Chatterino with the Streamlink Twitch GUI installed.
> 
> 1. Have the 'Streamlink Twitch GUI' application opened.
> 2. Adding the respective channel you want to watch (channel must be online)
> 3. [Select the more options drop down menu](https://i.imgur.com/3XfYz7X.png)
> 4. Open in streamlink
> 
> Hope this might help someone!

it did work but only the audio loaded, not the video

**Comment by bubibubibub** [comment]
> Have the 'Streamlink Twitch GUI' application opened.

You also don't need that part when using Chatterino to start streams via Streamlink.

> it did work but only the audio loaded, not the video

You need to set the preferred quality in Chatterino.

**Comment by mrk-han** [comment]
Is there a way to get debug settings of how our Streamlink GUI is launching our Streamlink/MPV so we can copy those settings and use for now as a workaround?

I really want to launch from Chatterino using the exact same settings but I can't seem to replicate.

Thanks @bastimeyer for looking into this so quickly.

**Comment by bastimeyer** [comment]
- https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#--loglevel--l
- https://streamlink.github.io/latest/cli.html

**Comment by Tauli-gif** [comment]
I hope the problem can be solved.

**Comment by bastimeyer** [comment]
I've pushed the [`temp-workaround-issue-887`](https://github.com/streamlink/streamlink-twitch-gui/compare/temp-workaround-issue-887) branch to the repo which you can build the app from (see 868b777a83232a66100fa4e3ddd97ce4d38c5893).

This limits the number of `broadcaster_id` parameters of each `/helix/channels` API request to at most 1. Requesting only one ID seems to be stable and doesn't cause any status code 500 responses.

**This is however incredibly stupid and inefficient**, and it's not how the API endpoint is supposed to be used. Usually up to 100 IDs will get queried in one go. Remember that the Twitch API is rate limited, so browsing lots of streams/channels will make a single `/helix/channels` API request for every stream/channel item that gets shown (unless the data has already been cached), and this may result in running into the max-API-requests-per-minute limitation.

Build instructions can be found as usual here, but I'll post them here as well:
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md#developing-and-building

```sh
# get the source code
git clone https://github.com/streamlink/streamlink-twitch-gui
cd streamlink-twitch-gui
git checkout origin/temp-workaround-issue-887

# install dependencies
yarn install --pure-lockfile
# build - see the build/releases/streamlink-twitch-gui directory afterwards
yarn run grunt release
```

Be aware that this includes the [latest changes of the `master` branch](https://github.com/streamlink/streamlink-twitch-gui/blob/425225a4ebeab2dd415cdadd055dbfe136d6a37e/CHANGELOG.md#master) ([git history](https://github.com/streamlink/streamlink-twitch-gui/compare/v2.0.0...master)), which has bumped the NW.js version to 0.62, which means if you go back (downgrade) to 2.0.0, then you will run an older NW.js version after having upgraded the local NW.js app config by running this version, which could cause issues. Back up your Streamlink Twitch GUI config directory first, aka the app's user-data-directory:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters#user-data-directory

----

That's all I can do for now. It's up to Twitch to fix this. If they don't fix this any time soon, then I will probably have to apply these changes permanently or remove the features that rely on data that is read from the broken API endpoint, but I doubt that this will be necessary. Depending on their work schedule though, it is unknown when this API issue will be fixed, so be patient.

**Comment by bastimeyer** [comment]
Quick update... Twitch is now returning this instead of error code 500

```json
{"error":"Too Many Requests","status":429,"message":"too many requests"}
```

but it's not reliable/deterministic. Sometimes it returns data, sometimes it does not. Tested this by querying the same IDs multiple times.

**Comment by davidvkimball** [comment]
> I'm experiencing similar issues (error code 500, no lists populating, unable to display the streamer page) and I've been opening streams manually by using Chatterino with the Streamlink Twitch GUI (STG) installed.
> 
>     1. In Chatterino Settings -> External Tools -> Streamlink : Make sure the preferred quality is set to something other than Audio Only
> 
>     2. Add the respective channel you want to watch (channel should be online)
> 
>     3. [Select the more options drop down menu](https://i.imgur.com/3XfYz7X.png)
> 
>     4. Open in streamlink
> 
> 
> Hope this might help someone!

This helped heaps, thank you!

**Comment by arrowgent** [comment]
its not just you,  chatty and my own Bash script have the same error with different oauth.

i can say this started as a cascade, some channels were reporting error while others were not
then within 30 minutes all access to the api was down.


but thanks for the issue report

**Comment by bubibubibub** [comment]
Seems to work again.

**Comment by arrowgent** [comment]
not entirely.  its not giving errors but my LIVE followed list is only showing 10-15 people instead of the usual 30-40

**Comment by bastimeyer** [comment]
Looks like the API issue has been resolved by Twitch. Closing the thread and deleting the workaround branch...
