### ISSUE TITLE
Streams not loading

### ISSUE THREAD

**Issue by tylothon** [streamlink/streamlink-twitch-gui#892]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.1.0

### Streamlink version

3.2.0

### Operating system, environment and configuration details

Windows 11 home 64 bit

### Description

As of about 6/6, streamlink will load the stream and the first frame of it after it launched but it will not load anything else. I've uninstalled VLC, Streamlink and Streamlink Twitch GUI, and have reinstalled all applications after clearing the folders and all files associated to it. The problem still persists.

**Comment by bastimeyer** [comment]
Streamlink Twitch GUI is a launcher for Streamlink and has nothing to do with the streaming part. This is the wrong place to ask.

And Streamlink itself has nothing to do with your player issues. Your very vague description of "streamlink will load the stream and the first frame of it" suggests that you should check your player and its decoding/rendering configuration.

Uninstalling software also doesn't mean that all config files will be removed, so you should check that, too.

Either way, I can't help you with your VLC issues, and as said, this is not the right place to ask for this. If you can't fix it, try using a different player like MPV or MPC.
