### ISSUE TITLE
Facebook gaming live streams

### ISSUE THREAD

**Issue by DannyDarth** [streamlink/streamlink-twitch-gui#900]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Add a feature to see facebook live streams for popular streamers that moved from twitch to facebook.

**Comment by bastimeyer** [comment]
#192
#309
#415
#807
#875
