### ISSUE TITLE
Python window

### ISSUE THREAD

**Issue by githubaccount532623** [streamlink/streamlink-twitch-gui#904]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [x] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.1.0

### Streamlink version

streamlink 4.2.0

### Operating system, environment and configuration details

Windows 10 21H2

### Description

Every time I open a stream this python command window appears, it didn't appear before. Is it possible to remove it?
![2022-08-02_23-50](https://user-images.githubusercontent.com/108201728/182526601-ce8540d2-2a78-4cf8-b8fc-2100bb293360.png)

**Comment by githubaccount532623** [comment]
Choose the executable streamlinkW.exe

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/wiki/Streamlink-configuration

> On Windows, Streamlink Twitch GUI will look for the streamlinkw.exe executable instead of streamlink.exe (notice the trailing w), so that no command line window will pop up when launching a stream.
