### ISSUE TITLE
Watching previous streaming sessions

### ISSUE THREAD

**Issue by 2ral** [streamlink/streamlink-twitch-gui#908]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Can you please add ability to watch previous streams from channels which a user follows ( I mean recordings from video tab in a streamer's channel  on the twitch.tv) ?

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/81#issuecomment-314374666
