### ISSUE TITLE
VLC crashes while opening a stream

### ISSUE THREAD

**Issue by pflanzenandi** [streamlink/streamlink-twitch-gui#909]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [x] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

2.2.0

### Streamlink version

5.0.1

### Operating system, environment and configuration details

POP_OS 20.04
AppImage

### Description

Since the new Streamlink Twitch GUI version, it takes three tries for every stream for VLC (flatpak) to start properly. 
It seems this behaviour only occurs in the 'Followed Streams' category. If I start a stream e.g. from the 'Game' category, VLC opens immediately at first try.

**Comment by bastimeyer** [comment]
> VLC crashes while opening a stream

Streamlink Twitch GUI is not involved when it comes to launching streams or even the player. It is merely a browser and command line parameters generator for Streamlink, that's it. If you're having issues with your player, then check your player configuration and make sure your system is working correctly.

You can launch the Twitch GUI with the `--loglevel=debug` parameter and see the command line parameters it uses when running streamlink. Then use those to further debug your player issues by running streamlink from your command line shell. Streamlink allows you to see the player's stdout/stderr by setting the `--verbose-player` parameter. Good luck.

> It seems this behaviour only occurs in the 'Followed Streams' category.

There is literally no difference between clicking streams in the "followed streams" and "games" menus.

**Comment by pflanzenandi** [comment]
Ok, thank you. 

VLC doesn't start anymore but MPV works just fine.
