### ISSUE TITLE
No window appears upon launching Streamlink twitch gui

### ISSUE THREAD

**Issue by ktulsyan** [streamlink/streamlink-twitch-gui#919]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

Version 2.2.0 (2.2.0)

### Operating system, environment and configuration details

Trying to run on macOS Ventura 13.0

### Description

No window appears when I open the app. However, an icon does appear in the dock.
Upon right-clicking the dock icon and clicking "Show all windows" I see a message saying "No windows available"

Things I've tried:
Launch the app with debug logs and with --reset-window parameter

Log output:
```
❯ cat 2022-11-05_05-44-29.log
[2022-11-05T05:44:30.204Z][debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": true,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}

 ~/Library/Logs/streamlink-twitch-gui 
```

Additionally, I've also tried granting Full disk access to Streamlink Twitch GUI just in case that was the issue.

**Comment by bastimeyer** [comment]
Sounds like a duplicate of #911

Please try the latest version from the master branch:
https://github.com/streamlink/streamlink-twitch-gui#-download
https://github.com/streamlink/streamlink-twitch-gui#-build

I'm waiting for an NW.js bugfix (#913) before I can publish a new release.

**Comment by ktulsyan** [comment]
Working with latest commit from master . Thanks for the quick turnaround!
