### ISSUE TITLE
S-T-G doesn't work on macOS using OCLP

### ISSUE THREAD

**Issue by Gravarty** [streamlink/streamlink-twitch-gui#920]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.2.0

### Streamlink version

5.0.1

### Operating system, environment and configuration details

macOS Monterey 12.6.1

### Description

The app shows up in the dock and menu bar but the main window doesn't appear.

### Debug log

```text
[11290:259:1107/142841.424431:ERROR:iopm_power_source_sampling_event_source.cc(31)] IOPMPowerSource service not found
objc[11299]: Class WebSwapCGLLayer is implemented in both /System/Library/Frameworks/WebKit.framework/Versions/A/Frameworks/WebCore.framework/Versions/A/Frameworks/libANGLE-shared.dylib (0x7ffb56506ec8) and /Applications/Streamlink Twitch GUI.app/Contents/Frameworks/nwjs Framework.framework/Versions/105.0.5195.102/Libraries/libGLESv2.dylib (0x10fe189e8). One of the two will be used. Which one is undefined.
[debug][Application]
Parameters
{
    "_": [],
    "tray": false,
    "hide": false,
    "hidden": false,
    "max": false,
    "maximize": false,
    "maximized": false,
    "min": false,
    "minimize": false,
    "minimized": false,
    "reset-window": false,
    "versioncheck": true,
    "version-check": true,
    "logfile": true,
    "loglevel": "debug",
    "l": "debug",
    "launch": "",
    "goto": ""
}
```

**Comment by bastimeyer** [comment]
#911

**Comment by bastimeyer** [comment]
See https://github.com/streamlink/streamlink-twitch-gui/issues/919#issuecomment-1304440455
