### ISSUE TITLE
[Feature Request] Add Videos section to Channels

### ISSUE THREAD

**Issue by soonan5** [streamlink/streamlink-twitch-gui#937]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Hi, sometimes I can't watch my favorite streamer live, so I open: `https://twitch.tv/streamer/videos` in my browser, copy the video link and open it with [Streamlink](https://github.com/streamlink/streamlink).

![2](https://user-images.githubusercontent.com/109312533/205195860-db0ffacd-432e-4033-8b16-bf921864f88b.png)
![3](https://user-images.githubusercontent.com/109312533/205195892-99cc6474-e511-40ec-a917-f3baa80b4c98.png)

I do this as this category cannot be accessed using Streamlink Twitch GUI and I really wish it was possible as my computer consumes a lot of resources when I go to: [Twitch](https://www.twitch.tv/)

![1](https://user-images.githubusercontent.com/109312533/205195979-3ce329ce-7ad1-492f-8acf-bd0df6e9f6d3.png)

Do you think you can add this feature? Thanks!

**Comment by bastimeyer** [comment]
#81
