### ISSUE TITLE
streamlink: error: unrecognized arguments: best

### ISSUE THREAD

**Issue by MilarvozM** [streamlink/streamlink-twitch-gui#941]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

Not used

### Streamlink version

5.1.2

### Operating system, environment and configuration details

Windows 10 21H2, streamlink with default configs

### Description

I likely previously installed some version of streamlink, and when I attempted to update I installed a new version from [streamlink-5.1.1-1-py310-x86_64.exe](https://github.com/streamlink/windows-builds/releases/download/5.1.1-1/streamlink-5.1.1-1-py310-x86_64.exe). For a moment I see two Streamlink folder in my program files. Then I uninstalled both of them and reinstalled using the latest version, however I only have this command output:
`$ streamlink "https://fms2.uniqueradio.jp/agqr1/iphone3/HLS_Layer1.m3u8" best --player "C:\Program Files\DAUM\PotPlayer\potplayermini64.exe" --loglevel=debug
usage: streamlink [OPTIONS] <URL> [STREAM]
streamlink: error: unrecognized arguments: best
`
I don't see a detailed log anywhere even with the `--loglevel=debug` argument.

**Comment by bastimeyer** [comment]
Wrong repo. This is the Streamlink Twitch GUI repo, not Streamlink.

> ### Streamlink Twitch GUI version
> Not used

... :man_facepalming: 

----

> streamlink: error: unrecognized arguments: best

Check your Streamlink config file. The CLI arguments you've posted are fine, but the config file also gets read, so if you have a mistake there, then this can lead to a parameter parsing issue like this.
