### ISSUE TITLE
Can I use the GUI without signing up for twitch?

### ISSUE THREAD

**Issue by githb123** [streamlink/streamlink-twitch-gui#946]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

After starting the GUI it requires me to log in. I don't have and don't want an account on twitch. When I try browsing for games/streams nothing happens, the log in prompt is displayed in the middle all the time.

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/blob/master/CHANGELOG.md#v200-2022-01-31
