### ISSUE TITLE
Thumbnails of currently live streams randomly are multiple days old

### ISSUE THREAD

**Issue by bubibubibub** [streamlink/streamlink-twitch-gui#949]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

streamlink-twitch-gui-v2.2.0-win64-installer

### Streamlink version

streamlink-5.1.2-2-py311-x86_64

### Operating system, environment and configuration details

Prozessor	AMD Ryzen 7 3700X 8-Core Processor                3.60 GHz
Installierter RAM	64,0 GB
Systemtyp	64-Bit-Betriebssystem, x64-basierter Prozessor

Edition	Windows 10 Pro
Version	22H2
Installiert am	‎15.‎11.‎2020
Betriebssystembuild	19045.2486
Leistung	Windows Feature Experience Pack 120.2212.4190.0

### Description

For a few days now, stream thumbnails shown in Streamlink Twitch GUI randomly are multiple days old. In the example screenshot 1 from today, Dansgaming is shown playing The Forest but the thumbnail in Streamlink Twitch GUI is from the game Grounded, which he has last played 5 days ago. 

This is happening seemingly randomly at least for any followed stream. The thumbnail then is wrong in any view within Streamlink Twitch GUI. At the same time, thumbnails directly on Twitch are correct (see screenshot 2). Sometimes it's just one affected stream like in screenshot 1 and 3, sometimes it's multiple affected streams at the same time. 

The affected streams can change within the same session without restarting Streamlink Twitch GUI. In screenshot 3, which was taken just a few minutes after screenshot 1 and after refreshing a couple of times, the thumbnail for Dansgaming is seemingly correct. At least it's from The Forest, which he has been playing for the last 3 days. But the thumbnail for Bonjwa is definitely wrong and shows some video they reacted to a few days ago (not sure how many exactly but I know for sure it's been a couple) while actually they're playing Escape From Tarkov right now.

Restarting the app or refreshing the view doesn't fix the problem. The change from old to current thumbnail or vice versa happens seemingly random. 

I have tried deleting all files in the following directories and restarting the app to no avail:

%LOCALAPPDATA%\streamlink-twitch-gui\User Data\Default\Cache\Cache_Data
%LOCALAPPDATA%\streamlink-twitch-gui\User Data\Default\GPUCache

I have tried completely uninstalling Streamlink and Streamlink Twitch GUI and erasing every directory and file containing *streamlink* and then reinstalling both to no avail.

Did I miss something or is the Twitch API all of a sudden delivering old thumbnails randomly?

![1](https://user-images.githubusercontent.com/88854156/211681843-e1a2caff-5405-478b-8787-a69b5c89aa18.png)
![2](https://user-images.githubusercontent.com/88854156/211682763-f17becda-a22b-46ca-abd6-8056295404cb.png)
![3](https://user-images.githubusercontent.com/88854156/211683204-93ea7f4d-dbe3-4231-b934-de52e4cafde2.png)

**Comment by bastimeyer** [comment]
Thumbnails are provided by the Helix Twitch API as template URLs:
`https://static-cdn.jtvnw.net/previews-ttv/live_user_CHANNELNAME-{width}x{height}.jpg`

When making an HTTP request to a thumbnail image, Twitch sets the cache duration to 300 seconds / 5 minutes:
> cache-control: max-age=300
> date: Wed, 11 Jan 2023 00:20:02 GMT
> expires: Wed, 11 Jan 2023 00:25:02 GMT

In addition to that, Streamlink Twitch GUI sets an additional query string parameter for "cache-busting" reasons, via a query string that includes the current timestamp and an expiration time of 60 seconds / a minute:
- https://github.com/streamlink/streamlink-twitch-gui/blob/v2.2.0/src/app/data/transforms/twitch/image.js
- https://github.com/streamlink/streamlink-twitch-gui/blob/v2.2.0/src/config/vars.json#L8

If Twitch is sending old thumbnail images, then this is not a Streamlink Twitch GUI issue. There is no local caching of stream thumbnail images apart from Chromium's internal caching, and this caching implementation is behaving correctly according to the HTTP headers and the expiration cache-busting query string.

The only images that get cached explicitly by Streamlink Twitch GUI are channel profile pictures, for being able to show them on desktop notifications, and the caching time here is one week, but that's entirely unrelated.
