### ISSUE TITLE
Automatically/Manually Sign-in

### ISSUE THREAD

**Issue by HDark15** [streamlink/streamlink-twitch-gui#951]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

I set the app to be running on start-up, and the device has no internet connection when it starts. The opened app that said you need to sign in, after that when being connected to the internet there's no way to refresh the app to be signed in. The only way to be signed in is to re-open the app, then it will automatically be signed in.

I hope there are features to automatically detect being connected to the internet, then refresh the app or manually click a button to be signed in.

**Comment by bastimeyer** [comment]
Not interested in such a feature. Launch the application when you have a functioning internet connection. How you can do this depends on your operating system. Good luck.
