### ISSUE TITLE
system proxy

### ISSUE THREAD

**Issue by bimozhiyani** [streamlink/streamlink-twitch-gui#957]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

can add a system proxy option ?  It's useful for me now.

**Comment by bastimeyer** [comment]
> --proxy-server=...

https://peter.sh/experiments/chromium-command-line-switches/#proxy-server

**Comment by bastimeyer** [comment]
And for Streamlink:
https://streamlink.github.io/cli/proxy.html
https://streamlink.github.io/cli.html#cmdoption-http-proxy
