### ISSUE TITLE
Japanese Localization Support

### ISSUE THREAD

**Issue by akawshi** [streamlink/streamlink-twitch-gui#961]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Localization is currently supported in only a few European and Chinese languages, not Japanese.  
  
According to external site statistics, 10% of Twitch users speak Japanese, and Japanese speakers usually don't understand English. Fewer people will use the Streamlink Twitch GUI without Japanese support.

**Comment by bastimeyer** [comment]
This isn't something I can do myself. Submit a pull request if you want to see translations for your local language.

Adding translations is a community effort. I won't pay any service to add translations for various languages and I also won't spend any time on implementing integrations for certain free services where translations can be submitted externally.

If anyone wants to add translations for Streamlink Twitch GUI, they'll have to follow this guide or figure it out on their own, which isn't that difficult:
https://github.com/streamlink/streamlink-twitch-gui/wiki/Translating

https://github.com/streamlink/streamlink-twitch-gui/pulls?q=is%3Apr+is%3Amerged+label%3Ai18n+sort%3Aupdated-desc

**Comment by akawshi** [comment]
Thanks for your reply

I would try it anyway
