### ISSUE TITLE
any variable other than {name} doesn't work with "--sout" in VLC

### ISSUE THREAD

**Issue by moswald14** [streamlink/streamlink-twitch-gui#975]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.3.0

### Streamlink version

6.0.1

### Operating system, environment and configuration details

Windows 10 22H2

### Description

trying to run VLC with this arg `--sout="#transcode{vcodec=mp4v,acodec=mpga,vb=4096,ab=128,deinterlace}:standard{access=file,mux=ts,dst='D:\TwitchStreams\{name}-{online}-{status}.mpg}'"`
But it doesn't seem to work, the VLC window just "stutters" until it crashes or I close it.

using just {name}.mpg works, but no other variable works by itself either

I read the Documentation, but it doesn't matter where I put quotes, and sometimes quotes make VLC completely unresponsive

**Comment by bastimeyer** [comment]
Launch the Twitch GUI with the `--loglevel=debug` argument and check the player command line that's built when launching a stream
https://github.com/streamlink/streamlink-twitch-gui/wiki/Parameters

**Comment by moswald14** [comment]
running it with just {online} (still stuttering) yields:
`[2023-08-05T19:54:05.291Z][debug][StreamingService]
Spawning process
{
    "exec": "E:\\Streamlink\\bin\\streamlinkw.exe",
    "params": [
        "--twitch-disable-ads",
        "--webbrowser",
        "true",
        "--webbrowser-headless",
        "true",
        "--player",
        "C:\\Program Files\\VideoLAN\\VLC\\vlc.exe",
        "--player-args",
        "--sout=\"#transcode{vcodec=mp4v,acodec=mpga,vb=4096,ab=128,deinterlace}:standard{access=file,mux=ts,dst='D:\\TwitchStreams\\Sat Aug 05 2023 08:48:33 GMT-0400 (Eastern Daylight Time).mpg}'\" --no-one-instance --play-and-exit",
        "--retry-open",
        "1",
        "--retry-streams",
        "1",
        "twitch.tv/dansgaming",
        "best"
    ],
    "env": null
}`

**Comment by bastimeyer** [comment]
I don't see any problems with the player arguments which the Twitch GUI generates from the variables you've set.

If you're having issues with your video player, then I can't help and you'll need to resolve them on your own.

Why are you even re-encoding the stream? Then you don't have to wonder if you're having performance issues. This is out of scope of Streamlink and Streamlink Twitch GUI. You're on your own here.

**Comment by moswald14** [comment]
just trying to record streams to save locally, is there a way to do this without VLC?
thanks for your quick replies!

**Comment by bastimeyer** [comment]
https://streamlink.github.io/cli.html#file-output-options

If you want to record, then don't re-encode, just remux. Check the VLC docs if you don't want to use Streamlink for that. Streamlink Twitch GUI is not designed with recording in mind.
