### ISSUE TITLE
VLC config paramter no longer working after updating to v2.3.0

### ISSUE THREAD

**Issue by TrantaLocked** [streamlink/streamlink-twitch-gui#978]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Streamlink Twitch GUI version

v2.3.0

### Streamlink version

v6.0.1

### Operating system, environment and configuration details

Windows 11 22H2

### Description

I have a VLC config for a specific skin that i would load using --config=C:\...\vlcrc in the Custom Parameters field that worked fine before but no longer works after updating.

**Comment by bastimeyer** [comment]
> * I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**

Read the changelog of Streamlink 6.0.0:
https://github.com/streamlink/streamlink/releases/tag/6.0.0

**Comment by TrantaLocked** [comment]
I have found that just adding quotes around the argument fixes the problem:

`"--config=C:...\vlcrc"`
