### ISSUE TITLE
Request to run on windows 7

### ISSUE THREAD

**Issue by Boladoxd** [streamlink/streamlink-twitch-gui#984]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

First of all sorry for my english, i don´t speak english but  I understand the basics. So a took a look in the project and I got interested and installed it but I noticed that it doesn't run on Windows 7 (my system) and i created this topic just to request you developers to make it run in windows 7 if you can and if it's not too much work to do it. thank you for the app and thanks for the attention :)

**Comment by bastimeyer** [comment]
https://github.com/streamlink/streamlink-twitch-gui/issues/976#issuecomment-1666976973
