### ISSUE TITLE
kill streamlink-gui if already open and try to open it again

### ISSUE THREAD

**Issue by killertofus** [streamlink/streamlink-twitch-gui#991]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

kill streamlink-gui if already open and try to open it again
like in #704

**Comment by bastimeyer** [comment]
Is this a question or what is this?

Just kill the process of the GUI. I'm not here to teach you how to use your operating system. You didn't even mention your OS.

```sh
pkill -f "path/to/the/executable/of/streamlink-twitch-gui"
```

**Comment by killertofus** [comment]
sometimes streamlink crashes, you try to open it again  but it never opens, you try to kill it then it works, it needs to auto kill if opening it when it's already "open", sorry for not being descriptive
