### ISSUE TITLE
[Closed thread, more info] "Could there be an option to ALLOW advertisements?" Ublock Origin prevents ads on Twitch.tv!

### ISSUE THREAD

**Issue by vrement** [streamlink/streamlink-twitch-gui#997]
### Checklist

- [X] I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**
- [X] [I have read the contribution guidelines](https://github.com/streamlink/streamlink-twitch-gui/blob/master/CONTRIBUTING.md)
- [X] [I have checked the list of open and recently closed issues](https://github.com/streamlink/streamlink-twitch-gui/issues?q=is%3Aissue+sort%3Aupdated-desc)
- [X] [I have checked the commit log of the master branch](https://github.com/streamlink/streamlink-twitch-gui/commits/master)

### Description

Ublock Origin (or Privacy Badger) does block all advertisements while watching Twitch streams on the website twitch.tv. So could one or the other somehow be added to the operation of Streamlink-Twitch-GUI? Also Ublock Origin works against YouTube ads on that website (though other adblockers won't).

**Comment by bastimeyer** [comment]
> * I understand that **Streamlink Twitch GUI** is just a launcher for **Streamlink**

**Comment by vrement** [comment]
And this is in the way that the stream itself continues without ads showing, none whatsoever. But watching through streamlink-twitch-gui comes the silent long purple screen. Could this be utilized?

**Comment by bastimeyer** [comment]
Read the Streamlonk docs if you're seeing "the purple screen". The Twitch GUI implements ads filtering.
